### ISSUE TITLE
WithRouter(FromConfig.Instance) blows up if no config is supplied

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1013]
```csharp
Props.Create<TileRenderActor>().WithRouter(FromConfig.Instance),"myactor");
```

This line throws if there is there is no deployment config specified for "myactor".
It should just assume that the config is empty and use defaults

**Comment by Aaronontheweb** [comment]
I actually don't think this is a bug. Rather than fail silently, you should be told if your expected configuration wasn't found.

**Comment by rogeralsing** [comment]
We need to look this up.
Imo, akka is largely based on the idea that you should just have to change the config and not the code to change how the application behaves.
And in this case that doesnt work, you need to change both config and code.

And even if this is the intended behavior, the given error message is cryptic and not helpful.

**Comment by Aaronontheweb** [comment]
> Imo, akka is largely based on the idea that you should just have to change the config and not the code to change how the application behaves.

I agree with that, but this is a case where there's either an application error or a configuration error. You should be able to switch the router implementation solely through configuration, but not whether or not a particular deployment is a router or not. That has to be done through code with `FromConfig` too because the relationship between the actor implementation being created and the `IActorRef` (whether it's a ref to a router or a concrete implementation) is supposed to be explicit.

> We need to look this up.

Totally agree. I tried to look that up myself earlier today but I think this is an instance where this happens via type-loading in the JVM. 

> And even if this is the intended behavior, the given error message is cryptic and not helpful.

Also agree. Should throw a `AkkaConfigurationException` with a clear error message if this is the case.

**Comment by rogeralsing** [comment]
Turns out that we throw the exact same excepton message as JVM Akka does. I guess we have to stick with that then :)
