### ISSUE TITLE
Akka.Persistence + Akka.Remote/Cluster serializes port numbers in journal/snapshot

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1074]
When Akka.Remote (Or cluster) is active, Akka.Persistence will serialize all messages using the systems `DefaultAddress`, so any serialized `ActorRef` in any message or state will contain the host and port number.

This means that if you use Akka.Remote with dynamic port numbers, if you restart (as in reboot a new process) the system and the system now gets a different portnumber.
Any message read from the snapshot store or journal will see actorrefs pointing to a system that no longer exists.

I don't think this is a bug but it will definitely bite some users in the butt in the future. so I bring this up here so we can at least document this.
Does JVM Akka allow dynamic port numbers or is this something we introduced?

I guess the reason why actorrefs are being serialized with an address is if remote actors consume the same journal (is that possible?) 
If not, I dont see why actorrefs are not just being serialized as local address-less refs, and the address can be re-augumented if the same message is passed to a remote node for some reason (which would be done automatically)

Thoughts on this.

cc @rkuhn , can you enlighten us on this matter?
cc @Aaronontheweb @Horusiath @akkadotnet/developers

**Comment by Aaronontheweb** [comment]
> `ActorRef` in any message or state will contain the host and port number

depending on a serialized `IActorRef` in any persisted message is a playing with fire to some extent - `IActorRef`s are guaranteed to have existed some time in the past; there's never any guarantee that they still exist upon rehydration of messages from a persistent store.

This is why the `AtLeastOnceDeliveryActor` uses an `ActorPath` as its persistent target instead - so it can recreate an `ActorSelection` on the fly if it has to, possibly from a different node / position in the actor hierarchy.

> Does JVM Akka allow dynamic port numbers or is this something we introduced? 

JVM Akka and Netty both allow this. It'd be frustrating to debug / test applications locally without it.

> I guess the reason why actorrefs are being serialized with an address is if remote actors consume the same journal (is that possible?) 

That's just the default way that `RemoteActorRef`s get serialized. You can extract the `ActorPath` from the `IActorRef` and serialize it with [`ToStringWithoutAddress`](http://api.getakka.net/docs/stable/html/3A3942BF.htm) and that should give you a non-remote address for it.

**Comment by rogeralsing** [comment]
Yes, i know how to get a local path. But the akka persistence code explicitly makes it a remote path with address.
I would like to know the reason behind this.

**Comment by rkuhn** [comment]
Whether with or without host & port, the result will be the same: since an ActorRef points to a specific incarnation it will need to be invalid after an ActorSystem restart—if you keep the same Address the new ActorRef will still have a different UID. Storing the fully qualified ActorRef in the journal makes sense for replay on different nodes, which is not a far-fetched scenario.

What Aaron was getting at is that this is the semantic difference between ActorRef and ActorPath, and if you want to persist just the name then ActorPath is the way to go. ActorRef has a very specific meaning, see [the lifecycle](http://doc.akka.io/docs/akka/2.3.11/scala/actors.html#Actor_Lifecycle).

**Comment by rogeralsing** [comment]
So why was it implemented using explicit remote ref serialization on the JVM? 
Can that code be removed?

**Comment by rkuhn** [comment]
As I said: having the full address in there makes a lot of sense in valid use-cases, and removing the remote information does not help anyone; or am I missing something?

**Comment by rogeralsing** [comment]
Its probably just me that is not seeing the bigger picture here.

Isn't the persistent state supposed to be idempotent, so that when you replay all your events, you get back to the exact same state that you had before restart?
If the journal contains actorrefs, that can be either valid or dead, that will not be possible, you will end up with state that is similar but not the same (e.g. if the replay mechanism relies on any of those actorrefs being used).

If you as you say want to replay the events on different nodes, that requires the system that wrote the events to still be up and still be the same instance. 
if it is not, the actorrefs in those messages are no longer useful.

My issue is that this looks sort of undefined. things will behave in one way as long as the writing system is up, and in another way when the writing system have rebooted
Do I make any sense at all here? :)

**Comment by rkuhn** [comment]
/cc @patriknw

If the journal contains ActorRefs then the desired semantics are that they shall be invalid when the Actors they pointed to are terminated—this needs to be consistent with all other uses of ActorRefs. This has nothing to do with idempotence, I think you meant omnipotence ;-) Seriously, though, there is nothing undefined here, to the contrary, everything is quite well defined.

Another angle: The events that are emitted by a PersistentActor shall only signify how its state shall change within the domain model and in almost all cases the domain model does not contain ActorRefs, simply because PersistentActor is not an Aggregate Root but instead it only encapsulates one; the use of Actors is an implementation detail.

One example that you might think of is a Process Manager that interacts with some Aggregate Roots in different Bounded Contexts. Implementing this such that ActorRefs are persisted might be possible (and even make sense), but it does imply that the process itself will notice when its interlocutors crash and recover (beyond a simple Actor restart). More typically, though, this will be implemented using logical IDs and service names, so that e.g. ClusterSharding is used to relay the messages between the Process Manager and the other Aggregate Roots, in which case the issue of ActorRef serialization does not come up.

**Comment by rogeralsing** [comment]
Thanks for the clarification.
I was talking to @Horusiath the other day about this an none of us knew why the transport information was used in the way it was for persistence. 
Closing this :)

**Comment by patriknw** [comment]
One use case where the full address is needed is Cluster Sharding. It saves ActorRefs of the active regions and when the coordinator is restarted on another node it should restore its state to the same as before, i.e. the ActorRefs must contain full address. Otherwise the ActorRefs that were local (no host:port) at the first location are not valid any more at a different location.
