### ISSUE TITLE
Akka.Di.Core 1.0.3 changed DI?

### ISSUE THREAD

**Issue by nibblesnbits** [akkadotnet/akka.net#1076]
Unless I'm doing something wrong, it seems DI is now completely non-functional in Akka.Net 1.0.3.  

When I try to create an actor the old way: 

```csharp
Context.DI().ActorOf<ClientProcessingActor>()).Tell(new ProcessClientsMessage {
    Clients = _clients
});
```

I get the `Obsolete` message from `DIActorContextAdapter`

```csharp
[Obsolete("Use Props methods for actor creation. This method will be removed in future versions")]
```

And yet when I use the normal way as it suggests:

```csharp
Context.ActorOf(Props.Create<ClientProcessingActor>()).Tell(new ProcessClientsMessage {
    Clients = _clients
});
```

The context never creates the actor; it fails silently.

Is this a known bug?

I'm setting the resolver with this line...

```csharp
new Akka.DI.Unity.UnityDependencyResolver(IocContainer.GetConfiguredContainer(), system);
```

... which, to be honest, feels a bit wrong, anyway.  I feel like it should be something like:

```csharp
system.DependencyResolver = new Akka.DI.Unity.UnityDependencyResolver(IocContainer.GetConfiguredContainer())
```

The current syntax just doesn't emit clear intentions.

**Comment by nibblesnbits** [comment]
Ok, so [this method](http://getakka.net/docs/Dependency%20injection#creating-child-actors-using-di) works:

```csharp
var diExt = Context.System.GetExtension<DIExt>();
var props = diExt.Props(typeof(ClientProcessingActor));
Context.ActorOf(props).Tell(new ProcessClientsMessage {
    Clients = _clients
});
```

So really it's a documentation and syntax problem.  The `Obsolete` message isn't clear on the correct way to do things, and the general syntax is just not very clear for any of this.

**Comment by Danthar** [comment]
First: Your right. The current syntax for registering the DI extension is abit non-intuitive. The reason its like that is because its the same as in the JVM Akka. Which since this is a Port of that, is something the project needs to adhere to.

That said, even though the project needs to adhere to certain rules, there is some leeway. Not sure if this falls into that category. That depends on how the core contrib team feels about that.

Secondly: There has already been lots of discussion on syntax of the DI system. And its already been decided its going to change. Hence the `Obsolete` attribute on the `DI()` extension method. The DI system syntax changes will probably be finalized in next Major version increase of Akka.Net. 

But your right that the documentation on the website should better promote the 'new' way of using DI and explain that the 'old' way will be deprecated in time.

**Comment by Danthar** [comment]
Did an PR for the site improve the docs on this issue. https://github.com/akkadotnet/getakka.net/pull/85

**Comment by rogeralsing** [comment]
docs updated
