### ISSUE TITLE
Port Finite State Machine DSL to Akka.Persistence

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1096]
Port [FSM](https://github.com/akka/akka/tree/master/akka-persistence/src/main/scala/akka/persistence/fsm) to Akka.Persistence. Nice thing to consider is support for recovering mechanism to update not only actor's state, but also it's behavior at the end of recovery cycle.

**Comment by maxim-s** [comment]
I can do it

**Comment by maxim-s** [comment]
I've checked [FSM](https://github.com/akka/akka/tree/master/akka-persistence/src/main/scala/akka/persistence/fsm) Akka.Persistence and [FSM](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/FSM.scala) for Akka.Actor also we already have [FSM](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Actor/FSM.cs) for Akka.Actor and looks like scala implementation has at least 80% the same code. Will we do it by the same way, or try to extract common things and reuse? @Horusiath what do you think about it?

**Comment by Horusiath** [comment]
@maxim-s if it's possible to not duplicate code, that would be great. Since C# doesn't offer traits like scala does, the implementation should probably rely on composition.

**Comment by maxim-s** [comment]
Hello @Horusiath , 
I hope you are fine. I've tried to implement this issue in different ways.  I tried to extract common things into separate class and to do it by composition instead of inheritance, but I had dome problems with it, and decided to do separately. So as  result I've got a problem with persist untyped events and restore their  state by events. What do you think if I will persist events with their current states?

**Comment by rogeralsing** [comment]
Has this one been merged?

**Comment by Horusiath** [comment]
Yes, PR #1394. This can be closed.
