### ISSUE TITLE
Can we run multinode testkits using different transports?

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1161]
As we now have two different transport, Helios and Akka.IO transport, would it be possible to run the remoting/cluster tests using both transports?
I think that would be very good for finding bugs, 
e.g. if some test fail using both transports, its likely that either the test is wrong or the remoting/cluster code is wrong.
If only one of the transports fail, its likely that there is some issue in that specific transport.

There are some shaky bits in these areas and having the ability to pinpoint the origin would be extremely helpful IMO.

**Comment by Aaronontheweb** [comment]
Sure, you can do this - just need to run the tests twice one with each transport and run them with different configurations.

**Comment by njimenez** [comment]
I am going to take a crack at this problem.
The way I understand it is that we would like to run the tests twice, each time with a different transport.
As of now, the tests are hard coded to use a configuration that specifies or defaults to helios. In order to allow the tests to change configuration, the test would need to figure out which transport we want to use in each run. Since we can't pass parameters to the test runner (at least I haven't found a way), the next best solution in my opinion would be to set up an environment variable that will be read by the tests and change its behavior as specified. Then when running the tests, I would set the environment variable to "helios", run the tests and then reset the environment variable to "akka.io" and re-run the tests. The tests will read the environment variable and supply the correct configuration instance.
That way if another transport is added we just change the variable to describe it and tests will change accordingly, and we would be able to run with as many transports as we support.

**Comment by willieferguson** [comment]
There is an ousting bug #1357 for the akka-io transport. I will send a PR with a fix soon.

**Comment by njimenez** [comment]
I have the tests running with Helios and AkkaIO in separate runs. Now I need you to point me to where I can find a good configuration for AkkaIO. So that I can start adding the config where needed.

**Comment by willieferguson** [comment]
Should we not have some generic way to run a test with multiple configurations? I was looking at using something like a 'Theory' in xunit. E.g.

``` csharp

class MySpec : AkkaSpec
{

   [Config(@"actor { remote { helios.tcp { ... } } } }")]
   [Config(@"actor { remote { akka-io { ... } } } }"")]
   public MySpec() : base(@"actor { actor.provider = ""Akka.Remote.RemoteActorRefProvider, Akka.Remote"" }") {

   }
}

```

The above will then run each fact twice - with diffirent configurations.

**Comment by njimenez** [comment]
It sounds like a good idea but unfortunately, I don't think we can apply Theories to constructors, AFAIK.
Also if one wanted to only run tests for a particular transport, they would have to comment out the theories they don't want to run; as opposed to just doing build.cmd helios, or build.cmd akkaio.
