### ISSUE TITLE
Add querying messages for Akka.Persistence.Sql.Common

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1227]
After talk with @nvivo , a some ideas arised there. One of them is extending existing sql-based journals API to allow to query the journal to receive stream of all events not partitioned by persistence Id, using some select criteria instead. This could be part of the solution for aggregating events from different persistent actors.

In akka google group [thread](https://groups.google.com/forum/#!topic/akka-user/MNDc9cVG1To) Roland Khun reminded that while each journal must satisfy basic journal API, some of them may also provide their own, based on underlying provider specs.

**Questions**

1. It should be allowed to replay all events in journal from some point in time. This mean, that event database should be enriched with some kind of timestamp column. And this would require schema change.
2. What other criteria should be able to filter? Event type, persistence id inclusion/exclusion?

What is your opinion @akkadotnet/developers ?

**Comment by nvivo** [comment]
There is a lot of discussion on that thread, but the main point I think needs some thought is that currently there is no API to do projections.  As Roland said:

> PersistentView basically does nearly the right thing, but it focuses on the wrong aspect

So, when using projections, the PersistenceID is pratically useless. On a real application, for basic projections you will at minimum listen for multiple event types from different aggregates instead. For example, imagine a forum and you want a projection to tell you the users that created topics that generated the most answers. You will want to listen to events like:

* UserRegistered
* TopicCreated
* AnswerPosted

Each of these events will be part of different aggregates, and the aggregate id doesn't matter.

From what I understood in the discussion it seems Akka direction on that is:

* The official API should provide only methods that will be used by most or all plugins, and there is some debate on what exactly that is
* There should be a way to specify custom queries without requiring effor from plugin maintainers - that probably means just a "custom" object where we implement the query logic, and that makes me wonder what could akka provide that wouldn't be harder than just querying the eventstore manually
* The ordering or events between aggregates may be important but that should depend on the backend implementation, not on akka - that means if I subscribe to "UserRegistered" and "TopicCreated", a backend on a single SQL server may return data ordered between aggregates while a sharded document store will provide no such guarantee

Also, it's very important to provide a good story on how to persist the data outside of akka. Projections will usually be stored on a relational or document database, and the process of starting the actor will require going to that database and deciding how to recover, checking event versions, etc. My view is that for commercial apps, projections outside of akka will be the most common case, not the exception.

Akka doesn't need to implement these details, but I'd like to see some guidance on how to achieve that by leveraging what the framework provides, so we know what is provided by the framework and what is our job to code.

What I'm implementing currently is something along the lines of:

```cs
QueryByEvents(long initialGlobalSequenceNr, string[] eventNames)
```

In this case I'd have a global sequence number for events that maintains ordering. That's easy on single server but if you add sharding, things get complicated. Or:

```cs
QueryByStream(string someStream, long initialSequenceNr)
```

Where that stream would be created by the server outside of akka persistence, similar to how Greg Young's EventStore works, by creating an index of links to events. The output looks like what Akka Streams will allow.

The problem is that both of these methods cannot be implemented by default inside akka without some assumptions or restrictions on the store. I'd be interested to know what other people think can be implemented in the API.

**Comment by Horusiath** [comment]
Closing this one, as initial solution was already added in v1.0.5. Further progress on that will be continued, once Akka.Streams will come out.
