### ISSUE TITLE
ReceiveActor behavior-switching + caching bug

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1238]
Akka.NET bootcamp attendee found a really strange bug with the `ReceiveActor`, which I believe to be an error with its caching and optimization system.

```csharp
 public class ApplicationActor : UntypedActor
    {
        private int count = 0;
        private ICancelable cancellation;
        private IActorRef _coordinator;

         public ApplicationActor(IActorRef coordinator)
        {
            _coordinator = coordinator;
        }

        protected override void PreStart()
        {
            Console.WriteLine("Prestart called!");

            count = 0;
            cancellation = Context.System.Scheduler.ScheduleTellRepeatedlyCancelable(
                TimeSpan.FromMilliseconds(500), TimeSpan.FromMilliseconds(5000), Self, "check", Self);

        }

        protected override void PreRestart(Exception reason, object message)
        {
            Console.WriteLine("PreRestart called!");
        }

        protected override void PostStop()
        {
            Console.WriteLine("PostStop called!");

            cancellation.Cancel();
            Context.System.Scheduler.ScheduleTellOnce(TimeSpan.FromSeconds(1), _coordinator, "stopped", ActorRefs.Nobody);
            base.PostStop();
        }

        protected override void OnReceive(object message)
        {
            count++;
            Console.WriteLine("Count = {0}", count);

            if (count > 2)
                _coordinator.Tell("shutdown");
        }
    }

    public class ApplicationCoordinatorActor : ReceiveActor
    {
        IActorRef _applicationActor;

        public ApplicationCoordinatorActor()
        {
            Stopped();
        }

        private void Started()
        {
            Console.WriteLine("Coordinator started");

            Receive<string>(s => s.Equals("shutdown"), s =>
            {
                Context.Stop(_applicationActor);
            });

            Receive<string>(s => s.Equals("stopped"), s =>
            {
                Become(Stopped);
            });
        }

        private void Stopped()
        {
            Console.WriteLine("Coordinator stopped");

            _applicationActor = Context.ActorOf(Props.Create(() => new ApplicationActor(Self)), "Application");
            Become(Started);
        }
    }
```

This code, when it runs as-is, produces the following output:

Coordinator stopped
Coordinator started
Prestart called!
Count = 1
Count = 2
Count = 3
PostStop called!
Coordinator stopped
Coordinator started
Prestart called!
Count = 1
Count = 2
Count = 3
**<------------ SHOULD stop / restart here**
Count = 4
Count = 5

Issue appears to be that the `ReceiveActor` actually caches `_applicationActor` somewhere and never updates it. 

cc @HCanber @rogeralsing any thoughts on why this might be happening?

**Comment by rogeralsing** [comment]
I think there is something else going on, refactoring the code to:
```csharp
      private void Started()
        {
            Console.WriteLine("Coordinator started");

            Receive<string>(s => s.Equals("shutdown"), s =>
            {
                StopAppActor();
            });

            Receive<string>(s => s.Equals("stopped"), s =>
            {
                Become(Stopped);
            });
        }

        //we are out of the compiled closure and in normal code here
        private void StopAppActor()
        {
            Context.Stop(_applicationActor);
        }
```

I moved the stopping to a normal method so we are not executing inside one of the compiled receive closures, and the behavior is still the same.

**Comment by Aaronontheweb** [comment]
@rogeralsing I'd love to know what it is, because this one stumped me :\

**Comment by rogeralsing** [comment]
Hmmm. I rewrite the coordinator to an untyped actor and then it all works fine. super weird this one...

**Comment by rogeralsing** [comment]
Found the cause

This part:

```csharp
            Receive<string>(s => s.Equals("stopped"), s =>
            {
                Become(Stopped);
            });
```

can be changed to

```
            Receive<string>(s => s.Equals("stopped"), s =>
            {
                Stopped();
            });
```

There is no receive behavior inside "Stopped" its just an imperative func doing stuff. doing that makes it all work.
I _think_ that the problem is that this example does a "Become(stopped)" which in turn inside the stopped, does a "Become(started)" .
I suspect that the Become for receive actors does its magic and at the end of it all, sets the behavior that was specified. which would be "stopped"

if you place a "ReceiveAny" inside stopped, you will see that the "Shutdown" messages are indeed handled by the "Stopped" behavior and not the "Started" after the first run.

I'm not even sure if this could be called a bug, as it is strange to have a behavior that just do imperative stuff and then immediately switches to another behavior, that is not the intention for become, it is to set up message handlers, which is not done here.

**Comment by Aaronontheweb** [comment]
Yeah, I found the same thing when I was working through this in the Akka.NET Bootcamp chat room.

I agree that this is a weird way to use behavior-switching... But that being said, the code inside the behavior-switched statements DID run. What was weird was it looked like the `IActorRef` being assigned to `_applicationActor` was cached somehow. Is that because we switched behaviors twice in the same pass? Or is there something the `ReceiveActor` is doing to optimize stuff under the hood?

**Comment by rogeralsing** [comment]
From Håkans ReceiveActor docs:
http://getakka.net/docs/ReceiveActor

>Note
In this case care must be taken to ensure that the number of Unbecome() matches the number of Become(..., discardOld: false) ones in the long run, otherwise this amounts to a memory leak (which is why this behavior is not the default).
Warning
**Do not add other statements than Receive in Become-declarations. The result of doing so is undefined**

**Comment by rogeralsing** [comment]
I vote for closing this as the example falls under invalid use imo.

**Comment by Aaronontheweb** [comment]
I agree
