### ISSUE TITLE
Remote deployed actors fail with super unintuitive exception when remote system does not reference actor types

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#1279]
Found this from an issue in https://github.com/IdleLands/IdleLandsRedux/tree/akka-refactor today.

The scenario was that the remote system did not reference the assembly holding the actor types.
Which made the `DaemonMsgCreateSerializer` create a `Props` object with no type, which in turn resulted in `DefaultProducer` being used, which in turn resulted in a exception, far far away from the actual problem.
There should be two fixes here IMO.
1. Make `Props` throw if the type passed is `null`
2. Make  `DaemonMsgCreateSerializer` throw if `var clazz = Type.GetType(proto.Props.Clazz);` results in `null`

In the latter case, if the proto.Props.Class holds a value, and `clazz` is null, then clearly there is a missing reference in the remote system

**Comment by rdavisau** [comment]
Hi @rogeralsing, I can look at this one.

I think we can't perform the null check in the [main constructor](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Actor/Props.cs#L238:L244), because the [parameterless constructor](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Actor/Props.cs#L165:L168) passes `null` in the type parameter; I guess it's there to support deserialization and maybe some subclasses?
```csharp
protected Props() 
    : this(defaultDeploy, null, noArgs)
{
}
```
In that case, I would be adding the check to each of the other ctors and static `create`-style methods. Does this sound reasonable?

**Comment by rogeralsing** [comment]
Yes that sounds like the correct way to go about it.
