### ISSUE TITLE
Target Akka.NET for .NET versions 4.0 and 3.5

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1313]
This subject appears in discussions from time to time, so I think we should have some general thread for that. It seems that most interested group of people are Xamarin/Unity3D programmers ;) .
### .NET 4.0

I've made short investigation (read: I've successfully compiled core Akka.dll) for .NET 4.0. Some notes:
1. System.Collections.Immutable is missing - this could be fixed using [Rackspace.Collections.Immutable](https://www.nuget.org/packages/Rackspace.Collections.Immutable/) library, which is defined to be backward compatible for version 3.5 and above.
2. Some task methods are missing, including: `CancellationTokenSource.CancelAfter`, `Task.Delay`, `Task.ResultFrom`, `Task.WhenAll`, `Task.WhenAny` and whole `ExceptionDispatchInfo`. I'm not sure if there is a purpose to use [Microsoft.Bcl.Async](https://www.nuget.org/packages/Microsoft.Bcl.Async/) - mostly because of mono - but most of the missing methods can be easily recreated. 
3. Most of async/await is centered around CircuitBreaker implementation.

Summary: targeting 4.0 can be definitelly done.
### .NET 3.5

Here the story is much more complicated, as 3.5 doesn't support `Task` at all. Even thou we could remove tasks based dispatchers, the situation is more complicated when it comes to tasks usage inside akka classes.

Is it possible to target 3.5? My guess is probably yes, but this will require much more effort and limit the list of available features. It may turn out, that we'll need some custom Task implementation here...

**Comment by rogeralsing** [comment]
If Unity3D is the thing we are targeting here, shouldnt we just wait for them to migrate to CoreCLR or whatever their latest strategy is?

**Comment by jweimann** [comment]
The Unity3D roadmap has the .Net update still in the "research" area.  It could a year or more before it actually comes out.  The method for doing async stuff in Unity is also quite a bit different, as mentioned above there's no Task, and I've never seen anyone use the ThreadPool in a Unity project either.  It's all done via their Coroutine system so that it works across all the different device platforms.  I don't know how much I could help with this, but I'd be happy to do what I can.

Here's the roadmap:
http://unity3d.com/unity/roadmap/

**Comment by rogeralsing** [comment]
Making Akka.NET work w/o any threading support feels a bit far fetched. even if we make a scheduler that can run actors on Unity Coroutines, we would still need Akka.Remote and the underlying transport lib to also run w/o tasks/threads etc.

**Comment by Aaronontheweb** [comment]
@rogeralsing might be possible - those are just dispatcher implementations.

Truth of the matter is though, managing a build for all of these .NET targets with different BCL dependencies and lots of `#ifdef` macros is going to be an epic pain in the ass. Given how much other stuff we have going on in the main repository, I am not supportive of doing this inside the main project at this time.

My recommendation is to have someone create a community fork that supports Unity3D's 2008/2009-era .NET runtime until such a time when they're able to rejoin civilized .NET society :p

**Comment by dkoontz** [comment]
For anyone considering doing the Unity3d support, here is work done to make Task & friends available in Unity's mono: http://spicypixel.com/developer/concurrency-kit/

**Comment by TeaDrivenDev** [comment]
I would also be very interested in .NET 4.0 support for a rather "boring" reason - we write WPF enterprise desktop software and can only use what we can be certain will run on client machines at the various customers. Currently the only definitive guarantee we have is 4.0.

I have a few places where I'd hope to improve things a lot with Akka.NET; that route is currently blocked until we can move up to .NET 4.5, so I'd love to see "legacy support" for 4.0.

**Comment by rogeralsing** [comment]
Welcome to the dark side @TeaDrivenDev 

It should be noted though that pre .NET 4.5, the threadpool was a lot worse than it is now.
There are probably some differences in flowing async state. but other than that, I dont think there is much preventing us to run on 4.0.

**Comment by MrTortoise** [comment]
Just stumbled across this whist considering unity for a graphical front end to some stuff.
Should be noted that support for .net40 is ending from ms
http://blogs.msdn.com/b/dotnet/archive/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1.aspx

**Comment by sherry-ummen** [comment]
So no more focus to this one.. :disappointed:

**Comment by patrickwolf** [comment]
Sorry I don't understand why there wouldn't be focus on this important ticket anymore just because MS stopped supporting NET 4.0? There is still very large community of Unity3d developers (5.5m registered developers to be exact https://unity3d.com/public-relations) who might just love to use Akka.Net and who are still stuck on .NET 3.5.

Making Akka.Net run:
-  on .NET 4.0 seems achievable without too much effort based on @Horusiath original post
-  and on .NET 3.5 would have to be reevaluated since @Horusiath didn't yet check building it with using a back-ported TPL library like:
-- https://www.nuget.org/packages/TaskParallelLibrary/ 
-- or the one @dkoontz  mentioned: http://spicypixel.com/developer/concurrency-kit/

Thanks for considering it!!!

**Comment by sean-gilliam** [comment]
With Unity3D having experimental support for 4.6, is this issue still valid?

**Comment by Aaronontheweb** [comment]
@sean-gilliam nah, not anymore. It'll all target .NET Standard soon enough too.
