### ISSUE TITLE
Event Data Versioning

### ISSUE THREAD

**Issue by Zetanova** [akkadotnet/akka.net#1392]
If an event type is moved to an other assembly or renamed because of versioning,
there is no possibility to replace the payloadTypeString or custom resolve the type
loaded from the Akka.Persistent.Journal.

**Comment by Horusiath** [comment]
From our talk it looks like this kind of behavior could result in infinite error loop inside event adapter. This should be resolved.

Few notes:

- Moving type definition from one assembly to another is basically indistinguishable from changing it's type, so this should never be made once event has been persisted.
- In general using default Akka.NET message serializer for events is a very bad idea. Define custom one whenever it's possible.

My proposition was a dirty trick in form of changing manifest used for message serializer resolution to `System.Byte[]`, so that message won't be deserialized at all, instead a raw binary form will be passed. From this place you could customize a way to recover data, using i.e. custom json.net settings.

Another thing we may try: when we deserialize an event using best effort, once this operation fails, we wrap raw binary in some kind of message like `DeserializationFailed(byte[] payload, Exception reason)` and send it instead. However this would change a way how this behavior works on .NET and JVM.

**Comment by Danthar** [comment]
A few thoughts from my part:

- I agree with the infinite error loop bug. That should be solved.
- I disagree with the byte[] solution

The Akka.Persistent.Journal is an EventSourcing system. Being such a system it should adhere to the tenets defined by such a system. In regards to applying versioning inside an eventsourced system there are plenty of articles available. Just google for 'eventsourcing versioning'.

(I am blissfully unaware of how versioning events works on the JVM but I cant imagine it works any differently)

Every EventSourced system needs to handle message versioning. How this is normally done is by providing some layer that sits between the eventstream and the AR. That may accept messages of TypeV1 and knows how to 'upgrade' them to TypeV2 before its passed on to the AR.

A cursory look into the codebase revealed the IEventAdapter type to enable such a feature. Although it looks like its more a global filter instead of a per message type based thing. If nothing else it can be used as a hook to roll your own 'upgrade' system.

Implementing custom type resolving or overloading type resolving on the appdomain like @Zetanova is suggesting in the chat, is absolutely NOT the way to handle these kind of scenario's imho.

**Comment by Zetanova** [comment]
all Serializer have some kind of feature to override/replace types. In very rude versioning, you tag the type with a int version (attribute or property) and save it in the metadata. If there is some version change of the type, the developer can move the type to an other namesace, assembly or copy+rename the type MyEventV4 and increace the current version of MyEvent to 5 and make the modification on the new version. This splits the versioning in two parts, one that resolves the correct type in the right version and the other part that OPTIONAL converts the old-version to a higher one (or down).
The second part is basicly covert with the IEventAdapter

I dont realy want to rename or move the events to other assemblies.
But a feature to load types from old assemblies with the old types in it
would be very nice.

**Comment by Danthar** [comment]
I now better understand what @Zetanova wants. Im not adverse to it. Having more options in this field is not a bad thing. No idea what it would currently take code-wise to achieve this though.

**Comment by alexvaluyskiy** [comment]
It could be solved by `SerializerWithStringManifest `
