### ISSUE TITLE
Persistent actor receives duplicated events after restart during recovery

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1403]
We have some sign, that actor can receive duplicated events, if it restarts during recovery. What's wrong here, is that we have a request for replay events send to journal from actor incarnation A1. Once journal starts to replay events, actor may crash and get restarted for some reason. New incarnation of the actor (let's call it A2) will again send replay request. In result it may receive some of the replayed messages twice (first time those sent for incarnation A1 before restart, and later the same for A2).

**Comment by patriknw** [comment]
That could be a bug (also in Akka). For the writes we have this instanceId to detect such things, see for example here: https://github.com/akka/akka/blob/release-2.3/akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala#L119

but that is not done for the replay.

Have you migrated to Akka 2.4? There we have less of this trouble in 2.4 because we unconditionally stop the actor when there are any journal failures, but restarts can still happen due to application exceptions.

**Comment by ktoso** [comment]
(a bit more details on how 2.4 deals with this here: https://github.com/akka/akka/issues/18850#issuecomment-153721647 )

**Comment by patriknw** [comment]
right, it's handled in 2.4: https://github.com/akka/akka/blob/master/akka-persistence/src/main/scala/akka/persistence/Eventsourced.scala#L487

**Comment by Danthar** [comment]
Closing this issue: A PR was merged

**Comment by thedevd** [comment]
I am even facing the same problem with akka 2.6.14, should I raise new ticket

**Comment by patriknw** [comment]
good to create new issue, thanks
