### ISSUE TITLE
Add CircuitBreaker support

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#147]
We should to add CircuitBreaker support.

docs: http://doc.akka.io/docs/akka/snapshot/common/circuitbreaker.html

impl: https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/pattern/CircuitBreaker.scala

**Comment by rogeralsing** [comment]
This will not be included in Akka.net, @HCanber might publish a separate package for the circuitbreaker

**Comment by HCanber** [comment]
Oh, I haven't decided yet. :) 
I realised when I started coding it that there is very little dependency on Akka so it would be very easy to create it as a separate package (which would be useful outside Akka as the C# implementations I've seen so far don't handle concurrency that well). 
However there is also a small part that needs to be created to integrate it with Akka, so until decided we should keep this issue opened.

**Comment by MAOliver** [comment]
I translated Akka's circuitbreaker to C# a while back
https://github.com/MAOliver/AkkaCircuitBreaker_InCS (Jun 21, 2013) along with the unit tests and test cases. 

It needs Option and some revisiting of some of the threading pieces (I remember this being a huge pain in the ass -- I was used to futures / promises and async / await was frustrating).

Hopefully, it's useful for someone : ).

**Comment by rogeralsing** [comment]
Anyone? should we bring in @MAOliver's code or do we have some other impl we should use?

**Comment by MAOliver** [comment]
After I finish up some side-work (another week or two), I can devote ~5 hours a week to updating this to the latest version from akka.io and writing up the new tests. Assuming no one has grabbed this one by then.

**Comment by MAOliver** [comment]
Initial integration complete and all tests passing.

Still to complete:

- Proper XMLDocs for all new classes
- Proper Test Descriptions
- Verify awaited tasks that exceed the timeout are handled (thread should die)
- Look at thread execution context for this implementation and verify that there isn't any surprising behavior compared to scala implementation
- Look at the akka.io current version / tests and pull in changes since 2.0.5

**Comment by Horusiath** [comment]
@MAOliver I've seen that you removed atomic counters in your implementation. Any specific reason for this?

**Comment by MAOliver** [comment]
My original implementation used:

```
public abstract class AtomicState : AtomicInteger, IState
{
// base implementation
}
```

I saw that akka.net got rid of AtomicInteger in favor of AtomicCounter and AtomicCounterLong, so I changed my base "AtomicState" to:

```
internal abstract class AtomicState : AtomicCounterLong, IAtomicState
{
// base implementation
}
```

The original scala code is (roughly) analagous to a nested static class extending AtomicInteger with State as a trait (https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/pattern/CircuitBreaker.scala)

```
  private object Closed extends AtomicInteger with State 
{
//
}
```

Because of not having traits and because of how .net handles nested static classes, I'm not sure that I can get away from creating the additional base "AtomicState" class. I need a way to keep track of listeners and update them on state change.

I'm open to suggestions if you got one.

**Comment by MAOliver** [comment]
@Horusiath Ah looking at this again -- it occurs that you were asking why i removed the AtomicCounter.cs and AtomicCounterLong.cs files from Akka.Util. 

They were identical to the ones in Akka.Util.Internal but they were excluded from the project files (but still checked into source). I'm just a habitual cleaner.

I reverted that change since it confuses what I'm actually working on.
