### ISSUE TITLE
Auto-scale servers at runtime with Akka.Net

### ISSUE THREAD

**Issue by TMaster** [akkadotnet/akka.net#1599]
Hi,

I started to work with akka a while ago. I was really impressed by the remote deployment and clustering in the project, and I want to know if you're thinking about the next level.

In my opinion akka.net servers (in a cluster) should "tell" a specific server (not necessarily the Leader, more like a Lighthouse server) about their state (like the number of messages they have processed, the number of times they were restarted, and of course another data the developer wish to provide).

This spacial server has on the one hand this constant steam of data from all the members in the cluster, and on the other hand, it has Rules for scaling up \ down based on that data.

Example for a rule may be: 
1. If the member did not get a message in a 10 minutes, Terminate it.
2. If the member has requested a data from a rest service 10 items in 1 second, add another member to the cluster(because I know the proxy against the Rest service can not handle so many responses in such  a little time.)

I have a few questions:
1. Do you have something like that, thinking of developing this ? (and if so, how can I help?)
2. Do you think it is a contribution that other would like too?
3. Where should I begin? (is there any problems you can think of that make it nearly impossible?)

Thanks

**Comment by Danthar** [comment]
Building an autoscaling system with Akka.Net clustering is definitely possible. There currently isn't something like an auto-scaling module for akka.net. 
Even though I know there are various production users who have build a similar thing, sofar a more generic module for that hasn't surfaced from that yet. And I think that is because its fairly easy to build such a system that is exactly tailored to your specific needs. 

Akka clustering for example has all kinds of hooks/events that allow you to detect the state of your cluster. Combine that with a few custom health monitoring interfaces in your system and you got all the tools you need to build your own decision engine.

A nice example is [Cluster monitor]( https://github.com/cgstevens/Akka.Cluster.Monitor) project.
