### ISSUE TITLE
Unify immutable collections

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1676]
At the present moment we have our own implementation of immutable collections - reason behind that was that Akka.NET predates `System.Collections.Immutable` package. However right now a lot of core plugins uses the latter or even mix of both.

This is an idea to move direct dependency on `System.Collections.Immutable` into Akka.dll, refactor internals to use this library and obsolete `Akka.Util.Internal.Collections`. NBench tests should give us some insights into how this change would affect an overall performance.

@akkadotnet/developers I hope we're on the same page here.

/cc #1175

**Comment by rogeralsing** [comment]
Agree, we should also try to get rid of the custom AVL tree. someone pointed out that the Dictionary in Immutable collections are also AVL trees, so it would be safer to use that IMO.

**Comment by mattnischan** [comment]
This is correct. ImmutableDictionary in System.Collections.Immutable (formerly Microsoft.Bcl.Immutable) is an immutable AVL tree.

Microsoft did release these in late 2013, though, so I think this was just an oversight rather than Akka.Net predating it. There a some good blog posts [here](http://blogs.msdn.com/b/dotnet/archive/2013/09/25/immutable-collections-ready-for-prime-time.aspx) and [here](https://blogs.msdn.microsoft.com/bclteam/2013/03/19/inner-workings-of-immutable-collections-on-channel-9/).

**Comment by praneetloke** [comment]
Hey guys, on that note, System.Collections.Immutable's latest version 1.1.37 seems to add a dependency on .net 5. This is preventing me from being able to add packages like akka.cluster.tools on top of akka.cluster in VS2013. Akka.cluster seems to require system.Collections.immutable >= 1.1.37. It complains that it needs nuget client 3.0 to install akka.cluster.tools, which is not available for 2013 and below. So one would have to upgrade to vs2015 to use those additions.

I can submit another issue for this but this thread seemed related. Please let me know otherwise and I'll open a new issue for a separate discussion about this.

**Comment by mattnischan** [comment]
Yeah, don't use 1.1.37. I don't know what versioning they're smoking, but it sure isn't SemVer. We found the same issue on our production code where we are using System.Collections.Immutable, so we reverted to 1.1.36 as a dependency. That doesn't pull in the .Net nuget deps.

**Comment by Aaronontheweb** [comment]
@praneetloke @mattnischan 

> Yeah, don't use 1.1.37. I don't know what versioning they're smoking, but it sure isn't SemVer. We found the same issue on our production code where we are using System.Collections.Immutable, so we reverted to 1.1.36 as a dependency. That doesn't pull in the .Net nuget deps.

Ugh, that sucks - so should we be doing a revert on the Akka.Cluster dependencies then? We'd need to do the same for Cluster.Tools and Sharding too.

**Comment by mattnischan** [comment]
I'd definitely recommend it.

**Comment by Aaronontheweb** [comment]
cc @Horusiath Bartosz, you onboard with downgrading our version of System.Collections.Immutable? Based on what @mattnischan and @praneetloke have reported it sounds like that would be a good idea.

**Comment by MrTortoise** [comment]
ill pick this up.

**Comment by praneetloke** [comment]
@MrTortoise  Any way that the version downgrade be treated as a separate issue and be tackled sooner? I realize that standardizing on using the immutable collections package is what this thread is about.

**Comment by MrTortoise** [comment]
ill do the nuget downgrade and issue a pull request first - but i have to get everything set up and tests running etc still. Last time i tried things were using packit and it didn't go well!

**Comment by praneetloke** [comment]
@MrTortoise let me try that. I'll report back.

**Comment by Danthar** [comment]
Done by @MrTortoise rebased by @Aaronontheweb . Net result. Issue solved \0/

**Comment by ZoolWay** [comment]
Should this be reconsidered as System.Collections.Immutable 1.3.0 targets .NET 4.5 like 1.1.36 does?
