### ISSUE TITLE
Actors created by TestKit.Sys, using DI, can't make actual child actors.

### ISSUE THREAD

**Issue by matneyx** [akkadotnet/akka.net#1915]
Related gist: https://gist.github.com/matneyx/32d0e674cee307163dfed268f3c03102

As the title says, my actors created by TestKit.Sys don't seem to be creating child actors in a way that they last.

Debugging through the gist, the two actors seem to be created just fine through the PreStart hook (though their PreStart hooks would never hit, if I left them in), but they don't seem to exist in a way that the parent actor can access. 

On line 52, when the parent Asks the child to get results, that always times out, which then causes the parent to return Failure.

Am I missing something?

**Comment by matneyx** [comment]
I'm genuinely not sure what happened, besides casting differently (I wasn't getting a casting error, I was getting Failure), but everything works now.  Closing the issue.

**Comment by Danthar** [comment]
2 things

- Note that we have the `ReceiveAsync` method for handling async stuff. So the line https://gist.github.com/matneyx/32d0e674cee307163dfed268f3c03102#file-akkaditest-L47 is probably better of using that.

- Because your casting the `GetResults` message to an object via the `GetResultsByExternalId` method definition. The `externalIdActor` receives an `object` message. And not `GetResults`. So the actor never processes the message and your ask times out.

**Comment by matneyx** [comment]
Oh, wow, thanks.  I didn't even know about ReceiveAsync. 👍
