### ISSUE TITLE
Drop Protobuf for 1.5?

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#2202]
As discussed in Gitter chat, Protobuf is not yet ported to .NET Core.
One way forward could be to drop Protobuf in favor for Wire even for Remoting/Cluster messages.
We do not aim for JVM interop, at least not on this level, so there is no clear benefit from using Protobuf other than performance.

Wire now support preregistering known types, which actually makes it outperform Protobuf in some cases both on payload and cpu time.

This would ofcourse not work for a hot swap upgrade, but AFAIK, 1.5 will make that impossible anyway, right?

I think this could be a fair approach as we would reduce the number of external dependencies.

**Comment by alexvaluyskiy** [comment]
It is to early to think about it right now. Right now we even couldn't use it with Akka. It's too unstable for me, at the moment. We should test it more.

**Comment by Aaronontheweb** [comment]
I don't like this idea. Just wait for Protobuf to stabilize. Jon Skeet and co are working on it. Or even better: help them out.

**Comment by cconstantin** [comment]
What are we going to do about all the events persisted using protobuf?

**Comment by rogeralsing** [comment]
@cconstantin IMO Akka Persistence should always use Protobuf or some other schema based serializer with true version tolerance.

@Aaronontheweb any specific reasons? I'm fine with using Protobuf, just interested in the arguments for it.

**Comment by Aaronontheweb** [comment]
@rogeralsing it's a proven quantity that works well already inside Remoting, Persistence, Clustering etc. I don't see a need to rush to get something to work on .NET Core, which is going to have its own issues that have yet to be discovered yet since few are running production workloads on it today. Switching out the `object` serializer is pretty trivial compared to doing the same for the built-in serializers used for the control messages and envelopes; if there was an issue with Wire you can easily roll back to JSON.NET (which we plan on shipping as its own package for backwards-compat) for the latter without having to release a patch. Not the case with the remoting serializers.

So in this case the benefits don't come close to surpassing the costs IMHO. I don't see a need for this.

**Comment by alexvaluyskiy** [comment]
Jon Skeet have just released netcore version of protobuf https://www.nuget.org/packages/Google.Protobuf/3.0.0-beta4

But it supports only proto3 format

**Comment by alexvaluyskiy** [comment]
Protobuf was updated in order to support NetCore
