### ISSUE TITLE
Should TypedActor be renamed?

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#221]
`TypedActor` in Akka.NET is not the same as `TypedActor` in Akka.

The Akka.NET version uses an `IHandle<TMessage>` interface for each message it responds to.
That is, it's more like a command handler a'la CQRS.

In Akka. TypedActors are interface AOP proxies.
Its pretty much the same as project Orleans does with code generation.
See http://doc.akka.io/docs/akka/snapshot/java/typed-actors.html

So, should we also support interface proxies?
And in such case, should we rename our current TypedActors to something else?

cc @akkadotnet/developers

**Comment by nvivo** [comment]
Is this still going to change? I noticed the master branch still has TypedActor and no HandlerActor.

**Comment by rogeralsing** [comment]
cc @akkadotnet/developers JVM Akka is making the current TypedActors obsolete, and I've seen a few TypedActor in .NET world in the wild. maybe keep it, no need to change just for the sake of changing.
opinions?

**Comment by nvivo** [comment]
I'm using Typed Actors almost everywhere as they are more convenient than ReceiveActors for simple actors. If JVM akka is not using the name anymore, normally I would agree.

On the other hand, as look for Akka resources, I often read examples in Scala or Java, as there are lots of it. And it is bad for a new guy to find an example of a "typed actor" and it doesn't even mean the same thing.

I think it would be nice if the names wouldn't conflict since Akka.NET won't be able to compete with documentation resources for some quite some time.

This doesn't need to be a breaking change though. The code for TypedActor is tiny, just clone it to HandlerActor and put an `[Obsolete]` on TypedActor until before 1.0. Should keep a better upgrade path at least.

Just my 2 cents.

**Comment by HCanber** [comment]
@rogeralsing Do you know why JVM Akka is obsoleting these? Is it a step towards more functional actors, as they talked about during our conf call with them?

**Comment by rogeralsing** [comment]
TypedActors in JVM Akka are based on POJO AOP proxies., that is, you can write a POJO class with normal methods.
And the typed actor ref then expose a proxy for this actor, marshalling every method call as an actor message which then is received and invokes the correct actor method.

At least one of the arguments I've heard for removing this is that it makes people think RPC/DCOM/Corba when doing so, it makes users stick to the old OOP mindset.

It was also mostly used by Java users and not by Scala users.
Java users make up some 10% of the JVM akka community and if only a fraction of them use typed actors, then it's just a burden to maintain for no real benefit.

They are making the functional actors typed (somehow) so I guess you are right about the main reason.

**Comment by HCanber** [comment]
Although `TypedActor` limit what an actor can do, for simpler actors they might be useful as @nvivo says (although I tend to use `ReceiveActor` everywhere, but I guess I'm biased :). 
To summarize:
- Create new `HandlerActor` (a copy of `TypedActor`)
- Put an `[Obsolete("Use HandlerActor instead")]` on `TypedActor`

**Comment by jpierson** [comment]
BTW, I think there are some overlaps with the concept of [Role Interfaces](http://martinfowler.com/bliki/RoleInterface.html) and the Akka.NET flavored TypedActor which uses granular IHandle\`1 interfaces to specify individual responsibilities aggregated into a sort fo adhoc contract implemented by the individual actor classes. Though that the word **role** may also be fun to consider seeing how puns could be made with other things such as _actors_ and _props_.
