### ISSUE TITLE
WebApi and Persistent Actor not working together

### ISSUE THREAD

**Issue by joshuadeanhall** [akkadotnet/akka.net#2243]
I have the following code in my Global.asax

`    public class WebApiApplication : System.Web.HttpApplication
    {
        protected void Application_Start()
        {
            

            AreaRegistration.RegisterAllAreas();
            GlobalConfiguration.Configure(WebApiConfig.Register);
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);

            BundleConfig.RegisterBundles(BundleTable.Bundles);

           
            var system = ActorSystem.Create("MyServer");

            var persistentActor = system.ActorOf(Props.Create<PersonActor>(), "employeeActor");
            persistentActor.Tell("test");

        }
        
    }`

PersonActor is as follows (In a sepearte project)

`    public class PersonActor : UntypedPersistentActor
    {
        protected override void OnCommand(object message)
        {
            Console.WriteLine("Message recieved " + message);
            Sender.Tell("Test");

        }

        public override string PersistenceId => "PersistentPerson";

        protected override void OnRecover(object message)
        {
            

        }
    }`

The same code works in a console app and if I change to a UntypeActor that will also work in my WebAPI project.  

I can't find anywhere that indicates that this shouldn't work in a web app.

**Comment by Danthar** [comment]
var system = ActorSystem.Create("MyServer");
You should store your `system` ref in a static variable. http://getakka.net/docs/deployment-scenarios/ASP%20NET

What happens now is that your actor system is being disposed probably before the message is ever handled by your actor.

**Comment by joshuadeanhall** [comment]
Danthar thanks for the response I did as you suggested and it still does not work.  But calling a non persistent actor does work (Worked in my previous example also)

Here is my new global.asax

` public class WebApiApplication : System.Web.HttpApplication
    {
        private static ActorSystem MySystem;
        private static IActorRef MyActor;
        private static IActorRef MyNonPersistentActor;
        protected void Application_Start()
        {
            


            AreaRegistration.RegisterAllAreas();
            GlobalConfiguration.Configure(WebApiConfig.Register);
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);

            BundleConfig.RegisterBundles(BundleTable.Bundles);


            MySystem = ActorSystem.Create("MyServer");

            MyActor = MySystem.ActorOf(Props.Create<PersonActor>(), "employeeActor");
            MyActor.Tell("test");

            
            MyNonPersistentActor = MySystem.ActorOf(Props.Create<NonPersistentPersonActor>(), "nonemployeeActor");
            MyNonPersistentActor.Tell("test");

        }
        
    }`


PersonActor remained the same and NonPersistentPersonActor is 

` public class NonPersistentPersonActor : UntypedActor
    {
        protected override void OnReceive(object message)
        {

            Console.WriteLine("Message recieved " + message);

            Sender.Tell("Test");

        }
    }`


I have am debugging with a breakpoint in OnReceive and OnCommand(+OnRecover) and the PersistentActor overrides never get called from ASP.NET application.

**Comment by Danthar** [comment]
A few remarks: Your actor reference does not need to be static, only your actor system.

Meanwhile your issue was addressed in gitter chat. It seems you have configured the local snapshot store for your persistence, which uses the filesystem to store snapshots, and by default stores its files under the `workingdirectory/snapshots`. Which in your case means a directory somewhere under the 'program files' dir, which caused an security exception because your process had no rights to that dir :)
You can use the setting: `akka.persistence.snapshot-store.local.dir = folder` to change the folder where the snapshots are stored.

I think that sums it up nicely. Feel free to add anything you feel is missing. :)

In the future, please direct questions to StackOverflow. You have a much larger audience there that can answer your question. Ofcourse your always welcome to drop your SO question link in gitter chat ;)
