### ISSUE TITLE
Conflict between localhost and 127.0.0.1 in clustering config

### ISSUE THREAD

**Issue by dandago** [akkadotnet/akka.net#2339]
Using a standalone seed node that connects to itself, the following code sample from the [Clustering Overview](http://getakka.net/docs/clustering/cluster-overview) documentation results in errors:

    akka {
        actor.provider = "Akka.Cluster.ClusterActorRefProvider, Akka.Cluster"
        remote {
            helios.tcp {
                port = 8081
                hostname = localhost
            }
        }
        cluster {
            seed-nodes = ["akka.tcp://ClusterSystem@127.0.0.1:8081"]
        }
    }

If the two hostnames (the one in tcp.helios.hostname and the one in the latter part of the seed node address) match, whether they are set to localhost and 127.0.0.1, it works.

It looks like Akka .NET may have an issue determining that localhost and 127.0.0.1 are the same.

**Comment by Aaronontheweb** [comment]
That's a mistake in the docs. Either always use IPs or always use hostnames. Mix the two at your peril.

**Comment by dandago** [comment]
I'll fix the sample in the docs then.

I'm still curious why it's such a problem to mix them though.

**Comment by Aaronontheweb** [comment]
@dandago  because Akka.Remote expects to receive messages at its explicitly bound address - if the message is addressed to something else but Akka.Remote receives it, it discards the message. It's part of the integrity guarantee that Akka.Remote makes about actor uniqueness: if the message was not explicitly addressed to me, it does not belong to me. That's the contract it enforces. Thanks for updating the docs!
