### ISSUE TITLE
Akka.Cluster and TestProbe have issues.

### ISSUE THREAD

**Issue by andrewbuttigieg** [akkadotnet/akka.net#2343]
If you create a router that has a constructor parameter, it will not be populated if you pass it the object created from the CreateTestProbe().

Where SomeActor is 

```
public class SomeActor: ReceiveActor
{
    public SomeActor(object bob)
    {
    }
}
```

This will not create the actor

```
var testProbe = CreateTestProbe();
var props = Props.Create(() => new SomeActor(testProbe).WithRouter(FromConfig.Instance);
var router = system.ActorOf(props, "someActor");
```

This will create the actor

```
var props = Props.Create(() => new SomeActor(123).WithRouter(FromConfig.Instance);
var router = system.ActorOf(props, "someActor");
```

**Comment by Horusiath** [comment]
As you've mentioned on gitter chat, this problem seems to be associated with the fact, you were using clustered routers. In that case, yes you cannot pass `testProbe` as actor constructor, for a simple reason: cluster router will deploy actors on remote nodes, therefore it requires that all actor constructor arguments must be serializable - while `testProbe` is not. If you really need to past it, you should be able to use `testProbe.Ref` instead.

**Comment by andrewbuttigieg** [comment]
Ok, but even when using the "normal" IActorRef and not necessary limited to the TestKit apparently.

**Comment by andrewbuttigieg** [comment]
Take a look at https://github.com/andrewbuttigieg/akka-cluster-router, the project AkkaClusterRouter.Tests has test that is implemented as you said but it fails.

**Comment by Aaronontheweb** [comment]
I believe this has been resolved for many years now.
