### ISSUE TITLE
Akka.Remote/Persistence Delivery bug

### ISSUE THREAD

**Issue by PowerMogli** [akkadotnet/akka.net#2372]
Hi guys,

we have some problems with Akka.Remote/Persistence and we would like to ask you for help or guidance.

We are hosting an actorSystem ('A') inside a ASP.NET MVC 5 website and an actorsystem ('B') inside a windows service.

On the side of A we have an actor of type AtLeastOnceDeliveryReceiveActor which is persisting events to Sql Server and then delivers a message to B. This works fine.

The remote actor on the side of B sends an delivery-acknowledge message with the deliveryId which was generated by the actor on the side of A in the handler when persitence was successfull.

Everything works fine this way. Until we shutdown our website for updates.

Assumed we have no event left inside the journal table and the metadata table contains five entries:

PersistenceId SequenceNr
OrderActor 1
OrderActor 2
OrderActor 3
OrderActor 4
OrderActor 5

When we restart our website and start sending a message from A to B then the deliveryId starts with 1 but in our journal table the SequenceNr is 6. This leads to the problem, that when we try to delete the message
with the method 'DeleteMessages(long toSequenceNr)' with 1 as parameter for toSequenceNr we dont really delete the event and so the event lives forever inside the journal table.

But this is only the first problem.

The next problem is, when our website (A) is shutting down with one or more events stored inside the journal table. After restart our AtLeastOnceDeliveryReceiveActor is trying to recover the stored events
and tries to deliver to the remote actor (B). But at this time deliveryId does not begin with the latest sequenceNr inside of the journal table but with 1. This way we have no chance to delete the event from the journal table
with method call to 'DeleteMessages(long toSequenceNr)' because deliveryId 1..x does not exist inside the journal table. Instead 6..x exist inside the journal table.

Please give us some hints or advice to handle this situation (bug) in a proper way.

**Comment by PowerMogli** [comment]
I created a repository for the akka.client to reproduce the problem:
https://github.com/PowerMogli/akka.client

and here is the repo for the server part:
https://github.com/PowerMogli/akka.server

**Comment by PowerMogli** [comment]
We would expect that the deliveryid inside the deliver method which is invoked inside recover is the deliveryid of the recovered event.
And when deliver is invoked inside command the deliveryid should be the highest sequence number in the metadata table for the requested persistenceid.

**Comment by Horusiath** [comment]
I've already responded on gitter, but for the sake of future generations :)

`DeliveryId` is not the same as `SequenceNr`, just like message send into Deliver method is not the same as event stored inside persistent actor's event stream. 

In usual scenario, when you want to make redelivery attempts durable, usually you may want to persist two events: 

1. Request to delivery a message.
2. Confirmation that message was sucessfully delivered and processed.

In this case each message delivery completes as two consecutive events (request/confirmation). Redelivery attempts are not persisted directly in event journal, but they are stored as part of AtLeastOnceDeliveryActor state that can be snapshotted (see example below).

Other important notes:

- `Deliver` updates actor's delivery state, but it doesn't perform any kind of persistent store. If machine will go down, that means, that not-persisted state will be lost. It's up to programmer to write message persistence. Using Akka.Persistence it's pretty simple (see example below).
- `SequenceNr` is monotonically increasing and it marks current position in persistent actor's event stream. Since Akka.Persistence works using **eventsourcing**, you cannot simply delete single event in the middle of an event stream, as this hole will make actor unable to replay its state. What you can do is to periodically (i.e. every 100 events stored) make a snapshot of an actor's state. Akka.Persistence will pick up recovery procedure from the latests stored snapshot, and then from remaining events older than that snapshot. In this case you can delete older events as they won't be needed anymore (again example below).

Here's an example of generic persistent gateway using at-least-once delivery semantics: https://gist.github.com/Horusiath/64d829720b66df16bc59dbf106a8008e

**Comment by PowerMogli** [comment]
Your example could not solve our initial problem but you directed me to the right solution. :)

**Comment by Caldas** [comment]
Can you explain your solution?

Em 10 de nov de 2016 8:39 AM, "PowerMogli" <notifications@github.com>
escreveu:

**Comment by PowerMogli** [comment]
Honestly we do not really need an event journal. All we need is persistence for sent messages to delete them as soon as they are confirmed. That way we try to avoid duplicate messages send to the recipient, in case of restart of our website as long as the message was not confirmed.

This is the reason why we save a snapshot after every delivery of the message. When saving the snapshot was successful we delete all previous snapshots and hold only the last successfully saved one. And after every confirm of a delivery we create again a new snapshot and delete every previous.

I know this procedure is not really intended by Akka.Persistence but it solves our needs.

**Comment by Danthar** [comment]
@PowerMogli Its not an uncommon pattern actually. If you want to put a name to it, it would be an AtMostOnceDelivery pattern/actor. 
I have implemented one for my own needs as well. They fit well when communicating with external services that don't support idempotency. 

Keep in mind though that out of all the delivery mechanisms (atleastonce, and others) atmostonce has the worst performance characteristics.
