### ISSUE TITLE
Optimize Config.GetNode

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#2404]
As @rogeralsing noticed, there is a non-optimal code on actor creation path - it was probably hard to detect, as it's not directly related to actors. During creation every actor must first check if there is a coresponding entry in HOCON deployment config. Problem is that parsing it every time is pretty expensive. 

If I understand correctly problem lies [here](https://github.com/akkadotnet/akka.net/blob/d86eb6eb4fe512aac603cbc20bddc420acaec74a/src/core/Akka/Configuration/Config.cs#L99). When we want to get a hocon path based on a string, we are are parsing it. It's not a problem itself, but when we won't find anything, we are proceeding with a recursive call to fallback configs - there may be a lot of them, as basically every akka plugin adds its own fallback config to actor system. Thus we are again parsing path string on every call. 

What we could do instead, is to parse config path once at top level call, and use overloaded methods to use parsed path on nested recursive calls to config fallback.

**Comment by rogeralsing** [comment]
I know we saw that the JVM impl do hit the config for each call, but doing any form of string manipulation per actor creation is horribly ineffective.
Creating actors should be cheap, this is both CPU intensive and causes a lot work for the GC.

Currently, Akka.NET is ~10 times slower than Akka in this area, According to the Skynet concurrency benchmark.

I think a lot could be improved here if there was a better story for the HOCON configs.
The design of the HOCON lib stems way way back, before there was any intention of building Akka.NET itself.
Not knowing all the oddities it would face later.
The parser itself is decent, but how the actual result is generated is messy.
It would have been nicer to actually be able to merge configs instead.

**Comment by Rattenkrieg** [comment]
This issue seems perfect to begin with. Will be happy to grab it.

**Comment by Aaronontheweb** [comment]
@Rattenkrieg go for it!

**Comment by Rattenkrieg** [comment]
If I correctly understand @Horusiath point about "the parsing", the toughest part in the call to SplitDottedPathHonouringQuotes is the string splitting and linq on top of it which pressures cpu and gc.
So [I did obvious optimisation ](https://github.com/Rattenkrieg/akka.net/blob/dd8f6d1974582ad6292781b11b571c7d48bd7b2f/src/core/Akka/Configuration/Config.cs#L120) with storing results of "parsing" once in collection, and then calling overloaded method in fallback logic. Exactly as suggested.
As for @rogeralsing thoughts on config merging it seems that we need to construct (parse+merge base config and possible multiple fallbacks) one integral _Config_ instance. So it never hits unhappy path in GetNode unless there is actual entry somewhere in base config or provided fallbacks. I hope I got the point, correct me if not.

**Comment by Horusiath** [comment]
@Rattenkrieg regarding parsing, your code can be simplified to:

```csharp
HoconValue GetNode(string path) => GetNode(path.SplitDottedPathHonouringQuotes().ToArray());

HoconValue GetNode(string[] pathSegments) { ... }
```

No need to duplicate the code and also no need to use generic `ICollection<>` interface. Compiler will make a lot better use of concrete implementation.

Regarding what Roger said, this would be a little more work, as you'd need to implement Merge operation over config tree, that consists of multiple different classes. To be honest, since we only use merge operation when we set a fallback config, I think, we should use immutable structures here. It's simply a less mess.

**Comment by Rattenkrieg** [comment]
I have [rewrited](https://github.com/Rattenkrieg/akka.net/blob/15618f88ca41911547cae3e872d0355a26b7084f/src/core/Akka/Configuration/Config.cs#L449) _WithFallback_ to merge config with provided fallback. I haven't removed _Fallback_ property nor it's population in WithFallback since it's public, however there is no code in solution outside of _Config.cs_ referencing it. So the field is there, it's assignment algorithm wasn't changed but it's no longer used in _GetNode_.
Also there is _Merge_ method defined on _HoconObject_ class, but it is mutating its instance, so I have implemented [MergeImmutable](https://github.com/Rattenkrieg/akka.net/blob/15618f88ca41911547cae3e872d0355a26b7084f/src/core/Akka/Configuration/Hocon/HoconObject.cs#L214) and used it in _WithFallback_.
The problem I figured is that system [emits](https://github.com/Rattenkrieg/akka.net/blob/15618f88ca41911547cae3e872d0355a26b7084f/src/core/Akka/Actor/Internal/ActorSystemImpl.cs#L138) its config during startup if configured so. This call ends on _ToString_ method of _Root_ property of _Config_. _Root_ includes all entries from fallback configs so startup log is a little bit verbose now. Also there is a [test](https://github.com/Rattenkrieg/akka.net/blob/15618f88ca41911547cae3e872d0355a26b7084f/src/core/Akka.Tests/Actor/ActorSystemSpec.cs#L65) I had to correct.

After grokking code I have realized another way to speed up lookups. The idea is to keep all nodes in single dictionary at root entry and reference it by full path:

```csharp
            Items = new Dictionary<string, HoconValue>
            {
                ["akka"] = HoconValue(HoconObject(Dictionary<string, HoconValue>{
                            ["actor"] = //...
                            }))
                ["akka.log-config-on-start"] = HoconValue("on"),
                ["akka.test.calling-thread-dispatcher.type"] = HoconValue("Akka.TestKit.CallingThreadDispatcherConfigurator, Akka.TestKit")
                //....
            }
```
Anyway _HoconObject_ is a dictionary itself and every node lookup ends at N = level of nesting dereferencings and dictionary lookups. So we can trade constant lookup for doubling space.

**Comment by Danthar** [comment]
Closing since the PR was merged. If additional work needs to be done it can be reopened if needed.
