### ISSUE TITLE
[MNTK] Log node Role names instead of index

### ISSUE THREAD

**Issue by Danthar** [akkadotnet/akka.net#2469]
In the MNTK when you start a spec with multiple nodes. The logs log stuff like Node1, Node2, Node3 etc.
This does not help in debugging an MNTK spec. Because it forces you figure out which nodeX is which Role in your Spec.

So an improvement would be to use the names of the Roles which are defined in the Spec itself. That would make the whole thing alot more transparent.

**Comment by Rattenkrieg** [comment]
Well, that one wasn't the easiest.

Finally I've managed to get node role printed everywhere, but I still have some concerns regarding design.
![default](https://cloud.githubusercontent.com/assets/6948307/22408854/63f75a6c-e691-11e6-8bda-5ea44fc41df0.png)





In current implementation node indexes are extracted as follows:

On _Akka.MultiNodeTestRunner_ side Xunit controller walks through assembly and executes _Discovery_ class callback passing metadata regarding test method and its surroundings
Logic in this callback looks for classes that has trailing digits in its names, cuts these digits and treats them as node indexes. These classes should be descendants of `MultiNodeSpec` by convention. Every such class will be instantiated as node in a dedicated process.
https://github.com/akkadotnet/akka.net/blob/v1.1.3/src/core/Akka.MultiNodeTestRunner/Discovery.cs#L65
Then _Akka.NodeTestRunner.exe_ is called for each node with node's index, node's class and test assembly in arguments list.
On _NodeTestRunner_ side node's class is bootstrapped with its own `MultiNodeConfig` instance.
Config provides `RoleName` instances for `MultiNodeSpec` which uses it in `RunOn` calls.

Currently there is no relation between `RoleName`s and node indexes at discovering time.

Thats what I have fixed. Instead of matching classes with trailing digits there is reflection now which builds relation `MultiNodeSpec` <~> `MultiNodeConfig` by looking in `MultiNodeSpec` constructor and extracting `RoleName`s from config
https://github.com/Rattenkrieg/akka.net/blob/mntk-role-names-2469/src/core/Akka.MultiNodeTestRunner/Discovery.cs#L59
Only non-abstract `MultiNodeSpec` descendants are treated as runnable nodes, there will be N instantiations of node in dedicated _Akka.NodeTestRunner_ process where N is number of properties `typeof(RoleName)` in corresponding `MultiNodeConfig` descendant declaration.
_Akka.NodeTestRunner.exe_ is called with additional argument _-Dmultinode.role_
During config initialization there is little change to base constructor to grab current node's role from executable arguments.
https://github.com/Rattenkrieg/akka.net/blob/mntk-role-names-2469/src/core/Akka.Remote.TestKit/MultiNodeSpec.cs#L145

Current discovery algorithm assumes that there will be no more dummy classes representing node indexes so we need sweep every spec. But I can tweak code to not to consider such classes.
Here is example of typical changes to specs:
https://github.com/Rattenkrieg/akka.net/commit/6870caeb8e8c9ffa417e2d66db1d2cd229e07c7a?diff=split#diff-d846d2958ff6883f1578e4fd25f1a556

If design is ok I will continue to sweep specs.
Also please notice my [concerns in comments to commit](https://github.com/Rattenkrieg/akka.net/commit/6870caeb8e8c9ffa417e2d66db1d2cd229e07c7a?diff=unified#diff-d787a40b005dc7af3a9490ff59d7a249R48).

**Comment by Danthar** [comment]
I think the idea is pretty nice. Certainly makes defining specs easier. 

@Aaronontheweb what do you think?

Another thing. Create a PR with WIP in the name. It will make it easier for us to review it.

**Comment by Aaronontheweb** [comment]
Yep, go ahead and create a PR for this. I saw your note about not wanting to have to strictly depend on the Akka.Remote.TestKit.... Maybe we can get creative here.

**Comment by Aaronontheweb** [comment]
Closed by #2502
