### ISSUE TITLE
Update google protocol buffers dependency

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#2485]
As @ismaelhamed noticed, we're currently using [Google.ProtocolBuffers](https://www.nuget.org/packages/Google.ProtocolBuffers/) in all Akka.NET libraries - a package that has been developed by Jon Skeet, is no longer supported - last update was in 2015. It has been replaced with [Google.Protobuf](https://www.nuget.org/packages/Google.Protobuf) that is actively maintained and supported by Google itself.

My idea here is to do 2 things:

1. Replace outdated packages with new one - this also means that all dependent classes will have to be re-generated from scratch. Important thing to note here is that generated classes should remain encapsulated (internal o each assembly, they are generated for) and be placed in custom namespaces (not global). Most of the proto files can be found in [this](https://github.com/akkadotnet/akka.net/tree/dev/src/core/protobuf) directory. Remaining ones, if any, needs to be fetched from akka jvm repository.

2. Maybe we should add Google.Protobuf as dependency directly in Akka core library? It's used anyway by almost any higher level plugin (i.e. both remote, cluster and persistence make use of it). Moreover in Akka.IO we're using custom `ByteString` class, that could be effectively replaced with the implementation taken from google protocol buffers.

/cc @akkadotnet/core

**Comment by Danthar** [comment]
Regarding point 1 and that generated classes should be internal. 
This is not possible atm. Because for example the remoting messages are used in other depending akka projects as well. Unless you want to do something with [assembly:InternalsVisibleTo("OtherProject")]
I think moving them into an explicit namespace is good enough.

Regarding point 2: There are plenty of people that have projects that use just the core akka library, and not the remoting or clustering. Feels silly to have a dependency on protobuff just for the ByteString class.

/my 2 cents.

**Comment by Horusiath** [comment]
@Danthar 

1. Where protobuf remoting messages are used outside of Akka.Remote? AFAIK, they are encapsulated in custom serializers used by remoting itself, which are not exposed anywhere else.
2. Yes, but those people also don't make use of any serializer lib (json.net or wire/hyperion) and quite probably not even System.Collections.Immutable itself. Core akka library could work without those dependencies, yet they are there.

**Comment by Danthar** [comment]
1. In https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Remote/MessageSerializer.cs#L26 A public interface is exposed which contains the SerializedMessage as parameter. This is one of the generated classes. If we make that internal, then we have an accessibility conflict there. There is another method with the same problem. So because of this, they need to be public. Or well, `SerializedMessage` needs to be. It might be an option to redefine the proto files to allow created flexibility in which generated types we do and do not expose.

2. I don't agree that Core akka could work without the System.Collections.Immutable ;) but I get your point. :)

**Comment by Aaronontheweb** [comment]
Adding this to the 1.5 milestone. If we need to make a major fix or change the namespace, that would be the place to do it.

Agree with @Danthar's point about adding Google Protobuffs as a default dependency. Shouldn't need to do that really. 

As for the `ByteString` part, I'm not worried about each library having their own implementation of this. It's natural to want to avoid having dependencies. But if ours has bugs or performance issues we should create some issues for addressing those.

**Comment by jeff-pang** [comment]
I want to try taking a stab at applying the Profobuf3 change to the coreclr branch. Is that ok?

**Comment by alexvaluyskiy** [comment]
It was done for all remote packages. Persistence serialization could be tracked there https://github.com/akkadotnet/akka.net/issues/2743
