### ISSUE TITLE
How to handle "cross-language"  actors ?

### ISSUE THREAD

**Issue by tomaszchacuk** [akkadotnet/akka.net#2510]
Hello,

Are there any rules on types that can be used in messages except beeing serializable?

I have a system where I want to use Akka, but some of the actors (remote) will be written in different languages (C#, GO, Java, C++). How ensure that the message sent eg from C# to Java or C# to GO will be properly handled by the other side?

**Comment by Horusiath** [comment]
@tomaszchacuk Akka actors are not mean to work with other platforms by default. If you want to pass messages between them, you need to use an external library for it and manage keeping death watch over your actors by yourself.

**Comment by tomaszchacuk** [comment]
@Horusiath Thank you for your response. Is this only the matter of the serializer I choose or some other internal issues ? I mean if i choose JSON serializer, does this allow me to remain cross-platform. If no, you mention some external libraries?  Do you have any examples of such libraries ?

**Comment by Horusiath** [comment]
It's more than that. I.e. by default .NET platform use little endian byte order for network communication, while Java (and probably Go) default is a big endian. With the next release of Akka.NET you'll be able to configure that. 

Another matter is communication protocol. In order to keep connection up and make some of the actor features available, actor systems pass some internal messages between each other. Those messages have to be well understood by both sides as well. AFAIK we have a binary compatibility here - both Akka on JVM and .NET use the same Google Protocol Buffers schemas - but nobody have ever checked if that actually work.

**Comment by tomaszchacuk** [comment]
Ehh that is definitely not what I wanted to hear. Akka is the best possible solution for my system - except this issue. OK I will try to check it as protobuf under the hood sounds promising.
When is the new vesrion supposed to be released ?

**Comment by Danthar** [comment]
@tomaszchacuk Even if you manage to get it to work on a basic level. Its still no guarantee that clustering feature's would work in an interoperable fashion. 

You might be able to have some success coupling the JVM Akka to Akka.NET. However if your talking about GO, im assuming you are referring to @rogeralsing protoactor library ? Because I can tell you right now, that that library is not network compatible with Akka. Simply because its implemented very differently. 

If its a key feature of your application to have multiple environments talk with each other. Then model your system accordingly. And yes, using the same Actor model implementation helps alot to reduce the cognitive disconnect between the 2 systems. But I really think that treating it as 2 systems which communicate between each other using a well defined and well known set of messages, is your best path to success.

**Comment by tomaszchacuk** [comment]
Well GO was mentioned here as an example of general concept that actors in different environments (different tech-stacks) would be able to talk to each other, creating some kind "plugin" to the core system. 
No clustering or advanced features are required, as this will be going on within one device with localhost based communication. 

Akka seems as natural solution as it is a mature framework with many implementations accross different stacks.  Now I am feeling that I misuse the general concept fo Akka.

**Comment by rogeralsing** [comment]
I've invested quite a bit of time in this topic.
While it's true as @Horusiath says that there is a bin compatibility at the base Akka.Remote message level.
There is however not compatibility on base Akka.Actor primitives.
e.g. ActorRef, Props, Config et al.
Those primitives are serialized by the default serializer. e.g. JavaSerializer or Hyperion.
JVM Akka is moving away for JavaSerializer https://twitter.com/akkateam/status/830098882403131394 due to security reasons.
(This is probably the right solution for Akka.NET too in the long run as Hyperion contains an entire IL compiler)

This is probably a good first step in order to have cross platform Akka / Akka.NET interop.
If JVM Akka starts recommending e.g. protobuf. it will make any cross platform Akka efforts a lot easier.

**Comment by tomaszchacuk** [comment]
So it seems that for now trying to use Akka in cross-platform env makes no sense... One of the biggest disappointments in my developer career I must say :-(

**Comment by Horusiath** [comment]
@tomaszchacuk Roger didn't mentioned it, so I will ;) Roger is working on other Actor platform implementation called [Proto.Actor](http://proto.actor/) which aims to bring a platform-neutral standard for actor programming. At this point it's available on Go and .NET (number of supported features differs however with advantage in Go), but you may want to get yourself familiar with it.

**Comment by tomaszchacuk** [comment]
@Horusiath Hehe. I read your post just after having a quick look through the examples of Proto.Actor. ;-)  This seems as a potential way to go, but really not beeing able to use Akka is a pain in my neck...

**Comment by Danthar** [comment]
@tomaszchacuk im going to close this. If you feel more discussion is warranted, feel free to reopen.

**Comment by mushroom-cn** [comment]
hi @Danthar
I meet the same problem now. But the comments is before 2017.  
This will never be resolved in akka, right?

**Comment by Danthar** [comment]
I dont think so, since its not a design goal of akka.net in the first place.

**Comment by mushroom-cn** [comment]
@Danthar  
I got it. Thanks for your help.
