### ISSUE TITLE
Fix unit tests on Linux

### ISSUE THREAD

**Issue by alexvaluyskiy** [akkadotnet/akka.net#2659]
Should test on Mono and on NetCore. Probably we should use [dotnet-xunit](https://www.nuget.org/packages/dotnet-xunit/2.3.0-beta2-build3683)

**Comment by heynickc** [comment]
#2666 partially resolves this by upgrading the runner, but there are some skipped tests that need to be fixed.  

.NET 4.5 Akka (Linux tests) had: Tests passed: 3075, ignored: 74.  
.NET Core Akka (v1.3) (Linux tests)currently has:  Tests passed: 1571, ignored: 33

- [ ] Akka.Persistence.Tests ignored per #2665 
- [ ] Akka.Cluster.Tests.ClusterSpec [A_cluster_must_return_completed_LeaveAsync_task_if_member_already_removed()](https://github.com/akkadotnet/akka.net/blob/v1.3/src/core/Akka.Cluster.Tests/ClusterSpec.cs#L189) ignored on .NET Core and .NET 4.5 due to flakiness
- [ ] Akka.Persistence.Testkit [SnapshotStoreSpec.cs](https://github.com/akkadotnet/akka.net/blob/v1.3/src/core/Akka.Persistence.TestKit/Snapshot/SnapshotStoreSpec.cs) ignored for .NET Core, running on .NET 4.5 and Mono.
- [ ] Akka.Persistence.Sqlite.Tests ignored on both Mono and .NET Core, enabled on .NET 4.5
- [ ]  Akka.Streams.Tests, Akka.Remote.TestKit.Tests, Akka.MultiNodeTestRunner.Shared.Tests are ignored for all runtimes currently, listing them here anyway just to take inventory

**Comment by alexvaluyskiy** [comment]
@heynickc All persisted failures on NetCore/Linux related with LocalSnaphotStore. Usually, it tries to load a wrong snapshot.

**Comment by Aaronontheweb** [comment]
Git closed this on merge by accident

**Comment by alexvaluyskiy** [comment]
The rest will be fixed there https://github.com/akkadotnet/akka.net/issues/2828
