### ISSUE TITLE
Are snapshots the correct way to handle operations that should be executed once?

### ISSUE THREAD

**Issue by fleed** [akkadotnet/akka.net#2708]
My actor is kind of avatar for real device.
Some operations should be sent only once to the device because they're not idempotent and unfortunately I cannot change their implementation.

Are snapshots the correct way to handle similar scenarios? Is creating snapshots after those non-idempotent operations a good solution?

**Comment by Aaronontheweb** [comment]
@fleed without knowing the specifics of your situation... Tough to say. I'd go with the journal as a default option since it represents a forward-only log of activity that happened on a per-device basis. The "append-only" journal structure that Akka.Persistence uses is amenable to that even if it's not idempotent.
