### ISSUE TITLE
Calling Context.System.Stop(Self) glitches and loses priority to subsequent Self.Tell

### ISSUE THREAD

**Issue by Jivko1212** [akkadotnet/akka.net#2751]
Here is very simple example code that demonstrates the issue:

    class StopActor : ReceiveActor
    {
        public StopActor()
        {
            Receive<string>(s => {
                if (s == "stop") {
                    Context.System.Stop(Self);
                    Self.Tell("Hello");
                } else {
                    Console.WriteLine(s);
                }
            });
        }
    }

If you send this actor a string with "stop". The output is "Hello". This means that the Stop(Self) loses priority to Self.Tell("Hello"). It should instead shut down, and the "Hello" message should go to dead letters.

I tried similar code with the Java version of Akka and it has the behavior that is expected.

**Comment by Aaronontheweb** [comment]
Yep, if we can reproduce that in a spec then it sounds like a race condition where the system message produced by `Stop` is losing to the `Self.Tell` - worth investigating why that is.

**Comment by Aaronontheweb** [comment]
Could also be an issue with the mailbox processor

**Comment by Aaronontheweb** [comment]
Investigated this and was able to reproduce the behavior, but it's a non-issue. the `Stop` command is issued to the actor's *parent* in the form of a `StopChild` instruction if the actor is a top-level actor. Therefore, if the current actor is processing a mailbox run and it sends itself a new message, that message may very well be processed ahead of the `StopChild` command on the separate parent actor. It's concurrent behavior and it's intended.

**Comment by Jivko1212** [comment]
Hi, this is not documented anywhere. As far as I remember the documentation
promises that delivery order be kept. How can stop be delivered after the
other message then? On top of that it is a high priority message. This is
completely unexpected to me base on the documentation. I know nothing about
StopChild command. Is it some internal API?

**Comment by Aaronontheweb** [comment]
@Jivko1212 so I wrote a spec to test this issue:

```csharp
/// <summary>
    /// Verifies that https://github.com/akkadotnet/akka.net/issues/2751 has been resolved
    /// </summary>
    public class Bug2751Spec : AkkaSpec
    {
        private class StopActor : ReceiveActor
        {
            private readonly IActorRef _testActor;

            public StopActor(IActorRef testActor)
            {
                _testActor = testActor;
                Receive<string>(s => {
                    if (s == "stop")
                    {
                        Context.System.Stop(Self);
                        Self.Tell("Hello");
                    }
                    else
                    {
                       _testActor.Tell(s);
                    }
                });
            }
        }

        [Fact]
        public void ShouldReceiveSysMsgBeforeUserMsg()
        {
            var stopper = Sys.ActorOf(Props.Create(() => new StopActor(TestActor)));
            stopper.Tell("stop");
            ExpectNoMsg();
        }
    }
```

Sure enough, it fails... But I after doing a review of the code here and the `Stop` method, here's what I realized: the actor code you presented stops the actor incorrectly.

You need to change this line:

```Context.System.Stop(Self)```

To this:

```
Context.Stop(Self)
```

This allows the actor to take advantage of its local context and immediately stop itself; it's stopping from the inside instead of the outside. The spec passes every time once I do that, and I'll add it to the `v1.3` branch to verify.

**Comment by Jivko1212** [comment]
I had no idea about this. Thanks.

**Comment by Aaronontheweb** [comment]
@Jivko1212 not your fault, and I'm glad you pressed me on it - otherwise the information I would have given you was incomplete. Hope this helps!

**Comment by optiks** [comment]
Surely that's a badly designed/incorrect interface. I would expect both usages to exhibit the same behaviour?

**Comment by Aaronontheweb** [comment]
@optiks since I never replied to this - no, this is correct. If we're visualizing concurrent access to a queue, I can't force Thread A to jump the line ahead of Thread B when processing the mailbox down to the nanosecond / microsecond level 100% of the time because thread B might already be beginning processing of the most recently passed user-land message, which is how a race condition like this can happen. The tools we have to work with are only so precise. 

That's what happens when you call `Context.System.Stop(Self)` - you're trying to stop the actor _from the outside_. When you call `Context.Stop(Self)`, you're trying to stop the actor _from the inside_ - i.e. the `Stop` invocation is being queued up by the very same thread that is going to read that instruction on the next pass over the mailbox, therefore we can guarantee reliable ordering.
