### ISSUE TITLE
[Documentation] Remoting: clarify disassociation, reassociation and actor lifecycle

### ISSUE THREAD

**Issue by 0x53A** [akkadotnet/akka.net#2838]
It would be great to extend the documentation at http://getakka.net/docs/Remoting on how the system behaves with regard to disassociation / reassociation and IActorRefs.

Quick test:

1) Connect two systems on two different computers and get a remote IActorRef through an ActorSelection.
1) Send a few messages between them, everything works.
1) Cut the network connection and wait a few seconds for the red/yellow error texts.
1) Reconnect the network cable.
1) Send a message to the previously obtained IActorRef -> everything works!

So it looks like the system auto-heals:
* After disassociation, messages are sent to deadletters.
* After reassociation, existing IActorRefs are still valid, and everything can resume.
* Awesome!

I also have two questions (but these may be more suited to stackoverflow):
* Is there a way to query whether a remote IActorRef is disassociated? I know you can ``Watch`` an actor, and will get a ``Terminated`` on death / disassociation, but I would like to just check if it is known-disassociated now, and don't care about the future.
* Is there an equivalent event to ``Terminated`` for re-association?

**Comment by Aaronontheweb** [comment]
To help close out this issue - we need to add some documentation around this, but it is possible to track changes in association / disassociation while just using Akka.Remote:

```
Context.System.EventStream.Subscribe(Self, typeof(AssociatedEvent));
Context.System.EventStream.Subscribe(Self, typeof(DisassociatedEvent));
```

We use this inside [Petabridge.Cmd.Remote `pbm remote tail` for tailing live remoting events](https://cmd.petabridge.com/articles/commands/remote-commands.html#remote-tail)

>Is there a way to query whether a remote IActorRef is disassociated? I know you can Watch an actor, and will get a Terminated on death / disassociation, but I would like to just check if it is known-disassociated now, and don't care about the future.

`Context.Watch`-ing an `IActorRef` on a disassociated connection right now will result in an immediate `Terminated` message.

It's probably best to use Akka.Cluster for this sort of thing though, since you can query the global connectivity state via `Cluster.State` and see all of the unreachable members at any point in time.
