### ISSUE TITLE
Akka.Remote Disassociation error when CPU is at about 100%

### ISSUE THREAD

**Issue by contactsamie** [akkadotnet/akka.net#2859]
We have two nodes, A and B. A is azure webapp , and B is a console app hosted in windows service . Akka.Remote works fine between them.However,  when A is at 100% cpu and B is not , using Akka.remote, A can send (Ask) message to B and B successfully processes the message and .Tell back a response .  but A its unable to receive this response message sent back from B. The Ask times out.  After this , we get the Disassociation error on B and A is gated on B. We only recover by restarting A.
Is this an expected behavior or something is wrong?

**Comment by Aaronontheweb** [comment]
@contactsamie if the CPU reaches 100% utilization, the Akka.Remote transport will start lagging behind and may eventually miss its heartbeat check. Nothing we can do about that really - the CPU is too busy on one machine, and the less busy machine takes notice and disassociates.

**Comment by 0x53A** [comment]
I also hit this when stress-testing our application.

Under normal usage, our app is not expected to be CPU limited, so this is not critical, but I was wondering if there was a way to increase the priority of the critical work.

From what I gathered, it is really two parts (at the least), that will fail under high utilization:

I got disassociations, which are probably due to the missed heartbeat, and the log contained a lot of these errors, which come from the transport level:

```
[ERROR][21.07.2017 08:40:19][Thread 0016][Akka.Remote.Transport.DotNetty.TcpServerHandler] Error caught channel [[::ffff:192.168.175.71]:52719->[::ffff:192.168.175.71]:58011](Id=58a8b386)
Cause: System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at DotNetty.Transport.Channels.Sockets.SocketChannelAsyncOperation.Validate()
   at DotNetty.Transport.Channels.Sockets.AbstractSocketByteChannel.SocketByteChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)
```

Even though it disassociated a few times, it always auto-healed after a short period and I never got into the quarantine state, which is great.


Afaik DotNetty uses dedicated worker threads, so the second issue may be be alleviated by boosting their priority.

The heartbeat is sent from actors on the ThreadPool, so that is a bit harder.
It may be possible to use a fixed-thread scheduler (instead of executing it in the thread-pool) and boosting that thread's priority? I'm not sure if the other parts of the actor pipeline would still continue to work as expected.

I realize that this is not even an issue for you, and so not really _any_ priority, but __do you think this could work?__

and

__would you consider accepting PRs regarding this?__

**Comment by contactsamie** [comment]
Thanks @Aaronontheweb . @0x53A  I noticed we recover as well when ever its a single cpu spike . However when the spike is sustained, we hit the quarantine state., we also have back pressure so more messages to pump through upon recovery etc. we usually just do a quick restart in all cases anyways. right now our strategy is to keep cpu away from spiking, so in a way it helped us think deeper about and improve our app performance . Wandering to what extent will this configuration affect things

```
 transport-failure-detector {{
                            heartbeat-interval = 60 s # default 4s
                            acceptable-heartbeat-pause = 20 s # default 10s
                        }}
```
