### ISSUE TITLE
Clustered actor not receiving messages from custom router

### ISSUE THREAD

**Issue by mtmk** [akkadotnet/akka.net#2872]
When using a clustered actor, it doesn't seem to be activated through its parent.

**Minimal solution to reproduce:**
https://github.com/mtmk/akkadotnetexamples

**Instructions:**
* Run src120 solution and see the message is passed to ActorOne and ActorTwo as you press enter on the console.
* Run src123 solution and see that ActorTwo is not even instantiated.

**PS** We are thinking, it's simple as missing a configuration entry which was defaulting to a correct value before (suspecting 'seed-nodes')

**Comment by Aaronontheweb** [comment]
Taking a look at it now...

**Comment by Aaronontheweb** [comment]
@mtmk so this code was affected by a bugfix we implemented as part of Akka.NET v1.2.2: https://github.com/akkadotnet/akka.net/issues/2783

We were ignoring the `use-role` setting on clustered routers before... So with this configuration:

```
akka.actor {
                  provider = ""Akka.Cluster.ClusterActorRefProvider, Akka.Cluster""
                  deployment {
                    /ActorOne/ActorTwo {
                        router = consistent-hashing-pool
                        nr-of-instances = 1
                        cluster {
                          enabled = on
                          allow-local-routees = on
                          use-role = role-one
                          max-nr-of-instances-per-node = 1
                        }
                    }
                  }
                }
```

that would have triggered a deployment on 1.2.0-1.2.1... even though you're not specifying a role for this node here. Technically, your router configuration was invalid and should not have worked. But it did, due to this bug.

In 1.2.2 since we fixed the bug, this would stop deploying. To resolve the issue, you'd need to add this line to the bottom of the configuration:

```
akka.cluster.roles = [role-one]
```
That will resolve the issue.

**Comment by mtmk** [comment]
Yep, that was it. Working now. Super quick response! Thank you @Aaronontheweb
