### ISSUE TITLE
PersistenceSnapshotSerializer can't be used in all persistence plugins implementations

### ISSUE THREAD

**Issue by alexvaluyskiy** [akkadotnet/akka.net#3068]
The current `PersistenceSnapshotSerializer ` could serialize the only payload, without any metadata. And I can't use this serializer for example with Redis implementation because I have to create an envelope and serializer for it.

Since Protobuf serializer can't serialize actually payload and tries to find another serializer. It makes the current `PersistenceSnapshotSerializer` useless

**Comment by joshgarnett** [comment]
Hey @alexvaluyskiy I'm not sure if I follow your concerns here.  This implementation actually fixed an issue when using the local snapshot store as it would alway serialize the Snapshot with the json serializer even if the actual object within the Snapshot was a protobuf, which caused problems with deserialization.

This really is just a helper class for plugins that want an easy way to serialize the snapshot object to the database as it does the heavy lifting of ensuring the manifest and serializer_id is setup properly.  Plugins do not need to use the Serialization.Snapshot object if they do not want to.

See https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Persistence/Snapshot/LocalSnapshotStore.cs#L206  

If it would be useful we could create a protobuf serializer for SelectedSnapshot, but in the case of something like the Redis plugin you manage, that would cause backwards compatibility issues, since the current implementation uses json.

**Comment by alexvaluyskiy** [comment]
We can't just create a maintain a separate serializer for `LocaSnapshotStore`, but it was created not for production. Only for tests. The current serializer could not be used in any else plugins (only for Sql plugins), because the most of them should store a metadata too.

Something like that
```proto
import 'ContainerFormats.proto';

message SnapshotMessage {
  string persistenceId = 1;
  int64 sequenceNr = 2;
  google.protobuf.Duration timeStamp = 3;
  PersistentPayload payload = 4;
}
```

I've never said that Redis plugin is production ready and has a final scheme. The scheme will definitely change in the next version.

**Comment by joshgarnett** [comment]
Sure, I get that argument, but this serializer for this type exists in the JVM Akka implementation and I can see non key/value stores getting value out of it.
