### ISSUE TITLE
Q: Has anything changed regarding ActorSelection ?

### ISSUE THREAD

**Issue by jalchr** [akkadotnet/akka.net#3097]
Is there a way to validate that I got a "valid" actor after calling this:
```
var remoteActor = Startup.ClusterSystem.ActorSelection("akka.tcp://MySystem@127.0.0.1:6667/user/api");
remoteActor.Tell(new Message());

```
This is failing somehow after upgrading to v1.3.1. 
The other end never gets the message.

**Comment by Horusiath** [comment]
I've run into very similar issue even before v1.3.1. In my case I was using `await actorRef.Ask<>` somewhere up in the message pipeline, which resulted in sending message to another node via ActorSelection - to be exact in ReadAggregator code of DData module. However ask was never completed. 

After investigation it looked like `ActorSelection` is sending the message correctly, but it looked like it was never received. After even deeper investigation (down to debugging actor mailbox) it turned out that message send via `ActorSelection` was send successfully, received and parsed on `EndpointReader` side ok and correctly directed to an actor's mailbox, BUT it was never picked up from there by a message dispatcher.

This is as far as I've managed to track this issue - In my case I've managed to solve the problem by wrapping `await actorRef.Ask` with `Task.Run` and processing the result in another thread. It's strange I know, but somehow it worked.

**Comment by Aaronontheweb** [comment]
@jalchr is this on .NET Core or on .NET 4.*?

**Comment by 0x53A** [comment]
Since you mentioned that a part of the issue was the awaiting of the Ask, could this be related to https://github.com/akkadotnet/akka.net/issues/2546?

Wrapping it with Task.Run would change the SynchronizationContext and change where the continuations are executed in.

**Comment by Aaronontheweb** [comment]
@0x53A yeah... that could do it... in terms of why this behavior would be different in 1.3.1 though, think it could have something to do with the .NET Standard / .NET Core runtime changes?

**Comment by jalchr** [comment]
@Aaronontheweb That happened on .NET 4.x

**Comment by marcpiechura** [comment]
@jalchr is this still an issue ?

**Comment by jalchr** [comment]
@marcpiechura I don't know if it was fixed ...
To me this issue is closed ... thanks
