### ISSUE TITLE
serializable attribute  NetCorePolyfills problems when used in a dotnetcore / netstandard 2.0 project

### ISSUE THREAD

**Issue by AGiorgetti** [akkadotnet/akka.net#3161]
Akka 1.3.1
platform: netstandard 2.0 / dotnetcore 2.0

Since the same attribute is now part of the core framework defining it again cause compilation problems:
 
The type 'SerializableAttribute' exists in both 'Akka, Version=1.3.1.0, Culture=neutral, PublicKeyToken=null' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'	

Workaround:
One workaround is to set an 'alias' for the reference and use 'extern alias ***' on all your code files.
This is tricky with packages referenced with NuGet (see https://github.com/NuGet/Home/issues/4989 for a workaround on this).

**Comment by Aaronontheweb** [comment]
@AGiorgetti .... soooo the issues is that `SerializableAttribute` means two different things on each runtime?

**Comment by AGiorgetti** [comment]
Not on each runtime, it's a 'duplicate' definition of the same class in the same namespace, but in two different strongly typed assemblies.
Ofc the two attribute might have the same semantic meaning, but they are in fact two distinct entities.

More info can be found on this msdn article:
https://blogs.msdn.microsoft.com/ansonh/2006/09/27/extern-alias-walkthrough/

**Comment by annymsMthd** [comment]
The type 'SerializableAttribute' exists in both 'Akka, Version=1.3.2.0, Culture=neutral, PublicKeyToken=null' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

**Comment by OnurGumus** [comment]
Any updates for this issue? Seems trival to fix. Why not just remove it from akka.net since as of now .net core 1.x is obsolete?

**Comment by Horusiath** [comment]
@OnurGumus there are still people sitting on 1.x ;) Also officially akka.net still supports .NET Standard from 1.6+. However I guess this will change soon. 

Microsoft may decide to remove support for their products few months after releasing it, but we're trying to behave as responsible people.

**Comment by OnurGumus** [comment]
@Horusiath It is true that there are people sitting on 1.x. But I never said drop support for  .net core 1.x.

Instead drop support of serializable for 1.x. Because now  people who use 2.x cannot use serializable. This is a much worse situation. It is much better to remove it immediately and tell people Serializable is no longer supported for upcoming 1.x releases.

**Comment by Lutando** [comment]
I am also coming into this issue

**Comment by Zetanova** [comment]
I am currently updating from net4.5 vs2013 to netstandard 2.0,
got this issue with akka 1.3.6

How it can be resolved now?

**Comment by Danthar** [comment]
We will be removing these polyfills in the next release.

**Comment by AustinAndersonTxm** [comment]
the same issue comes up when defining your own serializable exceptions

**Comment by Aaronontheweb** [comment]
@AustinAndersonTxm to comment on this real fast, since there were multiple issues opened for the same bug. This has been fixed in the current `dev` branch and the fix is available either as a [nightly Akka.NET build](https://getakka.net/community/getting-access-to-nightly-builds.html) or via one of the Akka.NET v1.4.0 betas on NuGet.org. As of right now, Akka.NET v1.4.0-beta1 is available with this fix and we'll be doing betas every 2-3 weeks until 1.4.0 RTMs.
