### ISSUE TITLE
TestKit.IgnoreMessages doesn't work on messages already received by TestActor

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#3172]
Version: Akka.NET 1.2.3

Calling `IgnoreMessages(Predicate<object>)` doesn't work on messages that have already been received by the `TestActor`, thus this behaves somewhat racily at the moment. Should it matter if the `TestActor` has received these messages or not already?

**Comment by Danthar** [comment]
Yes it matters. Because else you can potentially run into problems when using multiple occasions of IgnoreMessages in the same test. (most noticeable in the MNTK)

The way I use it, is by first setting up `IgnoreMessages`, and only then performing the action that would generate said messages. Therefore making sure my ignore is in place before I start generating messages.

And considering the async nature of Akka (even though the TestKit does some dispatcher magic) its exactly how i would expect `IgnoreMessages` to behave. 
But i might be biased :P

**Comment by Aaronontheweb** [comment]
@Danthar my use case:

have a scenario where I can receive multiple notifications of the same type depending on some external factors that are not important. I want to receive the first of these notifications and then ignore the subsequent ones while I fish for a second type of notification later.

If I use `IgnoreMessages`, I can't guarantee that the `TestActor` hasn't already received another copy of the first type of notification before I begin ignoring further messages.

I can use `FishForMessage` instead I suppose. I ended up doing something a little different to work around this issue. I suppose that's the right tool for the job here, instead of `IgnoreMessages` ?

**Comment by Danthar** [comment]
Ah yes. `IgnoreMessages` does not dequeue messages, it acts like a filter, and prevents messages from being queued in the TestActor in the first place.
So yes `FishForMessage` sounds like a better fit here. Because it actually dequeues messages until if hits the predicate. Ideal for your scenario.

`IgnoreMessages` Only works well in scenario's where you can set it up, upfront.

**Comment by Aaronontheweb** [comment]
Ok then, working as intended.
