### ISSUE TITLE
Akka Typed implementation as in original Akka

### ISSUE THREAD

**Issue by delfuria** [akkadotnet/akka.net#3185]
Hi,
since TypedActor will become obsolete from 1.5 version have you some plan for replace it with AkkaTyped-like as in "original" Akka ?
https://akka.io/blog/2017/05/05/typed-intro
Thanks

**Comment by Danthar** [comment]
TypedActor will become obsolete because we feel that the same can be achieved with UntypedActor in combination with the new pattern matching syntax of c#. 

AkkaTyped is not something that is on our roadmap at the moment. However there are user provided alternatives available: https://github.com/SaladLab/Akka.Interfaced
