### ISSUE TITLE
Node cannot join the cluster after restart

### ISSUE THREAD

**Issue by vasily-kirichenko** [akkadotnet/akka.net#3239]
It's bound to port 0, so after restart it's given a different port and it logs the following error endlessly
```
[WARNING][31-Dec-17 17:03:51][Thread 0012][remoting] Tried to associate with unreachable remote address [akka.tcp://TestSystem@localhost:61604]. Address is now gated for 5000 ms, all messages
 to this address will be delivered to dead letters. Reason: [Association failed with akka.tcp://TestSystem@localhost:61604] Caused by: [System.AggregateException: One or more errors occurred.
 ---> Akka.Remote.Transport.InvalidAssociationException: No connection could be made because the target machine actively refused it tcp://TestSystem@localhost:61604
   at Akka.Remote.Transport.DotNetty.TcpTransport.<AssociateInternal>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
That is the best practice to deal with it?

**Comment by vasily-kirichenko** [comment]
If the node is given a static port in the config, everything is OK. So, this is what I should always do?

**Comment by Horusiath** [comment]
From the cluster perspective, a node which connect on a different port than before, is a new node. If it was marked as unreachable, it's expected either to be reachable again (so connect under the same address) or be downed. 

By default node must be downed manually. It can also be configured on several ways:

1. The simplest case is setting up `akka.cluster.auto-down-unreachable-after = 10s` or other timeout - this way if node was unreachable for longer than provided timeout, it will be downed automatically. This however introduces risk of split brain: *if a network partition happened, and nodes on both sides are unreachable for longer, they may down themselves. Since they cannot communicate that to each other, you'll end up having two clusters, unaware of each other* .
2. From the next version (probably 1.3.3), a [split brain resolvers](http://getakka.net/articles/clustering/split-brain-resolver.html) will be available - they introduce 4 different strategies to deal with machine crashes, network partitions and risk of split brain.
3. You can also use [Akka.Cluster.Discovery.Consul](https://github.com/Horusiath/Akka.Cluster.Discovery) with `akka.cluster.discovery.consul.alive-timeout = 1m`. This will instruct nodes to treat consul service registry as arbitrary source of cluster membership state. Every node not registered in consul will be downed.
4. You can also write your own implementation of `IDowningProvider` and use HOCON config to use it.

**Comment by vasily-kirichenko** [comment]
wow. thanks! I think I need to try Consul.

**Comment by Horusiath** [comment]
Just keep in mind that with consul, a time necessary to determine if node is dead, is pretty significant - accordingly to the consul docs it should be at least 1 minute.
