### ISSUE TITLE
can deserialize with another object

### ISSUE THREAD

**Issue by shihangwei** [akkadotnet/akka.net#3353]
just have an issue,can i 'Serialize' with objectA,then 'Deserialize' with objectB ?
objectA and B have the same struct...

like:

```
    public class Object1
    {
        public string MyProperty { get; set; }
    }
    public class Object2
    {
        public string MyProperty { get; set; }
    }
   
```
```
   byte[] b = SerialzeTest.SerializeByHyperion<Object1>(new Object1() );
   Object2 de = SerialzeTest.DeserializeByHyperion<Object2>(b);
```

   now,it cannot work ,error message is : 
       System.InvalidCaseException:Unable to cast object of type '...Object1' to type '...Object2'.

   is there any way to solve this problem? thanks very much ^^

- i am using Version 0.9.8.0 and in .net framework 4.6.1

**Comment by Horusiath** [comment]
In theory this is possible. 

By default when unknown, a type itself is encoded as part of the message payload - this must work this way in order for serializer to be polymorphic (as you recall, actors receive plain `object` messages, which are already deserialized to their correct type without knowing what type receiver expected).

However Hyperion can work over so called known types. When a known type is specified to serializer, it uses a type identifier instead of type name. This means that `Object1` can be deserialized as `Object2` as long as their memory layout stays the same.

To configure that programmatically, you need to specify known types for Hyperion, for serializer itself:

```csharp
var serializer = new Serializer(new SerializerOptions(
    versionTolerance: true, 
    preserveObjectReferences: true, 
    knownTypes: new[]
    {
        typeof(Object1) // typeof(Object2) on second machine
    }));
```
In case of Akka.NET, you need to define known types provider

```csharp
public class MyKnownTypesProvider : IKnownTypesProvider
{
    // again use `Object2` on another machine
    public IEnumerable<Type> GetKnownTypes() => new[] { typeof(Object1) };
}
```

and set it in HOCON:

```hocon
﻿akka.actor {
  serializers {
    hyperion = "Akka.Serialization.HyperionSerializer, Akka.Serialization.Hyperion"
  }
  serialization-settings {
    known-types-provider = "MyNamespace.MyKnownTypesProvider, MyAssembly"
  }
}
```

#### What to keep in mind:

1. The ID assigned to each of the known types is based on the order in which they were provided. So if you'll provide more than one known type, keep `Object1` and `Object2` in the same position inside known types array. 
2. Also as known types are identified by ID rather than type name, all known types defined on one side of the serializer, must have their known types equivalents on deserializer side.
2. This is probably not a final shape of this feature. It more or less likely will change in the future.

**Comment by shihangwei** [comment]
i am sorry,foget the code..
`    public class SerialzeTest
    {
        public static byte[] SerializeByHyperion<T>(T obj)
        {
            var hser = new Serializer(new SerializerOptions(false));
            var hstream = new MemoryStream();
            hser.Serialize(obj, hstream);
            byte[] buff = hstream.ToArray();
            hstream.Close();
            hstream.Dispose();
            return buff;
        }

        public static T DeserializeByHyperion<T>(byte[] buff)
        {
            var hdeser = new Serializer(new SerializerOptions(false));
            var hstream = new MemoryStream(buff);
            T obj = hdeser.Deserialize<T>(hstream);
            hstream.Close();
            hstream.Dispose();
            return obj;
        }
    }`

**What to keep in mind** GOT IT. thank you ^^

**Comment by shihangwei** [comment]
i am sorry,foget the code..

```
    public class SerialzeTest
    {
        public static byte[] SerializeByHyperion<T>(T obj)
        {
            var hser = new Serializer(new SerializerOptions(false));
            var hstream = new MemoryStream();
            hser.Serialize(obj, hstream);
            byte[] buff = hstream.ToArray();
            hstream.Close();
            hstream.Dispose();
            return buff;
        }

        public static T DeserializeByHyperion<T>(byte[] buff)
        {
            var hdeser = new Serializer(new SerializerOptions(false));
            var hstream = new MemoryStream(buff);
            T obj = hdeser.Deserialize<T>(hstream);
            hstream.Close();
            hstream.Dispose();
            return obj;
        }
    }
```

What to keep in mind GOT IT. thank you ^^

**Comment by nathvi** [comment]
If you got the issue, please the issue :) 

@shihangwei

**Comment by shihangwei** [comment]
oh, i am sorry. forgot to close it.  :(
