### ISSUE TITLE
Cluster: "some nodes are more equals than others"

### ISSUE THREAD

**Issue by JTrotta** [akkadotnet/akka.net#3383]
- Which Akka.Net version you are using: **1.3.5**
- On which platform you are using Akka.Net: **Mono**
- A list of steps to reproduce the issue. Or an gist or github repo which can be easily used to reproduce your case.

I'm using akka to create microservice ESB, the cluster has minimum 3 nodes (centos VM). I need to distribute among nodes some messages using akka Distributed Publish Subscribe. Everything works, but my solution implies that all "nodes must be equal": when a new node is added to the cluster, it's  just to ensure HA, distribute load (i.e. too much traffic, clients etc.). The node is just like the others. But AKKA cluster needs seeds nodes, and when a seed node goes down, no new node could be added to the cluster. This implies that "all nodes are equal, but some nodes are more equals than others" (G. Horwell). 
My question is: how a real nodes democracy could be reached?
JJ

**Comment by Horusiath** [comment]
@JTrotta in order to join the cluster, node must know the address of any other node, that is already part of the cluster. The seed nodes list serves only as initial contact point. If all of seed nodes will go down, cluster will still operate and you still can join to it if you know the addresses of other nodes in the cluster. A lot of distributed solutions works this way.

If configurable list of seed nodes is not in your taste, you can also use [Akka.Cluster.Discovery.Consul](https://github.com/Horusiath/Akka.Cluster.Discovery) - it leverages a consul service discovery mechanism to use it as a contact point.

**Comment by JTrotta** [comment]
Hello @Horusiath  thank you for your answer. 
I agree with your point of view, but I prefer to not have any "external" dependence. In my node solution, each node can probe other nodes (using an internal protocol, not the AKKA one). Is it possible, when a node come alive, to probe the AKKA cluster programmatically, getting information from AKKASystem/AKKAActor on which is/are the seeds to contact? 
I mean, when I switch on a node (let's call X node), the node goes UP, and start probing other nodes, trying to get from other nodes something like "Hey, I'm an AKKA seed node". At that point  AKKA cluster of the X node can connect to the cluster using on of the discovered seeds node. **Without knowing at design time or by configuration whose are the seeds ore the leader**. Jut discovering them.
I'm checking: [here ](http://getakka.net/articles/clustering/cluster-extension.html), with no success.
Thak you
JJ

**Comment by Horusiath** [comment]
I think, you're missing the crucial thing here: if you have to actor systems that you want to join into a single cluster, at least one of them needs to know the address of the another one. It's just like in real life: you cannot send a email to a person without knowing their address. 

For that to happen you need to obtain an address from somewhere. It doesn't matter if it's configuration file, 3rd party service or shared database - you need an initial contact point.

> I mean, when I switch on a node (let's call it X node), the node goes UP

In akka terminology, UP means, that node has joined the cluster, and acknowledged by every other node in the cluster as its member. This assumes that you've already established the contact to other nodes, so you've already got their addresses.

> and start probing other nodes, 

In order to probe other nodes it need to know their addresses. If you've already have them running in your cluster, it's simple (either the events/methods from the link, you've found in the docs or `Cluster.Get(Context.System).State.Members`). If node is not yet part of the cluster, how does it know where to find nodes to probe?

> trying to get from other nodes something like "Hey, I'm an AKKA seed node".

There's no such thing as *I'm seed node* - it's a term used only in initial configuration list. Any node can work as seed node for others as long as it's part of the cluster.

**Comment by JTrotta** [comment]
I see.
When I wrote:

> the node goes UP

I meant my node system, my service/application, not AKKA system itself. So we are talking about the same thing.
But I think you gave me the solution here:
 
> In order to probe other nodes it need to know their addresses. If you've already have them running in your cluster, it's simple (either the events/methods from the link, you've found in the docs or Cluster.Get(Context.System).State.Members). If node is not yet part of the cluster, how does it know where to find nodes to probe?

My udp probing can gets other nodes IP (not AKKA but simple server IP), and than getting information from my udp probe answer (I guess an ACTORSystem knows it's a leader/seeds or not? Or whatever nodes replay to my beacon probe, as you say that any nodes in the cluster can be a seed), then connect AKKASystem to the cluster using that IP, isn't it?

I'm gonna try. Will let you know
Thank you
JJ

**Comment by JTrotta** [comment]
Hello, using cluster.Join or cluster.JoinSeeds programmatically, everything works as expected.
Thank you.
