### ISSUE TITLE
[Question] How to choose correct source for grabbing data from external providers.

### ISSUE THREAD

**Issue by sdanyliv** [akkadotnet/akka.net#3463]
At first i’m really expressed with your library and i have plans to use it widely in our system, especially streaming. But something hides from me when i’m digging documentation and samples. And possibly you will show me the best way how to do that with Akka.Net.

1. Push model: We have websocket connection to some source which pushes data. So we receive messages when source deceides to send data.

2.  Pull model: we grab data from external provider via REST API

How to define effective Source for such kind of scenarios?
Backpressure is on the first place. We have to be sure that our server will not die when it receives too many messages.

Then streams from different providers should be united and then separated into two parallel streams: one for recording into database, second for processing by other functionality. 

TIA

**Comment by Danthar** [comment]
Well i guess it boils down to, build a Source for your specific sources ?

Supporting backpressure on a websocket connection will be tricky, because if its a true push model, and there is no way to send a signal back (in traditional connection types, you can simply block or not-ack the message). So it might not be possible to achieve backpressure in that scenario. But im not an expert on websockets so someone else might have some ideas.

The pull model on the other hand is simple, since your fully in control of when you are going to get data, achieving backpressure is simply a matter of stopping to retrieve data, and continue when you need more.

Once you wrapped your datasources into a Source. Thats it, at that point you have access to all the rest that the Akka.Streams Api has to offer.

**Comment by sean-gilliam** [comment]
Hopefully, you've found a solution to your problem. Generally questions should be directed to our gitter chat room gitter.im/akkadotnet/akka.net.
Issues are usually reserved for actual bugs. Closing this issue.
