### ISSUE TITLE
akka.net and system.runtime both contain system.serializeattribute

### ISSUE THREAD

**Issue by hiwjcn** [akkadotnet/akka.net#3523]
akka.net and system.runtime both contain system.serializeattribute

version:
.net core 2.0
akka 1.3.8

here is the screen shot:
![http://hiwjcn.qiniudn.com/TIM%E6%88%AA%E5%9B%BE20180623190332.png](http://hiwjcn.qiniudn.com/TIM%E6%88%AA%E5%9B%BE20180623190332.png)
if can't see the pic,direct to http://hiwjcn.qiniudn.com/TIM%E6%88%AA%E5%9B%BE20180623190332.png

**Comment by Aaronontheweb** [comment]
@hiwjcn yes, these are polyfills from the pre-.NET Standard 2.0 days. In order to target .NET Standard 1.6 we had to add them back since the `SerializableAttribute` wasn't part of the .NET Standard library.

They reversed that decision in .NET Standard 2.0.

We're in the process of moving Akka.NET onto .NET Standard 2.0 as part of our v1.4.0 release and we'll go through and remove these once that's finished. https://github.com/akkadotnet/akka.net/pull/3452

In the meantime, this is stopping you from writing unit tests that utilize the `Serializable` attribute?

**Comment by Aaronontheweb** [comment]
cc @Danthar you're still working on this, right?

**Comment by hiwjcn** [comment]
@Aaronontheweb thanks for ur patient help

**Comment by Danthar** [comment]
@Aaronontheweb Yup

**Comment by Cephei** [comment]
Is there any temporary solution to this? Shall I just use `DataContract` and place `DataMember` on all fields?

**Comment by Aaronontheweb** [comment]
Other than recompiling Akka.NET in your own fork without those polyfills, no - or don't use the `Serializable` attribute like you suggested. There are some other work-arounds suggested here: https://github.com/akkadotnet/akka.net/issues/3161

We'll have this fixed in the v1.4 release but there's nothing we can do between now and then given that this requires a platform change (i.e. we have to move onto .NET Standard 2.0 to not need the polyfills anymore.)

**Comment by Cephei** [comment]
Much appreciated @Aaronontheweb. Looking forward to 1.4 / Standard 2.0!

**Comment by hiwjcn** [comment]
@Aaronontheweb haha can't wait for the version 1.4,can i have the release scheduler?

**Comment by saxenashubham** [comment]
@Aaronontheweb when can we expect the release of v1.4?

**Comment by crasshacker** [comment]
Has anyone managed to modify the Akka.NET sources to remove the SerializableAttribute polyfill and compile Akka.NET (core and remote libraries) for netstandard 2.0?  Also, is there an update on when Akka 1.4 will be released, with netstandard 2.0 officially supported?

**Comment by Aaronontheweb** [comment]
Resolved. Pushing first beta of Akka.NET v1.4 now.
