### ISSUE TITLE
Problem with ActorSelection().ResolveOne(TimeSpan timeout)

### ISSUE THREAD

**Issue by VladimirLuzhin** [akkadotnet/akka.net#3547]
- **Version Akka.NET v1.3.8**
- **Version Akka.TestKit.NUnit3 v1.3.2**
- **Version NUnit v3.10.1**
- **Platform Windows 10**

I have an actor of the following kind:

```
public class BranchUsersActor : ReceiveActor
{
    public BranchUsersActor()
    {
        Receive<UserBeingOnline>((online) =>
        {
            var userActorName = $"user_{online.UserId}";
            if (Context.Child(userActorName).Equals(ActorRefs.Nobody))
            {                
                var user = Context.ActorOf(UserActor.Props(online.UserId, online.BranchId), userActorName);
                user.Tell(online);                    
            }
        });
    }

    public static Props Props(LoggingTags tags)
    {
        return Akka.Actor.Props.Create(() => new BranchUsersActor(tags));
    }
```

When testing this actor, I expect that I will have a child actor.
I'm writing the next test to check this situation (using the NUnit framework):

```
[Test]
public void Test()
{
    var branchUserActor = Sys.ActorOf(BranchUsersActor.Props());
    branchUserActor.Tell(UserBeingOnline.Create(userId, branchId));
   
    var expectedChildActor = Sys.ActorSelection($"{actorPath}/user_{userId.AkkaPrepare()}")
        .ResolveOne(TimeSpan.FromSeconds(1)).Result;
    
    Assert.IsNotNull(expectedChildActor);
}
```
I expect that within a second I will receive the child actor on the specified path, but I get _ActorNotFoundExpection_.

If I'm doing something like this:
```
[Test]
public void Test()
{
    var branchUserActor = Sys.ActorOf(BranchUsersActor.Props());
    branchUserActor.Tell(UserBeingOnline.Create(userId, branchId));
   
    Task.Delay(100).ContinueWith(_ => 
    {
        var expectedChildActor = Sys.ActorSelection($"{actorPath}/user_{userId.AkkaPrepare()}")
            .ResolveOne(TimeSpan.FromSeconds(1)).Result;
    }
    Assert.IsNotNull(expectedChildActor);    
}
```
This works fine, but 1 of 10 times the test falls, because I get an _ActorNotFoundException_.
But I wonder why the first option does not work the way I expect?

Am I doing something wrong? 

Thanks in advance for the answer.

**Comment by Ralf1108** [comment]
Could it be that your assumption "I expect that within a second I will receive the child actor" is not reflected in code?

As I understand your code the following happens:

1. Advise actor system to create an actor -> this returns only an actor ref. The real actor might not yet be created. This is done in the background... because think about if the actor should be created on another machine. The "ActorOf()" call should not block in any case.
2. You send a message to this actot ref -> in reality this only queues a message for a specific actor ref. This does not ensure that the actor is now created or the message is delivered immediately.
3. Then you wait 100ms giving time to spin up actor and handle your queued message.
4. Immediately after the 100ms you check via actor selection if your user actor was created yet. The exception occurs here because if ActorSelection finds out if actor is not available at this point in time it quits with an exception. I dont think that the actor selection will poll and retry within a time intervall of 1 second until the actor eventually starts up. This behavior has to be implemented by yourself.

Possible solutions:

1. Increase your 100ms delay to 200ms. But this would only make your exception less likely and could still occur. Then maybe  1 in 1000.
2. For reliable waiting for actor to startup implement own polling mechanism with ActorSelection. Retry the actor selection if 1 second has not yet passed. This solution is better than solution 1 with delay of 1 second because your unittest continues immediately if the actors comes up earlier.

**Comment by Horusiath** [comment]
```csharp
branchUserActor.Tell(UserBeingOnline.Create(userId, branchId));
   
var expectedChildActor = Sys.ActorSelection($"{actorPath}/user_{userId.AkkaPrepare()}")
      .ResolveOne(TimeSpan.FromSeconds(1)).Result;
```

The problem here is that when you're telling `UserBeingOnline`, you're triggering an asynchronous action - a message has been send to `branchUserActor`, but it may not have been served right away. In the meantime you're calling resolve one, which tells actor system to find a child of `branchUserActor` - a child, which is not yet there, since the parent didn't handle the message yet.

**Comment by Ralf1108** [comment]
Good to know that there is already a method for it :-)

**Comment by VladimirLuzhin** [comment]
Thank you for your responses @Ralf1108, @Horusiath. You really helped me.
