### ISSUE TITLE
Persistence SqlJournal events written out of sequence

### ISSUE THREAD

**Issue by anthonyhawes** [akkadotnet/akka.net#3590]
Akka.Net 1.3.9 on Windows (Full .NET Framework)

Using SQL based journals, under load multiple events for the same actor can be written to the database out of sequence.
Processing a command message which persists multiple events via separate calls to Persist. These can potentially be batched up into the same call to WriteMessagesAsync. Each AtomicWrite is then processed in a separate (potentially concurrent) task via an async call to the database. At this point the order of writes is fairly arbitrary.

**Comment by Aaronontheweb** [comment]
Hi @anthonyhawes 

I'm not convinced you're correct here. Do you have a reproduction example or some data that indicates that this is an issue?

https://github.com/akkadotnet/akka.net/blob/75b1333a37dcbd8f0a8db46d39e27a6659c17b98/src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/SqlJournal.cs#L135-L198

I don't have time to go through the entire code base now, but the way this code works is that unless each event is written atomically, with its _predetermined sequence number_, on as independent events. The order in which the events are inserted into the database shouldn't actually matter since the keys have already been pre-determined by the persistent actor. We don't use auto-incrementing IDs.

In practice though, I have yet to actually see this code execute multiple inserts for a single persistent actor at a time.

**Comment by anthonyhawes** [comment]
Hi @Aaronontheweb, I don't have a simple code snippet that easily reproduces the behaviour (concurrency issues being what they are), but I am seeing this happen several times a day in production. It only started happening when we introduced code that made multiple calls to Persist when processing a single command message, much like the example in the documentation (http://getakka.net/articles/persistence/event-sourcing.html) and not all the time, only under load.
You are correct that the ordering in the database shouldn't affect the persistent actor because the sequence number is predetermined. It is a problem when replaying events to a separate store for querying, because the persistence query mechanism streams the events using the ordering column, which in this case means they come out in the wrong order.

**Comment by Horusiath** [comment]
@anthonyhawes before we'll fix this issue, the easiest workaround (hopefully working) would be to persist multiple events at once: `Persist` method has overloads, that allow you to store more than one event in a single call.

**Comment by anthonyhawes** [comment]
@Horusiath Thanks for the suggestion. I've already tried that and also calling Persist for the second event from inside the callback to the first. Both workarounds solve the out of order problem, but surface a different problem with persistence query events by tag where some of the events don't appear in the query stream. I am nearly finished writing a (bare bones) persistence plugin for PostgreSQL (the database in question) to help me gather more data.

**Comment by anthonyhawes** [comment]
It looks like it's the way PostgreSQL handles concurrency. Because lots of transactions are in flight it results in auto increment values being generated as normal, but other transactions with later auto increment values are committed first.
