### ISSUE TITLE
Problem with DistributedPubSub

### ISSUE THREAD

**Issue by avber** [akkadotnet/akka.net#3743]
Akka.net 1.3.12
.Net Core 2.1

Cluster setup
1 deployer node on Windows (10.0.80.131)
3 worker nodes on Centos 7 (CPU intensive operations)
2 lighthouse nodes

Deployer and worker nodes have this section in config file (taken almost verbatim from the docs):
akka.cluster.pub-sub {
  name = distributedPubSubMediator
  role = ""
  routing-logic = random
  gossip-interval = 5s
  removed-time-to-live = 120s
  max-delta-elements = 3000
  use-dispatcher = ""
}

I'm observing the following situation with my cluster. 

The cluster is stable, 4 CPUs out of 8 are used to perform operations.

Things change when I use DistributedPubSub. 

Once an actor on a worker node is subscribed or PubSub message is sent , Disassociated messages pop up and actors are restarted on worker nodes.

Logs:
2019-03-22 17:52:33.7640|WARN|192.168.150.62 DistributedSubscribeActor Receive SettingsMessage 3 from [akka.tcp://tess-system@10.0.80.131:4055/deadLetters]

Akka.Cluster.Tools.dll is present on deployer and worker nodes.

**Comment by Horusiath** [comment]
@avber since you're not using any specific role in your pub/sub config, do you have DistributedPubSub started and configured on all nodes (including lighthouses)?

**Comment by avber** [comment]
I have DistributedPubSub started and configured on all nodes EXCEPT lighthouses

Now I have separate configs on 1 deployer and 3 worker nodes:

akka.cluster.pub-sub {
name = distributedPubSubMediator
role = "deploy"
routing-logic = random
gossip-interval = 5s
removed-time-to-live = 120s
max-delta-elements = 3000
use-dispatcher = ""
}

akka.cluster.pub-sub {
name = distributedPubSubMediator
role = "worker"
routing-logic = random
gossip-interval = 5s
removed-time-to-live = 120s
max-delta-elements = 3000
use-dispatcher = ""
}

Cluster is stable. 

Pubsub message is sent from the deployer node.

However, first messages end up in deadLetters. After a few attempts the deadLetters log entry disappears.

[19:02:21 INF] tess-system sent TesseractSettings 3
[INFO][3/22/2019 1:02:21 PM][Thread 0023][akka://tess-system/system/distributedP
ubSubMediator] Message TesseractSettingsMessage from akka://tess-system/deadLett
ers to akka://tess-system/system/distributedPubSubMediator was not delivered. 9
dead letters encountered.
[19:02:26 INF] tess-system sent TesseractSettings 3
[19:02:31 INF] tess-system sent TesseractSettings 3
[19:02:36 INF] tess-system sent TesseractSettings 3
[19:02:41 INF] tess-system sent TesseractSettings 3
[19:02:46 INF] tess-system sent TesseractSettings 3
[19:02:51 INF] tess-system sent TesseractSettings 3
[19:02:56 INF] tess-system sent TesseractSettings 3
[19:03:01 INF] tess-system sent TesseractSettings 3
[19:03:06 INF] tess-system sent TesseractSettings 3
[19:03:11 INF] tess-system sent TesseractSettings 3
[19:03:16 INF] tess-system sent TesseractSettings 3
[19:03:21 INF] tess-system sent TesseractSettings 3
[19:03:26 INF] tess-system sent TesseractSettings 3
[19:03:31 INF] tess-system sent TesseractSettings 3

Actors on worker nodes (DistributedSubscribeActor) never get pubsub messages.

public DistributedSubscribeActor(IActorRef coordinator)
        {
            Log = Serilog.Log.Logger.ForContext(GetType());

            this.coordinator = coordinator;

            Receive<TesseractSettingsMessage>(s =>
            {
                Log.Warning($"DistributedSubscribeActor Receive TesseractSettingsMessage {s.OMP_THREAD_LIMIT} from {Sender}");
            });

            DistributedSubscribe();
        }

        void DistributedSubscribe()
        {
            Log.Warning($"DistributedSubscribeActor DistributedSubscribe");

            try
            {
                var mediator = DistributedPubSub.Get(Context.System).Mediator;

                mediator.Tell(new Subscribe("TesseractSettings", Self));
            }
            catch (Exception ex)
            {
                Log.Error(ex, "DistributedSubscribe " + ex.Message);
            }

        }

What am I doing wrong?

**Comment by Horusiath** [comment]
If you're configuring `akka.cluster.pub-sub.role` with different roles, this means that you'll create different spaces. Each distributed pub/sub mediator will only see mediators having the same role. 

Also make sure, that your actorSystem has joined the cluster (ie. by using `await Cluster.Get(system).JoinAsync("<lighthouse-node-address>")`) before sending messages to DistributedPubSub mediator.

**Comment by avber** [comment]
So lighthouse is not a dumb node after all...

Why does the cluster become unstable if DistributedPubSub mediator is not running on a node (in my case on lighthouse)?

**Comment by Horusiath** [comment]
It's not about lighthouse. Almost every Akka cluster plugin (i.e. DistributedPubSub, ClusterSharding, ClusterSingleton) must know, which of the cluster nodes are also running the same plugin in order to share messages. *Of course it could ask every cluster node if there's a corresponding actor living on it, but quite often those actors may live on configured, non-standard paths and this would take more time and risk to discover all of the nodes with target plugin on it.*

Therefore the standard way to resolving, which nodes are running the same plugin is simple: they are making conservative guess, that cluster is homogeneous (it means that all nodes have the same behavior and capabilities), so all nodes run the same code. This can be changed by configuring a role for target plugin - it will say to it, that only nodes with the configure role name have required capabilities.

Your specific problem comes from the fact, that you've not configured roles for DistributedPubSub in the first step (so it assumed that lighthouse nodes participate in pub/sub and was sending messages, that lighthouse couldn't deserialize because it didn't understood them) and in seconds step you've attached different roles for it in worker and deployer nodes, so DistributedPubSub working on each of them didn't know about each other.

**Comment by avber** [comment]
Got it. Thank you for the detailed explanation. 

>lighthouse couldn't deserialize because it didn't understood them
I thought the system is resilient to such errors.

Closing the issue.
