### ISSUE TITLE
System.ArgumentException when trying to close TCP connection

### ISSUE THREAD

**Issue by MichaelMayrhofer** [akkadotnet/akka.net#3768]
**Environment**
* Akka Version 1.3.12
* .NET Framework 4.7.1
* Win7
* Visual Studio 2017

**Steps to reproduce**
1. Check out a simple demo: https://github.com/MichaelMayrhofer/Akka.TcpDemo
The repo contains two projects:
1.1 **TcpServer:** Waits for an incoming TCP connection and sends each second a date-time string to the connected client.
-> Implemented without akka.net.
1.2 **TcpClient:** Connects to a TCP server, receives data and closes the connection.
-> Implemented with akka.net.
2. Build & run the two programs.
3. Press [enter] in the TcpClient.exe console window to connect to the TCP server.
4. The TcpClient should receive data.
5. Press [enter] in the TcpClient.exe console window to close the connection.

=> there will be an error output in the TcpClient.exe console window:
> [ERROR][29.04.2019 05:17:24][Thread 0004][akka://Akka-TcpDemo/system/IO-TCP] The  supplied message type is invalid. Only Connect and Bind messages are supported.
>
> Parametername: message
> Cause: System.ArgumentException: The supplied message type is invalid. Only Connect and Bind messages are supported.
> Parametername: message
>    bei Akka.IO.TcpManager.Receive(Object message)
>    bei Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
>    bei Akka.Actor.ActorCell.ReceiveMessage(Object message)
>    bei Akka.Actor.ActorCell.Invoke(Envelope envelope)

**Implementation details:**
The TcpClient uses `Context.System.Tcp().Tell(new Tcp.Connect(...))` and `Sender.Tell(new Tcp.Register(...))` to open the TCP connection. With `Context.System.Tcp().Tell(Tcp.Close.Instance)` the connection will be closed.

**Comment by Aaronontheweb** [comment]
We should definitely change this error message to say WHICH type of message we supplied that was invalid.

**Comment by IgorFedchenko** [comment]
@MichaelMayrhofer Actually, if you will take a look onto diagram [here](https://getakka.net/articles/networking/io.html), you will notice that `Tcp.Close` message should be sent to TcpOutgoingConnection actor, that was created for you once you sent `Tcp.Connect` message to TcpManager (that is, to `Context.System.Tcp()`). Not to the TcpManager, which is what your sample does.

So, basically if your `Commander` and `ConnectionHandler` from the referenced picture is the same actor, then you need to store `Sender` of `Tcp.Connected` message internally, and after job is done you should send `Tcp.Close` to that stored reference. Since `TcpManager` is not the one who closes connections - he only opens them, and you need to ask the connection to close itself.

So, I do not see any bug here . But with that said, as @Aaronontheweb suggested nothing wrong would be in adding more detailed exception message with invalid command type and some hints like "If you are going to manage your connection state, you need to communicate with `Tcp.Connected` sender actor. See more here: (url to the docs)". I will make PR to close this issue.

**Comment by MichaelMayrhofer** [comment]
@IgorFedchenko Thank you for your detailed explanation.
