### ISSUE TITLE
DotNetty error when sending packets to akka system

### ISSUE THREAD

**Issue by edwinparker** [akkadotnet/akka.net#3789]
We have an akka.net application running and we get a security scan every so often on the host/port the application is running on.  It produces the "Adjusted frame length exceeds 128000: xxxxx - discarded" error.

At first I thought it was sending a large amount of data based on the error but that doesn't appear to be the case. I was able to reproduce this locally by using Packet Sender utility (https://packetsender.com).  If I send more than 3 ASCII characters using the tool to the open host/port that akka is using (I just used lighthouse 127.0.0.1:4053 for testing) then this error is thrown.  If I have 3 or less ASCII characters there is no error.  Also the value xxxxx seems to be a little random, but that could be my lack of understanding dotnetty.

My question is why would this error occur with such little data being sent?  I would expect it to error out if I sent a large value to it (> 128000b).  I suppose the tool (Packet Sender) could be sending more data that I'm not aware of, but it seems to error out and respond by saying a large value was sent.  Is this a bug in akka or dotnetty? Is there some way I can prevent this from being thrown when our security scanner scans our application?  Thanks for any help or suggestions.

I am using v1.3.13 on a windows environment using the latest dev branch lighthouse akka application as a test.

![image](https://user-images.githubusercontent.com/3344524/57891464-b3951f00-77f8-11e9-81e7-60470cb63b1f.png)

**Comment by Aaronontheweb** [comment]
@edwinparker if you fire a packet at the DotNetty TCP transport without any [frame-length encoded headers](https://petabridge.com/blog/large-messages-and-sockets-in-akkadotnet/) - a 4 byte header DotNetty uses to determine how long the current message is within the TCP stream, then DotNetty will interpret the content of your message as the 4 byte header instead. and produce a corrupted message size.

In other words, you can't just send unencoded packets to DotNetty - it expects every message to be prefixed with that 4 byte header. Otherwise you'll get an error like this. It's a standard part of the messaging apparatus used by DotNetty in this configuration. Not a bug with DotNetty or Akka.Remote - just the way it's configured. The link I included explains the rationale for why these headers are necessary in socket-driven systems.

**Comment by edwinparker** [comment]
Thanks for the clarification @Aaronontheweb. I am assuming the error causes no harm to the health of an akka system and we can just ignore the error, assuming we can't get our security guys to just stop scanning our application?

Keep up the good work! We are loving akka.net!

**Comment by Aaronontheweb** [comment]
@edwinparker happy to help! Won't affect your Akka.Remote nodes at all - that one connection opened by your security guy will simply get disassociated and closed right away. So other than some error messages appearing in your logs it won't cause any harm.

Glad you're having a great experience with Akka.NET!
