### ISSUE TITLE
Measuring mailbox size

### ISSUE THREAD

**Issue by stefansedich** [akkadotnet/akka.net#383]
After a discussion with Aaron this morning over here: https://github.com/Aaronontheweb/akka-monitoring/issues/2

I thought it would be a good idea to bring this here, does anyone have any ideas on how this can best be implemented in the core? happy to help with implementation if required.

Cheers
Stefan

**Comment by Erlord** [comment]
Hi, has there been any progress on this? It is a very important area I think for monitoring where messages are backing up, whats slowing down the system.

**Comment by AlbertoMonteiro** [comment]
Some news?

**Comment by splitice** [comment]
+1

**Comment by nekenk1** [comment]
+1

**Comment by Aaronontheweb** [comment]
So we support this inside [Phobos, Petabridge's Enterprise DevOps Suite for Akka.NET](https://phobos.petabridge.com/): https://phobos.petabridge.com/articles/monitoring/configuration.html

If you set enable the `phobos.monitoring.monitor-mailbox-depth = on` we record these metrics and emit them automatically to whatever monitoring back-end you've configured.

I should note here that Phobos is a commercial product and requires a license.

**Comment by Aaronontheweb** [comment]
If you want to access this data yourself in Akka.NET today, there's a way to do it but it requires getting access to some of the "internal," yet publicly exposed APIs:

```csharp
// from within an actor
Context.AsInstanceOf<ActorCell>().Mailbox..MessageQueue.Count);
```

I think that should allow you to get access to the number, but note that on really high throughput actors this will may have a performance impact as I believe accessing the `Count` locks the underlying queue temporarily. In the majority of cases though that should be fine - you'll only really see something come up if your actors are processing messages in the millions / second range. Nevertheless though, that's why we have this setting turned off by default inside Phobos.

**Comment by nekenk1** [comment]
Thanks I will try that, we don't manage millions of events per second but we do load the machine heavily with other processes that can consume a lot of CPU...
