### ISSUE TITLE
Docs: need to encourage Akka.Persistence users to use IEventAdapters and Tags from day one

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#3937]
Version: N/A

For users who are interested in using Akka.Persistence.Query, CQRS, EventSourcing, projections, and so forth - the only practical way to combine data from multiple persistent entities without knowing in advance what those entity IDs are is to use Akka.Persistence.Query's `EventsByTag` queries.

Unfortunately, if you start writing to Akka.Persistence without using any tags at all, you really don't have any mechanism for replaying historical events without going back and ETL-ing your data.

Therefore, all events should be tagged with some sort of generic "omni" event at least, so you have the option of replaying the entire journal in its chronological order if you really needed to.

We don't cover this in any depth at all in our current literature, and I think that's a mistake. We should really look to set Akka.Persistence users up with best practices from day 1 and I think this is one of them: use tags from the beginning and here are some ways you might want to use them later.

**Comment by ismaelhamed** [comment]
I couldn't agree more. `EventsByPersistenceId` will only get you so far (a few thousand streams maybe) but this is not obvious, specially if you are coming from the deprecated Persistence Views.

Still, `EventByTags` comes with its own issues. For instance, if your're using them with sharded persistent actors (which can easily accommodate hundreds of thousand of them), you will probable need to shard those tags too, since a single stream per tag won't cut it. 

We borrow all that stuff from Lagom, but having same examples on how to solve it would definitely help newcomers to the game.

**Comment by Aaronontheweb** [comment]
> Still, EventByTags comes with its own issues. For instance, if you're using them with sharded persistent actors (which can easily accommodate hundreds of thousand of them), you will probable need to shard those tags too, since a single stream per tag won't cut it.

> We borrowed all that stuff from Lagom, but having same examples on how to solve it would definitely help newcomers to the game.

Is this something we need to factor in, technically, to the design of Akka.Persistence or is this more of an end-user guidance type issue? Is this something that can be solved with how the users use the plugin, in other words?

**Comment by ismaelhamed** [comment]
Basically, the idea is to utilize the Cluster Sharding tool but with Persistence Queries instead of normal actors. Eventually, if you have too many (and your mileage may vary) persistent actors all using the same tag (i.e., "DeviceEvent"), a single stream won't suffice to keep the pace. What you probable want in this case is to shard this tag: something like `DeviceEvent-0` to `DeviceEvent-N` ('n' being the total number of shards).

There are two implementations of this, that I know of: one in Lagom, which I find too tailored towards that particular framework; and more recently they added a [CQRS](https://github.com/akka/akka-samples/tree/2.5/akka-sample-cqrs-scala) sample with a more straightforward implementation. Actually, I started porting that sample a while back, so maybe I could resume work and issue a PR. This would definitely help.

**Comment by Zetanova** [comment]
This issue is related to https://github.com/akkadotnet/akka.net/issues/3971 also.

What is missing to work with Journals by themself, is something to query all events
and to query the highest SeqNr/Offest. 

if the journal-plugin only skips the deserialization of the events to query the highest SeqNr/Offset 
it would improve already a journal import/export.   

It should be similar to EventByTags but for AnyTag (including NoTag).

A user the needs to correct the misstake of  not using IEventAdapters to tag from the start
could then migrate/copy all events from OldJournalA to NewJournalB to tag them.

**Comment by Aaronontheweb** [comment]
> What is missing to work with Journals by themself, is something to query all events
and to query the highest SeqNr/Offest.

Yeah, this is one problem that tags can solve. Having a "default" tag that gets applied to every message would solve this problem too - so you can perform a full, ordered scan of the contents. We just ran through an ETL like this for a customer that's been using Akka.Persistence for ~4 years and it's been very tricky doing this without tags.

**Comment by Aaronontheweb** [comment]
@ismaelhamed @Zetanova is having a standard "default" tag that always gets added a terrible idea? Or we could just have a separate query that's able to traverse the "Ordering" index without any tag.

**Comment by Zetanova** [comment]
Made the same thing yesterday only from mssql to eventstore with around 500k events. It took around 4h by query every pid.

The other issue is the resume after the first copy. The copy system would need to know the last sequence number of the destination journal. of course it could save it somewhere else but it is like to demand from rsync to make a temp file to copy a folder.


Von meinem Samsung Gerät gesendet.


-------- Ursprüngliche Nachricht --------
Von: Aaron Stannard <notifications@github.com>
Datum: 11.10.19 17:08 (GMT+01:00)
An: "akkadotnet/akka.net" <akka.net@noreply.github.com>
Cc: Andreas Dirnberger <dirnberger@cwtech.at>, Comment <comment@noreply.github.com>
Betreff: Re: [akkadotnet/akka.net] Docs: need to encourage Akka.Persistence users to use IEventAdapters and Tags from day one (#3937)


What is missing to work with Journals by themself, is something to query all events
and to query the highest SeqNr/Offest.

Yeah, this is one problem that tags can solve. Having a "default" tag that gets applied to every message would solve this problem too - so you can perform a full, ordered scan of the contents. We just ran through an ETL like this for a customer that's been using Akka.Persistence for ~4 years and it's been very tricky doing this without tags.

**Comment by Zetanova** [comment]
To extend the query tag spec by an any-tag
And a no-tag would be a good option.

Anytag: every event, including events without a tag
Notag: only events without a tag


-------- Ursprüngliche Nachricht --------
Von: Aaron Stannard <notifications@github.com>
Datum: 11.10.19 17:09 (GMT+01:00)
An: "akkadotnet/akka.net" <akka.net@noreply.github.com>
Cc: Andreas Dirnberger <dirnberger@cwtech.at>, Mention <mention@noreply.github.com>
Betreff: Re: [akkadotnet/akka.net] Docs: need to encourage Akka.Persistence users to use IEventAdapters and Tags from day one (#3937)


@ismaelhamed<https://github.com/ismaelhamed> @Zetanova<https://github.com/Zetanova> is having a standard "default" tag that always gets added a terrible idea? Or we could just have a separate query that's able to traverse the "Ordering" index without any tag.

**Comment by Aaronontheweb** [comment]
@Zetanova maybe we should split this out into its own issue - I'm sure we can add the "all events" query without having to retroactively modify any one's events using tags.

**Comment by ismaelhamed** [comment]
IMHO, migrations are a very application-specific scenario. Wouldn't it make more sense to solve this at the application level, by adding those ad-hoc queries to a custom ReadJournal?:
```csharp
public class MigrationReadJournal : SqlReadJournal
{
    public MigrationReadJournal(ExtendedActorSystem system, Config config) 
        : base(system, config)
    { }

    public Source<EventEnvelope, NotUsed> AllEvents()
    {
        //...
    }

    public Source<long, NotUsed> ReadHightestSequenceNr(string persistenceId)
    {
        //...
    }
}

PersistenceQuery.Get(system)
    .ReadJournalFor<MigrationReadJournal>(SqlReadJournal.Identifier)
    .AllEvents()
    .RunWith(Sink.Ignore<EventEnvelope>(), mat);
}
```
Maybe even come up with a "generic migration plugin" built on top of Akka.Persistence, not within.

**Comment by Aaronontheweb** [comment]
> IMHO, migrations are a very application-specific scenario. Wouldn't it make more sense to solve this at the application level, by adding those ad-hoc queries to a custom ReadJournal?:

That's a lot of engineering work for someone who's not familiar with the Akka.Persistence implementation internals - and having spent some time bug-fixing more than 1 Akka.Persistence.Query implementation this month I can tell you that it's often done wrong. Exposing a way to query the `Ordering` index, however that's determined, as part of the core Akka.Persistence.Query API (and not all journals have to implement that either) wouldn't be a bad thing I think. Open to different opinions though.

**Comment by Zetanova** [comment]
I had yesterday a mistake in one of the Flag interface. 
The Event inherited from the DomainCommand  

```csharp
public interface IMyARCommand : IMyCommand, IMyDomainEvent
{
}

public interface IMyAREvent : IMyCommand, IMyDomainComman
{
}
```

I only saw it by chance as i looked into eventstore webpanel.

For Debug/Warning purpose the NoTag Query option would be very useful
and combined with a *new Offset* feature ```Offset.Current``` 
a debug warning could be implemented.

```csharp
readJournal.EventsByTag(QueryTag.NoTag, Offset.Current)
   .RunForeach(n => Log.Warning("Untagged Event: {event}", n), materializer);   
```

**Comment by Aaronontheweb** [comment]
@Arkatufus did we end up porting that "all events query" in Akka.Persistence.Query? If so, we don't need to do this anymore do we?

**Comment by Zetanova** [comment]
@Aaronontheweb yes was added some versions ago, it is a query faced `IAllEventsQuery`
https://github.com/akkadotnet/akka.net/blob/8fd4af42c8ce1bcb304784d2c89ba004d4e00cfd/src/core/Akka.Persistence.Query/Interfaces.cs#L82-L85

**Comment by Aaronontheweb** [comment]
I think we can close this issue then.
