### ISSUE TITLE
Remote Sender akka Actor is terminated after 30 sec in other cluster

### ISSUE THREAD

**Issue by Dmdv** [akkadotnet/akka.net#4110]
Akka.Version: 1.3.16
Platform: docker, net.core 3.1

With `ClusterClient.Send` a message is sent to remote actor.<br>
The remote actor receives the message and stores the sender in local variable.<br>
After 30 sec the remote sender is terminated.

**Details:** <br>
Both actors are living in different clusters.
Sending actor is not dying on it's own cluster, only in remote one.

I've tried to find any docs or any related settings to make this Sender Actor live forever on the side of other cluster. So far no luck

Need help to resolve this

Akka.Version: 1.3.16
Platform: docker, net.core 3.1

**Comment by Aaronontheweb** [comment]
That's because of this setting inside Akka.Cluster.Tools.ClusterClientReceptionist:

https://github.com/akkadotnet/akka.net/blob/63472ea8d0ec72135a20a7a83a5fab9d4cd5a035/src/contrib/cluster/Akka.Cluster.Tools/Client/reference.conf#L11-L24

It times out the response tunnel if no one has attempted to communicate through it within 30 seconds by default.

I'd recommend increasing the timeout in your case.
