### ISSUE TITLE
Akka.Pattern: Pass in clearer error message into OpenCircuitException

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#4314]
Akka.NET Version: 1.4.1-rc1 and later

When an Akka.Persistence journal begins experiencing failures on the database-side of the operation, users begin seeing lots of `OpenCircuitExceptions` appear inside their logs - these errors don't do much to tell the human operators of Akka.NET clusters and applications what is really going on under the covers and what the root cause of the issue is.

If we could add some method overloads to `CircuitBreaker` to make it possible to provide a hint as to what's going on, that would be very useful for operators.

**Comment by ismaelhamed** [comment]
I've had this conversation so many time. Because only the very first exception will actually give you some insight, and everything after that is just failing fast. 

One possible solution could be to make the `CircuitBreaker` remember the last exception (which made the circuit to break) and set it as the `InnerException` of the `OpenCircuitException`
