### ISSUE TITLE
HOCON substitution from .net Core configuration

### ISSUE THREAD

**Issue by atrauzzi** [akkadotnet/akka.net#4341]
- 1.4.2
- Windows 10

It would be nice if I could give akka.net the ability to leverage the values in my `appsettings.*.json` files via the `Microsoft.Extensions.Configuration` abstraction.

**Comment by Aaronontheweb** [comment]
This was a huge part of the HOCON sprint for v1.4, which we ultimately rolled back due to some problems that reared their heads during integration testing: https://getakka.net/community/whats-new/akkadotnet-v1.4.html#changes-between-akkanet-v141-rc1-and-akkanet-v141-rc23stable

We've also added this to the HOCON 3.0 specification for stand-alone HOCON: https://github.com/akkadotnet/HOCON/issues/267 - it'll be addressed there. 

We're not starting work on HOCON 3.0 right away yet - have a significant number of post-1.4 projects that we're still working on :p

**Comment by atrauzzi** [comment]
Noted!
