### ISSUE TITLE
Whether akka has a disconnect message?

### ISSUE THREAD

**Issue by ShawnYun** [akkadotnet/akka.net#4366]
- Akka.net 1.4.2
- Windows 10 x64
- When I send a connect message and receive a connected message, I don't want to establish a connection for some reason，such as too many connections. Is there any way to send a failed connection with a message to tell the remotenode the reason? Like HTTP various status codes.

**Comment by Aaronontheweb** [comment]
@ShawnYun is this question for Akka.Remote or Akka.IO?

**Comment by ShawnYun** [comment]
@Aaronontheweb I think it is Akka.IO.

**Comment by IgorFedchenko** [comment]
@ShawnYun 

Could you please clarify the issue you are trying to solve? 
Your actor is requesting for new connection with `Connect` command, gets `Connected` message - and decides that he does not want to have this connection anymore (there are too many connections already opened for example). And then - what you want to do? How is remote node related to that? Is remote note a server you have connected and now want to disconnect? 

If you want to close connection, you will send `Close` command. And server will receive `PeerClosed` message for client's connection. If you want to notify server a close reason, you may send some special message to server first, containing all the details, and after that send `Close` command. This way server will receive message with closing reason before receiving `PeerClosed`.

Is it what you were trying to do?

**Comment by ShawnYun** [comment]
@IgorFedchenko For example, there are two nodes A and B. First, A wants to establish a connection with B, so A send `Conntect` to B,  then B response `Connected` to A. Normally, A needs to send `Register` to B, but now for some reason A doesn't want to establish a connection with B, and A wants B konw the reason why aborting connection. Is there any way to let B know the reason without sending a `Register`?
![78322571-b1b78400-75a1-11ea-9eb1-84ba0337fd4a](https://user-images.githubusercontent.com/42930111/80184434-2760be00-863d-11ea-8a42-f77ee0e11c91.png)

**Comment by IgorFedchenko** [comment]
First of all, we need to understand that node B is Akka.NET internal `TcpConnection` actor (the TCP Outgoing Connection on the diagram above), which handles your socket connection. So do not fully understand what you mean by "sending reason to node B".

After receiving `Connected` message you have a `Sender` reference, which is reference to this `TcpConnection`, B node. Now if you do not want to register handlers, you are able to send `Tcp.Close` message to abort connection. That would be "disconnect message".

But there is nothing about the reason of disconnect - because `TcpConnection` does not care of the reason. 

Another important thing to keep in mind is that real socket connection to server/remote actor is opened after `Connect` message was sent. Server already has new client connected. And if you need to notify your remote actor (server) why you decided to not connect (or, better to say, why you decided to disconnect), you'll need to send `Register` and then send your reason via `WriteCommand` before sending `Close`. 
That's the case if "B node" you wanted to notify of the reason is not the `TcpConnection` you are sending `Connect` to, but some another custom actor behind the network.

**Comment by ShawnYun** [comment]
@IgorFedchenko Thanks. So, I can send the `Tcp.Close`message directly to close, or I send the `Register` and then I send the reason via `WriteCommand` before sending `Close`. Is it right?

**Comment by IgorFedchenko** [comment]
@ShawnYun Exactly. In the first case, your connection will be closed silently for your server. In the second, server will receive a reason before connection is closed.

**Comment by Aaronontheweb** [comment]
@ShawnYun @IgorFedchenko is this issue resolved or do we need to take some additional action here?

**Comment by IgorFedchenko** [comment]
I guess we can close it. @ShawnYun feel free to reopen/ask additional questions.

**Comment by ShawnYun** [comment]
@IgorFedchenko @Aaronontheweb Thanks. Professional answer.
