### ISSUE TITLE
Is the suggested PersistenceId in Cluster Sharding Documentation right?

### ISSUE THREAD

**Issue by chrisbarker** [akkadotnet/akka.net#4406]
In Akka Cluster Sharding documentation for persistent actors
https://getakka.net/articles/clustering/cluster-sharding.html#integrating-cluster-sharding-with-persistent-actors

It says each actor path will follow the `/system/{typeName}/{shardId}/{entityId}` pattern
It then suggests that the PersistenceId could be created from the actor path as

`PersistenceId = Context.Parent.Path.Name + "-" + Self.Path.Name;`

which will use `shardId` and `entityId` as the persistent id.

I think this is an error and it should be

`PersistenceId = Context.Parent.Path.Parent.Name + "-" + Context.Self.Path.Name;`

which will use `typeName` and `entityId` as the persistent id (which will be unchanged if you ever need to change the `maxNumberOfShards`).

If I'm right please point me at the doc in source control and I'll raise a PR.

**Comment by Aaronontheweb** [comment]
I think this advice is outdated anyway - the `PersistenceId` shouldn't be married to the shardId because otherwise it would be impossible to change the shard count at a future point in time. This advice creates unnecessary coupling, in other words.

I'd stick to just using the `entityId` itself - that should be globally unique anyway, ideally, and if not you could just prefix it using a static identifier because you know what type the entity is at compile-time. 

We would _love_ a pull request here - the documentation you are looking for is at https://github.com/akkadotnet/akka.net/blob/dev/docs/articles/clustering/cluster-sharding.md
