### ISSUE TITLE
Akka Persistence Custom Serialization not being used with Generic Types

### ISSUE THREAD

**Issue by fluxlife** [akkadotnet/akka.net#4528]
I created a class that inherits and implements the `Akka.Serialization.SerializerWithStringManifest`

I successfully register the serializer via `app.conf` with the types I am looking to serialize.

```
akka.actor {
  serializers.my-event = <<type name of serializer that implements SerializerWithStringManifest here>>
  serialization-bindings {
     <<type that will be serialized>> = my-event
  }
}
```
I know the types and serializer are being registered because if I malform the strings above, I get a warning at startup.

If one of the types I am trying to serialize in my custom serializer is generic (i.e. `CloudEvent<T>`), My custom serializer is never used in persistence and the default serializer is used.

If I don't use _any_ generic types (i.e. `CloudEvent`) the custom serializer is used as expected.

- Which Akka.Net version you are using: 1.4.9
- On which platform you are using Akka.Net: F# / DotCore 3.1.302 / MacOS

**Comment by Aaronontheweb** [comment]
This looks less like a bug and more like a configuration issue - the problem is that for the serialization bindings, the type containing type needs to match. Do you have a non-generic interface on those generic types that you can target for the `serialization-binding`s?

Otherwise, you can try to create the serialization binding programmatically as that's now supported - this might be easier to do for your case since the `SerializationSetup` class can have its bindings type-checked and unit tested:

https://github.com/akkadotnet/akka.net/blob/163d5b8acef94e7340cab24d3fa196ddbe4e4ea0/src/core/Akka.Tests/Serialization/SerializationSetupSpec.cs#L60-L74

**Comment by Aaronontheweb** [comment]
Can you try either one of those and let us know if that resolves your issue?

**Comment by fluxlife** [comment]
I did solve my problem with non-generic types and that worked. 

I thought I saw 'progmatic' serialization registration in some release notes some where but couldn't find any documentation. Thank you sharing that!

Regardless, I understand about non-generic types but it was difficult to debug this issue and the only way I was able to realize what was going on was by looking at the manifest column in the event journal, etc. Not sure if there is a way to warn users about this, but just wanted to bring it to light, if anything to help the next person that may happen upon this issue :).

Thank you!

**Comment by Aaronontheweb** [comment]
> I thought I saw 'progmatic' serialization registration in some release notes some where but couldn't find any documentation. Thank you sharing that!

That is still on my to-do list. We want to do an overhaul of the documentation this year but we have some outstanding work to do on other projects.
