### ISSUE TITLE
Racy RemotingTerminator actor crash in Akka.Remote initialization

### ISSUE THREAD

**Issue by petrikero** [akkadotnet/akka.net#4530]
Using Akka v1.4.9 on Windows (though the issue seems platform agnostic).

When Akka.Remote is being spawned on a system under load, it is possible for the initialization sequence to use resources which haven't yet bee initialized. In particular, the `RemoteActorRefProvider` spawns the `RemotingTerminator` actor before initializing its `_internals` variable.

The `RemotingTerminator` actor ends up referencing the `_internals` when its initializing `FSM._log` is being initialized. The call chain is `Logging.GetLogger()` -> `LogSource.Create()` -> .. -> `LogSource.FromActorRef()` -> `RemoteActorRefProvider.DefaultAddress.get()` -> `RemoteActorRefProvider.Transport.get()`, which accesses `RemoteInternals.Transport`, which can end up null.

The code causing this issue is in `RemoteActorRefProvider.Init()`:
```
    _remotingTerminator =
        _system.SystemActorOf(
            RemoteSettings.ConfigureDispatcher(Props.Create(() => new RemotingTerminator(_local.SystemGuardian))),
            "remoting-terminator");

    _internals = CreateInternals();  // <- _internals initialized after spawning `RemotingTerminator` which uses _internals.
```

The tricky part is that the initialization sequence seems to be circular, as `CreateInternals()` uses the `_remotingTerminator` (which wants to access `_internals`).

The right way to fix this isn't obvious to me, but I'd be happy to implement the fix if you could guide me in the right direction.

**Comment by petrikero** [comment]
Not sure about this, but I believe this may actually get silently handled by the actor restarting and trying again until the `_internals` has been properly initialized.

I only see this when running under Visual Studio debugger which immediately stops on the exception being thrown.

**Comment by Aaronontheweb** [comment]
> The RemotingTerminator actor ends up referencing the _internals when its initializing FSM._log is being initialized. The call chain is Logging.GetLogger() -> LogSource.Create() -> .. -> LogSource.FromActorRef() -> RemoteActorRefProvider.DefaultAddress.get() -> RemoteActorRefProvider.Transport.get(), which accesses RemoteInternals.Transport, which can end up null.

Ah, so this is a bug - it comes from the changes we added to `LogSource` in order to fully append the remote address to outgoing log information to make the logs more useful.

Best way to fix this is to change the `ILoggingAdapter` implementation inside the `RemotingTerminator` so it uses an explicitly configured `LogSource`, rather than an automated one that is going to attempt to look up the `TransportInformation` from the `RemoteActorRefProvider`. I think I can fix this rather quickly.

**Comment by Aaronontheweb** [comment]
> Not sure about this, but I believe this may actually get silently handled by the actor restarting and trying again until the `_internals` has been properly initialized.

This is the case - otherwise Akka.Remote would leak connections like crazy during our unit test runs. The reason why this issue has persisted for so long without being reported is likely due to the fact that this error is handled by the actor lifecycle management.

These are the kinds of bugs users can find now that SourceLink support is much more widely available :)
