### ISSUE TITLE
Akka.Net 1.4.7: Sharing ExecutionContext with Actor thread when actor system is integrated and launched from Web Application startup

### ISSUE THREAD

**Issue by snrajan** [akkadotnet/akka.net#4539]
**Akka.Net : 1.4.7
Platform : Windows**

**Problem statement:** We are launching actor system from web application. Facing the issue while passing Open Tracing span(trace) context.   
                                               -------------------------
**Request Flow** :  Browser ---->| Web--->ActorSystem |
                                               --------------------------
Note: Actor System is launched from web application startup both are residing in same process.

**Details** : OpenTracing span context is created in Web Application and properly passed to Actors, where I am able to create new span and add to the active span(Tracer.ActiveSpan) created in web application hierarchy is working fine. But when I updated to higher version  >= 1.4.8 it was not working.

==================================================
```
Controller: 
public class DemoController : ControllerBase
 {
        private ITracer Tracer;
        private IServiceA ServiceA;

        public DemoController(ITracer tracer, IServiceA servicea)
        {
            Tracer = tracer;
            ServiceA = servicea;
        }


        [HttpGet]
        [Route("test1")]
        public async Task<string> Get()
        {
            
            using (Tracer.BuildSpan("DemoController-Get-" + HttpContext.TraceIdentifier).StartActive(true))
            {
                Tracer.ActiveSpan.Log("Logged in controller");
                await ServiceA.GetServiceAMessageTest1Async(HttpContext.TraceIdentifier);
            }

            Tracer.ActiveSpan.Log("Outside the Span in DemoController");
            return "Hello World";
        }
 }
```
==================================================
Service : 
 ```
public class ServiceAImpl : IServiceA
 {
        private ITracer Tracer;
        private IWebActorService WebActorService;

        public ServiceAImpl(ITracer tracer, IWebActorService webactorservice)
        {
            Tracer = tracer;
            WebActorService = webactorservice;
        }

        public async Task<string> GetServiceAMessageTest1Async(string id)
        {

            using (Tracer.BuildSpan("GetServiceAMessageAsync-ActiveSpan2-" + id).StartActive(true))
            {
                Tracer.ActiveSpan.Log("ServiceAImpl before calling inner method");
                await Task.Delay(TimeSpan.FromSeconds(5));
                using (Tracer.BuildSpan("GetServiceAMessageAsync-ActiveSpan3-" + id).StartActive(true))
                {
                    await Task.Delay(TimeSpan.FromSeconds(5));
                }
                Tracer.ActiveSpan.Log("ServiceAImpl before calling inner method but within");
            }

            Tracer.ActiveSpan.Log("Out side Using Blocks -" + id);
            return "Waited";
        }
}

 public class WebActorService : IWebActorService
    {
        private readonly IActorRef webActorRef;

        public WebActorService()
        {

        }
        public WebActorService(IActorRef webActor)
        {
            this.webActorRef = webActor;
        }

        public Task<T> Ask<T>(object message, TimeSpan? timeout = null)
        {
            return webActorRef.Ask<T>(message, timeout);
        }
    }
```
==================================================
Actor :
```
 public class WebActor : ReceiveActor
    {
        private ITracer Tracer;

        public WebActor(ITracer tracer)
        {
            Tracer = tracer;
            Receive<string>(msg =>
            {
                Tracer.ActiveSpan.Log("Received in actor");  //  Tracer.ActiveSpan is getting null from version 1.4.8 and it is working fine 
                                                                                      //   in 1.4.7
                Sender.Tell("done");
            });
        
        }
    }
```

=====================================================
Please let us know what is the changes made from version 1.4.8:

**Our Analysis** : Trace context will be added to ExecutionContext so that it can be access in another thread in case of async programming. Looks like from Akka.Net 1.4.8 ExecutionContext is not flowing correctly when ActorSystem is launched from web application.

**Comment by Aaronontheweb** [comment]
There were no fixes in 1.4.8 that would have caused this, as you can see via the full release notes and changelog here: https://github.com/akkadotnet/akka.net/releases/tag/1.4.8

Your traces were going to have this issue in 1.4.7 too - it was only a matter of time before you ran into problems.

You could look at Phobos https://phobos.petabridge.com for distributed tracing and monitoring inside your Akka.NET applications - your analysis is correct but the issue is that actors don't flow `ExecutionContext`, or more specifically `AsyncLocal`, because they don't use `await` internally to manage their asynchronous dispatching. We use a system built on top of the `ThreadPool` directly. 

We fixed this issue inside `Phobos` by adding a custom `OpenTracing.IScopeManager` which is better able to correlate state that occurs inside and outside the actor system. I'm considering redesigning how actors dispatch inside Akka.NET to use `IValueTask` so we can solve some other `ExecutionContext`-related issues (specifically, being able to set the `TaskScheduler.Default` ambiently).

That may solve your issue in the future, but we have no timeframe and no concrete plans for making those changes yet. Currently in the "idea" phase.
