### ISSUE TITLE
[Question] Akka.NET with Asp.Net Core

### ISSUE THREAD

**Issue by kaiohenrique** [akkadotnet/akka.net#4637]
Hello.
When deploying an Asp.Net Core API would Akka.NET and the host compete over the same ThreadPool by the default Dispatcher configuration? 

- Which Akka.Net version you are using: 1.3.13
- On which platform you are using Akka.Net ASP.NET CORE

**Comment by Aaronontheweb** [comment]
Hi @kaiohenrique 

Akka.NET and ASP.NET Core will both use the same `ThreadPool` by default inside the same process. You can change the default dispatcher Akka.NET runs on by modifying this HOCON setting:

https://github.com/akkadotnet/akka.net/blob/0876fbaea67c95b14368a61769077f53aad93aa6/src/core/Akka/Configuration/Pigeon.conf#L286-L331

Typically though, Akka.NET actors require much less CPU time than ASP.NET, since most actors aren't performing network I/O and serialization. You can change their dispatcher to run on a separate threadpool using a ForkJoinDispatcher but you probably don't need to do this for most applications.
