### ISSUE TITLE
Memory Leak when using many short lived instances of ActorMaterializer

### ISSUE THREAD

**Issue by DSanchen** [akkadotnet/akka.net#4659]
- Which Akka.Net version you are using: 1.4.x
- On which platform you are using Akka.Net: Windows 10

I wonder wether it is allowed to create and dispose of many instances of ActorMaterializers.
I have an actor that is created many times, and that actor starts a short lived akka stream, needing a ActorMaterializer.
So I thought it could be nice, if that actor just creates an ActorMaterializer and when it's done disposes it.
That does not seem to be a good idea, as each instance of an ActorMaterializer seems to create many other objects, that do not get cleaned up, once the ActorMaterializer gets disposed.
You can easily reproduce it with the following code:

```
ActorSystem actorSystem = ActorSystem.Create("myActorSystem");
Console.ReadKey(true);
while (true)
{
  ActorMaterializer materializer = actorSystem.Materializer();
  materializer.Shutdown();
  materializer.Dispose();
}                       
```

Take a memory dump before hitting a key, the let the while-loop run for some seconds, and the the second memory dump.
On my system the differential memory dump shows a result as follows:
![memoryleak](https://user-images.githubusercontent.com/16952004/101633126-2000f000-3a27-11eb-8d3f-854958cfb0ea.png)

**Comment by Aaronontheweb** [comment]
Yep, looks like a memory leak - we'll need to clean that up somehow.

**Comment by Arkatufus** [comment]
It is most probably caused by Hocon configuration fallback injection at this point: https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Streams/ActorMaterializer.cs#L77

Everytime a new `ActorMaterializer` is created, a copy of the default config is injected into the `ActorSystem.Settings` configuration stack, making it bigger and bigger. Since it is referenced by `ActorSystem.Settings` and not the `ActorMaterializer`, these allocated objects will never be released, not until the `ActorSystem` is disposed.
