### ISSUE TITLE
FSM Persistent Actor has inconsistent state transitions.

### ISSUE THREAD

**Issue by pirovorster** [akkadotnet/akka.net#4717]
Which Akka.Net version you are using
- Akka 1.3.17
On which platform you are using Akka.Net
- Windows 10

Summary:

If a PersistentFSM actor state does not have a corresponding when statement, it does not transition to the new state before calling the AndThen method.

```
When(ProcessSteps.Init.Instance, (evt, state) =>
{
	switch (evt.FsmEvent)
	{
		case StartMessage msg:
			{
				return GoTo(TestProcessSteps.Started.Instance)
					.Applying(msg);
			}
		default:
			throw new NotImplementedException();
	}
});
When(TestProcessSteps.Started.Instance, (evt, state) =>
{
	switch (evt.FsmEvent)
	{
		case TestActivityActor.ActivityCompletedMessage msg:
			{
				return GoTo(TestProcessSteps.Step1Completed.Instance)
					.Applying(msg)
					.AndThen(o=>
					{
						//HERE 

					});
			}

		default:
			throw new NotImplementedException();
	}
});

When(TestProcessSteps.Step1Completed.Instance, (evt, state) =>
{
	return Stay();
});
```

At the "//Here" comment the StateName property value is determined whether or not the following code exists
```
When(TestProcessSteps.Step1Completed.Instance, (evt, state) =>
{
	return Stay();
});
```

**Comment by Arkatufus** [comment]
This is an inteded behaviour. When you're using a `When`, you're registering a state to the state machine. When you try to change state to a "state" without when, the state machine does not have any reference to that state, so it will default to `Stay` on the previous state, which in your example is the `TestProcessSteps.Started.Instance` state. 

@Aaronontheweb What I'm a bit confused at is that when the FSM failed to find a transition state function because it couldn't find the target state name (state isn't registered), it still calls the `AndThen` handler, when it is actually terminated. Is this an intended behaviour?

**Comment by Arkatufus** [comment]
I did a code comparison with the original scala code, our behaviour is the same as theirs, so I'm not sure if these are actual intended behaviour or not.
