### ISSUE TITLE
Weird behavior with Akka cluster leader

### ISSUE THREAD

**Issue by tesgu** [akkadotnet/akka.net#4736]
Hi team

We are experiencing a weird behavior with Akka cluster. We haven't found anything related to this behavior in the docs, so maybe is a bug or maybe is by design.

We have a cluster and three seed nodes on it let's call them SN1, SN2, SN3. When they are marked as seed nodes in the hocon configuration they are thi this order (1, 2, 3) in the array of seed nodes.

If we start first SN2 machine without any other it never become the leader of the cluster, if we start SN3 without any other it never become the leader of the cluster. If we start both SN2 and SN3 none of them become the leader of the cluster.
If we start SN1 only, it becomes the leader of the cluster.

If we apply the following configuration:
SN1 -> [SN1, SN2, SN3] (as seed nodes)
SN2 -> [SN2, SN1, SN3] (as seed nodes)
SN3 -> [SN3, SN1, SN2] (as seed nodes)
everything works as expected.

We are simulating this with three processes (not with three machines), but I suppose the behavior is the same between machines.

We are using Akka.Cluster V1.4.10
This is the whole hocon configuration file present in the test program:

`            var akkaConfigurationContent = @"
                akka 
                {
                    actor
                    {
                        provider = ""cluster""
                        serializers
                        {
                            hyperion = ""Akka.Serialization.HyperionSerializer, Akka.Serialization.Hyperion""
                        }
                        serialization-settings 
                        {
                            hyperion 
                            {
                                version-tolerance = true
                            }
                        }
                        serialization-bindings
                        {
                            ""System.Object"" = hyperion
                        }
                    }   
                    remote 
                    {
                        dot-netty
                        {
                            tcp
                            {
                                port = 8092
                                hostname = ""localhost""
                                enable-ssl = true
                                ssl 
                                {
                                    suppress-validation = true
                                    certificate 
                                    {
                                        path=""c:\\akkacertificates\\*****************""
                                        password=""*******************""
                                    }   
                                }
                            }
                        }
                    }
	                cluster
                    {
		                name = ""the-cluster""
                        seed-nodes = 
                        [
                            ""akka.ssl.tcp://the-cluster@localhost:8091""
                            ""akka.ssl.tcp://the-cluster@localhost:8092""   
                            ""akka.ssl.tcp://the-cluster@localhost:8093""   
                        ]
                    }
                }";
`

Is this by design? Are we misunderstanding something?

**Comment by to11mtm** [comment]
This is by design.

So, here's how this works, more or less.

Now, for ease of explaining, lets assume there are 4 nodes.
All with seed nodes set up as  [SN1, SN2, SN3, SN4]

If -none- of the seed nodes are up, and the node is not the first seed node in the list, it will attempt to join the first seed node.
If it -is- the first seed node in the list, it will start the cluster with itself as a member.

Now, lets say the cluster has come up, but for whatever reason SN1, and then SN4 are taken down, but SN2 and SN3 are still up. SN2 becomes leader.
Let's also pretend SN1 doesn't come back up, but SN4 does

When SN4 comes back up, it will try to contact everyone else, see that SN2 and SN3 are still in the cluster, and successfully re-join. (Someone correct me if I'm wrong on that, but that's how I recall the behavior.)

Often seed nodes work well with something like [Lighthouse](https://github.com/petabridge/lighthouse) or some other paradigm where your seed nodes are primarily there to act as discovery points for other workers.

**Comment by tesgu** [comment]
Ok, understood. Thanks a lot for the explanation @to11mtm . ;)
