### ISSUE TITLE
Question: Are akka.net version numbers intended to be semver compliant?

### ISSUE THREAD

**Issue by mchandschuh** [akkadotnet/akka.net#4881]
I upgraded from 1.4.12 to 1.4.18 and had breaking changes due to `IPersistentRepresentation` adding `Timestamp` and `WithTimestamp` members.

Just curious for future knowledge -- we like to setup automatic package upgrades for those that are semver compliant.

Thanks!

**Comment by Aaronontheweb** [comment]
@mchandschuh yes, we do try to apply with SemVer but occasionally we run into instances where we have to introduce small breaking changes in revisions. In this case, it's because the base `IPersistentRepresentation` implementation uses all optional parameters in its only public constructor, so making any kind of changes to that are going to be breaking one way or another (this is one reason why we should probably start using record types in C# going forward.)

So sorry about that, we do try to document those when they do happen: https://github.com/akkadotnet/akka.net/releases/tag/1.4.14
