### ISSUE TITLE
How can I catch the StreamRefSubscriptionTimeoutException when using ISourceRef?

### ISSUE THREAD

**Issue by ClockGet** [akkadotnet/akka.net#5031]
Akka.Net version: 1.4.20
Akka.Streams version: 1.4.20
platform: win 10, .net core 3.1

code:
```
var sink = StreamRefs.SourceRef<byte[]>()
            .AddAttributes(StreamRefAttributes.CreateSubscriptionTimeout(TimeSpan.FromSeconds(5)))
            .AddAttributes(ActorAttributes.CreateDebugLogging(true))
            .AddAttributes(Attributes.CreateLogLevels(LogLevel.DebugLevel, LogLevel.InfoLevel, LogLevel.ErrorLevel));

StreamConverters.FromInputStream(() => pipe.Reader.AsStream())
.Select(p =>
{
    var bytes = p.ToArray();
    return bytes;
})
.RunWith(sink, Context.System.Materializer())
.PipeTo(remoteActorRef,success: sourceRef => sourceRef);
```
If the remote actor doesn't receive the ISourceRef message, after 5 seconds, the flow will be canceled. Then I attached the source code of Akka.Streams and debugged it to see what happened. Then I found that when the subscription timed out, a StreamRefSubscriptionTimeoutException would be thrown by the OnTimer method in the SinkRefStageImpl's nested class Logic, but it could not be received outside. What should I do to catch this exception in my code?

**Comment by Aaronontheweb** [comment]
I think this is very likely a bug with Akka.NET. We'll see about creating a reproduction for it and solving it.

**Comment by Arkatufus** [comment]
Currently, there is no way to capture this exception, as it is immediately swallowed by the `FailStage` method.

**Comment by Arkatufus** [comment]
The exception is thrown from [this line](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Streams/Implementation/StreamRef/SinkRefImpl.cs#L199), which bubbles up to [the try..catch block in `RunAsyncInput`](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Streams/Implementation/Fusing/GraphInterpreter.cs#L809), which are then handled by the [`FailStage` method.](https://github.com/akkadotnet/akka.net/blob/b1a9aa64ea71bce27dc6dbc7ead841bc8ded10df/src/core/Akka.Streams/Stage/GraphStage.cs#L1285).

`FailStage` will never propagate exceptions to the input port of a stage, and a sink only have an input port.

The JVM implementation somehow managed to get around this problem by passing a `Promise` object (`TaskCompletionSource` in C#), and flags async failure/success by setting the success/failure state of the promise object. We can't really adopt this method since JVM async implementation is completely different compared to ours.
