### ISSUE TITLE
Allow actors to have non-public constructors (mainly for unit testing)

### ISSUE THREAD

**Issue by BradKnowles** [akkadotnet/akka.net#5395]
**Is your feature request related to a problem? Please describe.**

I have an actor, `DownloadCoordinator`, that is responsible for receiving requests to download data at a given URL. 
 `DownloadCoordinator` creates a child `DownloadUrl` actor to deal with fetching the contents at the URL.  When `DownloadUrl` sends a `DownloadComplete` message back to `DownloadCoordinator`, `DownloadCoordinator` sends a `SaveFile` message to a sibling actor, `FileSystemCoordinator`, to farm out the responsibility of saving the file to disk.  

The constructor of `DownloadCoordinator` looks like this...
```csharp
public DownloadCoordinator(IActorRef fileSystemCoordinator)
{
    if (fileSystemCoordinator is null) throw new ArgumentNullException(nameof(fileSystemCoordinator));

    Receive<Messages.DownloadUrl>(message =>
    {
        _log.Debug("Received {Message}", message);

        var downloadUrlActor = DownloadUrlActor.Create(Context);
        downloadUrlActor.Tell(message);
    });

    Receive<Messages.DownloadComplete>(message =>
    {
        _log.Debug("Received {Message}", message);

        if (message.SaveToFile)
        {
            fileSystemCoordinator.Tell(new FileSystemCoordinator.Messages.SaveFile(message.DownloadPath,
                message.Contents, message.CorrelationId, message.MessageId));
        }
    });
}
```
This works fine except when it comes to unit testing.  I'd like to mock the `DownloadUrl` actor so that it doesn't actually download a URL when unit testing.  A pattern I like to use involves creating a `internal` constructor, that when combined with `InternalsVisibleTo` (yeah yeah I know 😄) allows my unit test to use the internal constructor to mock away certain dependencies.

```csharp
public DownloadCoordinator(IActorRef fileSystemCoordinator) : this(fileSystemCoordinator, null) { }

internal DownloadCoordinator(IActorRef fileSystemCoordinator, IActorRef downloadUrlActor) { }
```
This doesn't work since the code in `Props.Produce` uses `Activator.CreateInstance` which only looks for `public` constructors.
https://github.com/akkadotnet/akka.net/blob/55c117566bb7176351a4e2bc40e471e87f8eecfc/src/core/Akka/Actor/Props.cs#L669-L672

**Describe the solution you'd like**

A naive solution might be to simply add BindingFlags to allow public and non-public constructors.
```csharp
public ActorBase Produce()
{
    const BindingFlags flags = BindingFlags.NonPublic | BindingFlags.Public;
    return Activator.CreateInstance(ActorType, flags, null, _args, null).AsInstanceOf<ActorBase>();
}
```
Admittedly, I don't know all the ramifications of such a change.

**Describe alternatives you've considered**

I've read through the blog and the documentation, but wasn't able to figure out a way to let `DownloadCoordinator` create the child actor in production, but let me use a `TestProbe` when testing.

https://petabridge.com/blog/how-to-unit-test-akkadotnet-actors-akka-testkit/
https://getakka.net/articles/actors/testing-actor-systems.html

**Additional context**

Perhaps I've designed the whole thing wrong and need to rethink my setup.  I'm open to other options.

**Comment by to11mtm** [comment]
@BradKnowles I don't think your design is wrong per-se. Some of this is opinion (I mean, we are in the realm of dependency injection *and* unit testing :)

Here's what I'd do:

```
public interface IDownloadActorProducer
{
   IActorRef Create(Context ctx);
}

public class RealDownloadActorProducer : IDownloadActorProducer
{
  public IActorRef Create(Context ctx) => DownloadUrlActor.Create(Context);
}
```

Then you can have a constructor of `public DownloadCoordinator(IActorRef fileSystemCoordinator, IDownloadActorProducer producer)`, and for unit testing create a fake or mock of `IDownloadActorProducer` that gives you the IActorRef with the behavior you want. 

If I was lazy about it and didn't care about the tight coupling, I'd do `public DownloadCoordinator(IActorRef fileSystemCoordinator, Option<IActorRef> downloadActorOverride = Option<IActorRef>.None)` and just call it a day.

If I wanted to solve 'long term' I would start looking into an Akka DI Package that fit my needs, unless the app was small enough I was OK with maintaining hand-wiring of `Props` helpers in my composition root.

But I think you should do at least one of these. Probably not the Option one. Why? The ergonomic advantage of making these injectable as such in the long term is it will help minimize coupling, in case you want to change your routing architecture later, which is one of the huge benefits of Akka.

Lets say you push this design out and realize, oh dear, you've built an accidental DDOS Machine and need to put some throttling in. With the Interface design I suggested above, That could be as simple as making `IDownloadActorProducer` that instead gave me a consistent-hash, round robin, or smallest-mailbox `DownloadActor` pool. (If you need some failure signal, it's worth noting that you can `Context.Sender.Tell()` in `PreRestart()`.) Or lets say it works, but you realize that limiting downloads to 10 per domain at a time actually makes everything faster. Okay, ConsistentHash->SmallestMailbox->DownloadActor pool. Because you've refactored -all- your bits to the composition root, it's easier to play with all of these different parts, and *evolve* the routing architecture of your app as you learn and requirements change.

**Comment by BradKnowles** [comment]
Thank you @to11mtm for your detailed response!

In addition to unit testing, I feel there's an added benefit of encapsulating the creating of the actors.  I’ve seen the pattern of having static methods return `Props`, but I’ve taken it a step further and moved the actor creation to a static method as well.

```csharp
public static IActorRef Create(IActorRefFactory actorRefFactory, String name = null)
{
    if (actorRefFactory == null) throw new ArgumentNullException(nameof(actorRefFactory));

    return actorRefFactory.ActorOf(Props.Create<DownloadUrlActor>(),
        String.IsNullOrWhiteSpace(name) ? "downloadUrl" : name);
}
```

This allows me to do this inside a message handler of `DownloadCoordinator`..
```csharp
Receive<Messages.DownloadUrl>(message =>
{
    _log.Debug("Received {Message}", message);

    downloadUrlActor = DownloadUrlActor.Create(Context);
    downloadUrlActor.Tell(message);
});
```
Using this style, I could change the constructor (implementation and signature) and/or the`Create` method implementation without needing to change the usage.

Since the constructor must be public, a consumer could circumvent my `Create` method and new up the actor manually.  Which I would frown upon. 😄

However, I will work on some implementing your Producer suggestion and reply with my results.

**Comment by BradKnowles** [comment]
I want to say thanks again @to11mtm for your detailed response and your suggetsions.  I did implement the producer pattern you mentioned and it did work, as expected.   However, I opted to go with something closer to my original suggestion.  I created a new class implementing the `IIndirectActorProducer` interface and used this in my `Produce` method.

```csharp
public ActorBase Produce()
{
    const BindingFlags flags = BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance;
    return Activator.CreateInstance(ActorType, flags, null, _args, null).AsInstanceOf<ActorBase>();
}
```
When combined with the overload of `Props.CreateBy(IIndirectActorProducer producer, params object[] args)` I was able to achieve exactly what I wanted.
