### ISSUE TITLE
ActorPath is not serializable using standard Newtonsoft JSON serializer

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#553]
While trying to use `ActorRef.Tell` on an object having an `ActorPath` as a reference I've got following exception:

```
'Newtonsoft.Json.JsonConvert.SerializeObject(d)' threw an exception of type 'Newtonsoft.Json.JsonSerializationException'
    base: {"Self referencing loop detected for property 'Root' with type 'Akka.Actor.RootActorPath'. Path 'Parent.Parent'."}
```

I think this deserves to be described as a bug. ActorPath should probably have it's own custom serialization rule (maybe serialization to stringified path and parsed on deserialization?).

**Comment by rogeralsing** [comment]
When do you want to serialize an actor path instead of the actual ActorRef?

**Comment by Horusiath** [comment]
While porting Akka.Persistence I've found, that canonical Akka implementation heavily utilizes `ActorPath`s to **at least once** delivery confirmations. I'm not quite sure yet if it can be replaced by `ActorRef` or even `ICanTell` instances, but either way it think it should be a serializable value.

**Comment by Aaronontheweb** [comment]
@rogeralsing @Horusiath that makes sense - in order to resurrect a downed Actor inside `Akka.ClusterSharding`, which depends on `Akka.Persistence` internally you're going to care more about the `ActorPath` than the reference to a specific `ActorRef` instance itself. 

This is similar in concept to Orleans' virtual actors - only one instance of the Actor is actually doing work in the cluster at any given time, but it has hot replicas standing by elsewhere in the cluster in the event that the main actor dies. It uses Akka.Persistence under the hood to make sure that the internal state from the main actor gets shared with the replicas in a read-only fashion, so they can take over immediately in the event of main actor termination.

So we should make `ActorPath` serializable - I think stringifying / unstringifying it is pretty straightforward.

**Comment by rogeralsing** [comment]
See #557

**Comment by Aaronontheweb** [comment]
@rogeralsing does #581 solve this?

**Comment by rogeralsing** [comment]
@Horusiath has already fixed this
