### ISSUE TITLE
[RACY TESTS] RunAsAsyncEnumerable Throws on Abrupt Stream termination

### ISSUE THREAD

**Issue by eaba** [akkadotnet/akka.net#5546]
https://github.com/akkadotnet/akka.net/blob/4edb257d96c82f569a22e93e778c3a62ab9f483c/src/core/Akka.Streams.Tests/Dsl/AsyncEnumerableSpec.cs#L97-L125

When the test fails, it fails with the error message: `Akka.Streams.StreamDetachedException : Stream is terminated. Materialized value is detached.` 

I found two area where this is likely been thrown or set:

https://github.com/akkadotnet/akka.net/blob/db28aa32a6a6f5c98bc6fcd9ba275372cbf71229/src/core/Akka.Streams/Implementation/Sinks.cs#L808-L810

https://github.com/akkadotnet/akka.net/blob/db28aa32a6a6f5c98bc6fcd9ba275372cbf71229/src/core/Akka.Streams/Implementation/Sources.cs#L168-L178

Seeing that it is Set when `Logic` stops, two questions:
- Is lopgic not designed to be stopped?
- What could be the cause of `Logic` stopping?

**Comment by Aaronontheweb** [comment]
cc @to11mtm

**Comment by Aaronontheweb** [comment]
This is the offending code:

https://github.com/akkadotnet/akka.net/blob/3e0f97ccbb156b88953c38e5a55514fc122ce23a/src/core/Akka.Streams/Implementation/AsyncEnumerable.cs#L80-L93

Specifically, this line that throws:

https://github.com/akkadotnet/akka.net/blob/3e0f97ccbb156b88953c38e5a55514fc122ce23a/src/core/Akka.Streams/Implementation/AsyncEnumerable.cs#L83

And this is because when the stream shuts down that promise (`TaskCompletionSource<T>`) is set with an exception by the `PostStop` of the sink,

We probably need to just handle that exception gracefully rather than letting it blow up the stream.

**Comment by Aaronontheweb** [comment]
Need to add another `catch` block to this test:

```
 catch (StreamDetatchedException e) 
 { 
     thrown = true; 
 } 
```

And that should resolve this.

**Comment by Aaronontheweb** [comment]
IMHO, this is trying to test that the cancellation token gets invoked, but if the stream gets dethatched it accomplishes the same goal. We should handle either.
