### ISSUE TITLE
Memory leak in DistributedData on cross-node replication

### ISSUE THREAD

**Issue by Tavriets** [akkadotnet/akka.net#5553]
**Version Information**
Version: Akka.NET 1.4.32
Akka.NET Modules: Akka.DistributedData
Environment: Windows 11, .Net 6.0, no containers

Akka.DistributedData module leaks memory while replicating DData updates between nodes.

1. Create new project using _Petabridge Akka.Cluster Starter App_ template (pb-akka-cluster, v.1.2.0).
2. Add Akka.DistributedData module.
3. Modify existing _AkkaService_ class to perform periodic updates of the _LWWRegister_ items through the DData replicator with WriteAll consistency. 
4. Run 2 or more instances of the test app to form a cluster with data replication among nodes.
5. Each DData update operation would leave GC non-collectable LWWRegister instance locked on ActorRefResolveCache's ThreadLocal instance which eventually would flood Gen2.

Reproduction: [Akka.DistributedData-MemLeak](https://github.com/Tavriets/Akka.DistributedData-MemLeak)

**Expected behavior**
DData replicator should not leave zombie instances of LocalActorRef type after DData replication is done.

**Actual behavior**
![scr1](https://user-images.githubusercontent.com/3467807/151736834-a5ff1cea-fbab-4214-a8a7-e7587d34bb46.png)

The number of retained ActorRefResolveCache will grow proportionally to the number of DData updates:
![scr2](https://user-images.githubusercontent.com/3467807/151736979-e4f865d1-825d-41e3-a633-0838b22ba1b2.png)

A typical retention tree of the objects survived through GCs:
![scr3](https://user-images.githubusercontent.com/3467807/151737067-9e8e0962-52ff-4f32-8bb3-1084ad6d8e95.png)

Some additional observations:
- Problem seems to be replicable only within multi-node cluster. Single-node cluster without cross-node DData replication behaves well.
- Problem is not only limited to _LWWRegister_. Other CRDT types would stuck in Gen2 in the same way.
- The retrieval of values stored in the DData does not cause memleak, so it seems to be related to the update replication only.

**Comment by Arkatufus** [comment]
@Tavriets Thank you for the bug report, we'll be investigating it.

**Comment by Arkatufus** [comment]
This issue is not limited to DData, it affects any local actors that are being messaged through `Akka.Remote`. It shows up very prominently in DData because the `WriteAggregate` actor have a large payload and it is being created and removed in rapid succession.

The real issue lies in 2 places, `ActorRefResolveCache` and `LocalActorRef` class: 
* `ActorRefResolveCache` holds a reference to `LocalActorRef` until the cache is full and the old `IActorRef` got evicted, blocking it from being GC-ed. 
* `LocalActorRef` holds a reference to the original `Props` instance while it does not have any mechanism to release them. It is the `ActorCell` responsibility to release `Props` instance when the actor is killed/stopped.

**Comment by Aaronontheweb** [comment]
So to clarify, the issue here is that these `LocalActorRef`s have _already been killed_ and are not being GCed?

**Comment by Arkatufus** [comment]
Non-GC-ed `LocalActorRef` is fine since they're quite small, the problem is that it held a reference to `Props` that belongs to a dead actor.

**Comment by Aaronontheweb** [comment]
This fix will be available in our next nightly build https://getakka.net/community/getting-access-to-nightly-builds.html
