### ISSUE TITLE
Problem while getting a child actor's mailbox size

### ISSUE THREAD

**Issue by HamidEbr** [akkadotnet/akka.net#5997]
I cast an `IActorRef` object to `LocalActorRef `and use `Children `property of it for preparing a list of its children and also converting them (children) to `LocalActorRef`.
When I want to get the mailbox size of an Actor inside of its class, is used `(Context as ActorCell).Mailbox.MessageQueue.Count` and it works properly, but when I use `child[i].Cell.NumberOfMessages` (child[i] is a `LocalActorRef`), the value of `NumberOfMessages `is always be 0. Is it a bug or is there another way to get a child actor's mailbox size inside of a parent actor?

**Comment by Aaronontheweb** [comment]
So `ActorCell.NumberOfMessages` accesses `Mailbox.NumberOfMessages`

https://github.com/akkadotnet/akka.net/blob/138d576efd5e70644870f8059e0aa756233664ed/src/core/Akka/Actor/ActorCell.cs#L152

And that's implemented using

https://github.com/akkadotnet/akka.net/blob/138d576efd5e70644870f8059e0aa756233664ed/src/core/Akka/Dispatch/Mailbox.cs#L138

So they're using the same methods under the hood - the difference is whether or not you're polling the mailbox depth from within the actor that's processing messages or from the outside. Odds are that the value is returning `0` because you don't have the ability to block flow while you check, so you're in a race to observe those children's mailboxes before they get emptied - which you will generally lose given how fast they are.

Does that make sense?
