### ISSUE TITLE
ActorSystemSpec

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#60]
Port the ActorSystemSpec.scala to C#
(Download the Scala source code from https://github.com/akka/akka)

**Comment by alex-kondrashov** [comment]
I*d like to help out here. Is it ok if I work on this one?

**Comment by rogeralsing** [comment]
Absolutely, go for it! :)

**Comment by alex-kondrashov** [comment]
there is ActorSystemSpec.cs already in repository.  However ActorSystemSpec.scala is slightly different. Should ActorSystemSpec.cs be merged/overwritten according to scala*s version or left as it is?

**Comment by Danthar** [comment]
Is this still an active issue ?

**Comment by Aaronontheweb** [comment]
Our version should be updated to include all of the specs found in the Scala version. @alex-kondrashov or @Silv3rcircl3 or @Danthar, would any of you like to:

1. Verify that we've ported all of the specs and close out this issue or
2. Finish porting those specs and then close out the issue?

**Comment by Silv3rcircl3** [comment]
I will give it a try.

**Comment by Aaronontheweb** [comment]
Ty sir

**Comment by Silv3rcircl3** [comment]
I think I need some help here :)
This is what I found

Scala implementation | .Net implementation
------------ | -------------
[use scala.concurrent.Future's InternalCallbackEC](https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/actor/ActorSystemSpec.scala#L158) | I'm not sure if [this](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Tests/Actor/ActorSystemSpec.cs#L93) is the equivalent
[reject invalid names](https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/actor/ActorSystemSpec.scala#L162) | Is implemented [here](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Tests/Actor/ActorSystemSpec.cs#L29)
[allow valid names](https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/actor/ActorSystemSpec.scala#L178) | Is implemented [here](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Tests/Actor/ActorSystemSpec.cs#L46)
[support extensions](https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/actor/ActorSystemSpec.scala#L182) | Is implemented [here](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Tests/Actor/ActorSystemSpec.cs#L76)
[handle extensions that fail to initialize](https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/actor/ActorSystemSpec.scala#L189) | Not implemented yet
[log dead letters](https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/actor/ActorSystemSpec.scala#L199) | I think is implemented in [DeathWatchSpec](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Tests/Actor/DeathWatchSpec.cs#L56)
[run termination callbacks in order](https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/actor/ActorSystemSpec.scala#L212) | I think is not implemented, furthermore I couldn't find any reference of ```RegisterOnTermination``` in the ```ActorSystem``` although it is referenced in the ```Shutdown``` [summary](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Actor/ActorSystem.cs#L144)
[awaitTermination after termination callbacks](https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/actor/ActorSystemSpec.scala#L234) | See previous
[return isTerminated status correctly](https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/actor/ActorSystemSpec.scala#L251) | IsTerminated doesn't exist in the ```ActorSystem```, only in the context of an ```Actor```
[throw RejectedExecutionException when shutdown](https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/actor/ActorSystemSpec.scala#L266) | Also uses the ```RegisterOnTermination``` callback and I couldn't find the ```RejectedExecutionException```
[reliably create waves of actors](https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/actor/ActorSystemSpec.scala#L276) | Not implemented yet
[find actors that just have been created](https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/actor/ActorSystemSpec.scala#L283) | Not implemented yet
[reliable deny creation of actors while shutting down](https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/actor/ActorSystemSpec.scala#L288) | Not implemented yet
[shut down when /user fails](https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/actor/ActorSystemSpec.scala#L314) | I think is implemented in [SystemGuardianTests](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Tests/Actor/SystemGuardianTests.cs#L37)
[allow configuration of guardian supervisor strategy](https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/actor/ActorSystemSpec.scala#L322) | Seems to be not implemented at all, there are two TODO's ([here](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Actor/ActorRefProvider.cs#L158) and [here](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Actor/ActorRefProvider.cs#L183)) in the ActorRefProvider for this. 
[shut down when /user escalates](https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/actor/ActorSystemSpec.scala#L342) | Needs to change the guardian-supervisor-strategy, so can only implemented if the previous one is implemented
[work with a passed in ExecutionContext](https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/actor/ActorSystemSpec.scala#L357) | I'm not sure if [this](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Tests/Actor/ActorSystemSpec.cs#L99) is the equivalent
[not use passed in ExecutionContext if executor is configured](https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/actor/ActorSystemSpec.scala#L357) | If the ExecutionContext from scala is the equivalent of the Dispatcher in .Net, this is not possible at all since the ActorSystem has no constructor which accepts a Dispatcher
[not allow top-level actor creation with custom guardian](https://github.com/akka/akka/blob/master/akka-actor-tests/src/test/scala/akka/actor/ActorSystemSpec.scala#L406) | I don't know if it is possible to use a custom guardian, since I didn't found the expected ```UnsupportedOperationException``` I think it's not implemented

**Comment by Silv3rcircl3** [comment]
Last pending PR has been merged and all possible tests are implemented
