### ISSUE TITLE
Move to Paket for dependency management

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#609]
This is a free idea and can be applied basically by anyone at anytime, but we could change our package management inside Akka.NET solution to [Paket](http://fsprojects.github.io/Paket/). It makes managing dependecies and their versions a lot easier across multiple project and has better performance characteristics than NuGet.

**Comment by rodrigovidal** [comment]
If you wish, I can work in this issue.

**Comment by Horusiath** [comment]
I want the rest of @akkadotnet/developers to vote first.

**Comment by rogeralsing** [comment]
Here is my take on it;
Interacting with the F# community is a strategy that have played out quite well so far, and I do think Paket is a wonderful project and seems to get a lot of traction lately.
But at the same time, I do think that if we go all spaced out with all the newest shiny tools, it might be intimidating for C# users to get involved.
Everybody knows Nuget, even if it is a lack luster.
So we should think this through carefully before choosing either or.

Just my 2 cents.

**Comment by smalldave** [comment]
I've only played with Paket not used it in earnest. It seems to address some of my gripes with Nuget, particularly for multiple projects. Are we struggling to manage them now though?
Not sure I agree that it would put people off. We'd still publish Nuget packages wouldn't we?
Think people prepared to contribute are probably going to be happy to use / learn shiny tools?

My view is use it if it fixes problems we currently have.

**Comment by Aaronontheweb** [comment]
Just occurred to me - right now FAKE depends on the packages.config section inside each project to determine all of the user-facing NuGet dependencies every time we ship a new release of Akka.NET.

Since Paket's audience overlaps pretty strongly with FAKE, is it safe for me to assume that it wouldn't be a lot of work to rewrite this part of our NuGet build process to use Paket instead?

**Comment by aprooks** [comment]
Just my 2 cents about Paket. I've got 1 project which is maintained by c# devs only, so it is not intimidating at all. 

Though we've encountered some issues, like some nugets, that modify VS building process or vs itself could not work at all. E.g. xunit test runner https://github.com/fsprojects/Paket/issues/516 or octopack https://github.com/OctopusDeploy/OctoPack/pull/64

Paket simplifies dependency management alot, so we've even chose to use nunit + paket instead of xunit + nuget

**Comment by aprooks** [comment]
@Aaronontheweb yes it should not be an issue to migrate FAKE scripts as well as a whole project to Paket. Migration is pretty straightforward and well documented.

**Comment by rogeralsing** [comment]
@sforkmann (the Paket author) has volunteered to make the PR for this if we give a go for this

**Comment by forki** [comment]
I added a WIP pull request to see if this is possible. See #1243

**Comment by Danthar** [comment]
This was done. And we already migrated away from again. So Closed.
