### ISSUE TITLE
ActorSystem.Shutdown won't give time to flush all the logs

### ISSUE THREAD

**Issue by nvivo** [akkadotnet/akka.net#615]
When stopping the actor system, it won't give enough time to flush all the logs. This can be demonstrated with the following code:

```csharp
using Akka.Actor;
using Akka.Event;
using System;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            var system = ActorSystem.Create("MySystem");
            var test = system.ActorOf<Test>();
            test.Tell(1);
            system.AwaitTermination();
            Console.WriteLine("Stopped");
            Console.ReadLine();
        }
    }
    
    public class Test : UntypedActor
    {
        LoggingAdapter log = Logging.GetLogger(Context);

        protected override void OnReceive(object message)
        {
            for (var i = 0; i < 1000; i ++)
                log.Info("Message {0}", i);

            Context.System.Shutdown();
        }
    }
}
``` 

On my machine, the log is displayed until "Message 40" or so.

**Comment by Aaronontheweb** [comment]
This is by design - once the `Shutdown` call gets invoked everything dies.

We're working on adding support for post-termination hooks, but that still wouldn't really address this issue.

The best design pattern to make sure that mission-critical work gets completed before shutdown is to make sure that the same actor who accounts who the "completeness" of the job, flushing logs in this case, is also the one who makes the shutdown call to the actorsystem. That way the shutdown call can only be made once the work is finished.

**Comment by Aaronontheweb** [comment]
Going to mark this as closed.
