### ISSUE TITLE
Need to have API docs for each release on the site

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#637]
It would make it a lot easier to explain Akka.NET to new users if we could link directly to some NDoc content hosted on getakka.net somewhere. Doesn't need to be pretty - just needs to be available and versioned according to release.

**Comment by rogeralsing** [comment]
The site is generated via nodejs,Either we need to generate docs from the xml in that process, not ideal since we wont find any .net doc generators in npm land.
Or, our build process builds the ndoc stuff and publishes it to a repo that the site generator can clone.

Skickat från Outlook




On Mon, Feb 16, 2015 at 10:26 PM -0800, "Aaron Stannard" <notifications@github.com> wrote:












It would make it a lot easier to explain Akka.NET to new users if we could link directly to some NDoc content hosted on getakka.net somewhere. Doesn't need to be pretty - just needs to be available and versioned according to release.

**Comment by Aaronontheweb** [comment]
We can add an NDOC step to the build process and push that content into a new repo - would that work?

**Comment by rogeralsing** [comment]
:+1: yepp, that would be fine. we could add a web hook to that repo to trigger the site builder

**Comment by rogeralsing** [comment]
I've uploaded some example docs generated by Sandcastle here:
http://rogeralsing.github.io/help/

Im going to try to rewrite the templates so that the site header and footer can be added to the docs.

**Comment by Aaronontheweb** [comment]
@rogeralsing so I have the build server automatically generating this stuff now: 

http://petabridge-ci.cloudapp.net/repository/download/AkkaNet_AkkaNetWeeklyApiDoc/211:id/bin/doc/html/d75eb659-6335-53f6-af7a-81814a21ab7f.htm?guest=1

Runs on a weekly schedule - compiles a new set of docs for the latest stuff in the `/dev` branch every Monday at midnight UTC.

Once 1.0 ships (and the code that's necessary for generating the docs lives on the master branch) I'm going to have the RELEASE configuration of the build server automatically create one of these for latest stable AND run a separate build for the Git tag corresponding to the version number.

That way we can archive docs for past versions of Akka.NET

**Comment by rogeralsing** [comment]
The F# docs looks funky.. `LessBarBangOperator<'T>`
