### ISSUE TITLE
Association to [akka_ tcp://name_server:49766] with UId [1896650320] is irrecoverably failed. Quarantining address

### ISSUE THREAD

**Issue by SEMBM** [akkadotnet/akka.net#6414]
**Version Information**
Version of Akka.NET: 1.3.18 
Which Akka.NET Modules: Akka.Remote (via Cluster)

**Describe the bug**
Good morning, we are facing this exception every few days, nodes become unreachable although they could be in the same VLAN.
It was stable until we configured some Firewall rules over windows allowing only ports needed , for instance Start Port 49152 Number of Ports 16384 or in some servers Start Port 32767, number of ports 32768.
This is the exception
Akka.Pattern.IllegalStateException: Error encountered while processing system message acknowledgement buffer: [-1 []] ack: ACK[0, []] ---> System.ArgumentException: ack
Parameter name: Highest SEQ o far was -1 but cumulative ACK is 0
at Akka.Remote.AckedSendBuffer'1.Acknowledge(Ack ack)
at Akka.Remote.ReliableDeliverySupervisor.b__32_3(Ack ack)
--- End of inner exception stack trace -
**To Reproduce**
Can't reproduce it on purpose.

**Screenshots**
![image](https://user-images.githubusercontent.com/125868195/220089651-a0657981-2caa-42e7-92d5-00f5c3b5a01d.png)

**Environment**
Windows Which version of .NET--> Framework 4.7.0362

**Comment by Aaronontheweb** [comment]
This issue occurs after a network failure when either side of the Akka.Remote connection can't successfully ACK each other's system messages - usually it's `Context.Watch` notifications.

This is also for a fairly old version of Akka.NET that we don't really support anymore - we have made a ton of stability improvements to Akka.NET over the course of v1.4 and v1.5 is shipping next week. Please consider upgrading.

**Comment by Aaronontheweb** [comment]
## Reopening - Root Cause Identified

This bug still exists on the current `dev` branch. The underlying code in `AckedDelivery.cs` has not been substantively changed since 2021. We traced this to a production incident where a customer's 20-node Akka.NET cluster was completely downed by SBR due to this quarantine bug.

### Root Cause

The guard check in [`AckedSendBuffer<T>.Acknowledge()`](https://github.com/akkadotnet/akka.net/blob/108bc0eaea7f01fb932cdcb96e93f28a15f62fee/src/core/Akka.Remote/AckedDelivery.cs#L432-L436) throws an `ArgumentException` when it receives a stale ACK from a previous association:

```csharp
public AckedSendBuffer<T> Acknowledge(Ack ack)
{
    if (ack.CumulativeAck > MaxSeq)
    {
        throw new ArgumentException(nameof(ack), 
            $"Highest SEQ so far was {MaxSeq} but cumulative ACK is {ack.CumulativeAck}");
    }
```

[`MaxSeq` is initialized to `-1`](https://github.com/akkadotnet/akka.net/blob/108bc0eaea7f01fb932cdcb96e93f28a15f62fee/src/core/Akka.Remote/AckedDelivery.cs#L404) as a sentinel meaning "no messages sent yet."

### How This Triggers

1. Node A and Node B have an established connection. Node B's `AckedReceiveBuffer` has `CumulativeAck = SeqNo(0)` from previously received system messages.
2. Node A gets disrupted (network blip, GC pause, container freeze, etc.) - but the process stays alive.
3. Node A reconnects to Node B (same UID since neither process restarted). Node A's `ReliableDeliverySupervisor` calls `Reset()`, creating a fresh `AckedSendBuffer` with `MaxSeq = -1`.
4. Node B restores its stale `AckedReceiveBuffer` from the `_receiveBuffers` `ConcurrentDictionary` in `EndpointReader.PreStart()`, sees the UID matches, and calls `DeliverAndAck()`.
5. Node B sends `ACK[0]` based on its old state.
6. Node A receives the ACK. Guard check: `ack.CumulativeAck (0) > MaxSeq (-1)` → **true** → `ArgumentException` → `IllegalStateException` → **irrecoverable quarantine**.

### Why This Is Severe

This is not an exotic edge case. The trigger conditions are simply:
- A transient disruption where both sides stay alive (same UID)
- The disrupted node reconnects before SBR downs it
- Any system messages were previously exchanged (Watch/Unwatch, etc.)

In the production incident we investigated, this quarantine of a single node by all peers created an "indirectly connected" topology that caused SBR's `keep-majority` strategy to fire `DownIndirectlyConnected` and **down the entire 20-node cluster**, including itself.

### Proposed Fix

Change the hard throw to a no-op - if `MaxSeq` is -1 and the buffer is empty, there's nothing to acknowledge and nothing to corrupt:

```csharp
if (ack.CumulativeAck > MaxSeq)
{
    // Stale ACK from a previous association - nothing to acknowledge
    return this;
}
```

This is safe because the send buffer has been reset and is empty - there are no messages that could be incorrectly acknowledged or dropped.
