### ISSUE TITLE
[PERF] `ReceiveActor` memory allocation

### ISSUE THREAD

**Issue by ismaelhamed** [akkadotnet/akka.net#6450]
**Version Information**
1.5.0 (9c6501c7)
Akka

**Describe the performance issue**

There's a noticeably extra allocation happening in the `ReceiveActor` when compared to the `UntypedActor`. I think it'll be great to figure out where all that extra allocation comes from, and maybe do something about it.

**Data and Specs**

BenchmarkDotNet=v0.13.2, OS=Windows 11 (10.0.22621.1265)
AMD Ryzen 7 5700X, 1 CPU, 16 logical and 8 physical cores
.NET SDK=7.0.200
  [Host]     : .NET 7.0.3 (7.0.323.6910), X64 RyuJIT AVX2
  Job-BOAHGM : .NET 7.0.3 (7.0.323.6910), X64 RyuJIT AVX2

|       Method | ActorCount |        Mean |       Error |      StdDev |        Gen0 |        Gen1 |      Gen2 |  Allocated |
|------------- |----------- |------------:|------------:|------------:|------------:|------------:|----------:|-----------:|
| UntypedActor |     100000 |    845.0 ms |   228.13 ms |    59.24 ms |  32000.0000 |  31000.0000 | 2000.0000 |  479.73 MB |
| ReceiveActor |     100000 |    929.0 ms |    36.01 ms |     5.57 ms |  39000.0000 |  20000.0000 | 2000.0000 |  592.25 MB |
| UntypedActor |    1000000 | 11,512.2 ms | 2,086.63 ms |   541.89 ms | 418000.0000 | 313000.0000 | 3000.0000 | 6616.41 MB |
| ReceiveActor |    1000000 | 12,137.9 ms | 4,578.70 ms | 1,189.07 ms | 478000.0000 | 242000.0000 | 4000.0000 | 7549.41 MB |

You can find the benchmark used [here](https://gist.github.com/ismaelhamed/ec9c38f035a352f1293e76c6d21de0e1).

**Comment by Aaronontheweb** [comment]
@ismaelhamed could be delegate allocations or possibly the `MatchBuilder` and the compiled expressions

https://github.com/akkadotnet/akka.net/blob/8f186198545e24042b984d10036ac8419283dc56/src/core/Akka/Actor/ReceiveActor.cs#L23-L24

**Comment by Aaronontheweb** [comment]
I'd like to replace the expression compilation in the `ReceiveActor` with source generators eventually, in order to make this class AOT-friendly. That might also help address the memory usage too.

**Comment by woksin** [comment]
@Aaronontheweb I'd like to give this a shot!

**Comment by woksin** [comment]
I modified the ActorMemoryFootprintBenchmark a bit to showcase this issue and I can confirm that there is some overhead with the ReceiveActor https://gist.github.com/woksin/f090e3c06e85bf00246550b05121b72d

I also noticed that the benchmark seemed to run slower when the actor system was started and terminated as part of the global setup/cleanup in contrast to I set it to setup/cleanup per iteration

**Comment by woksin** [comment]
Also to probably no surprise when adding Receive-methods to the ReceiveActor it further increases the memory https://gist.github.com/woksin/09c28a08622075b16a0644a8bfff130b

**Comment by Aaronontheweb** [comment]
> @Aaronontheweb I'd like to give this a shot!

Go for it!

**Comment by Aaronontheweb** [comment]
> Also to probably no surprise when adding Receive-methods to the ReceiveActor it further increases the memory https://gist.github.com/woksin/09c28a08622075b16a0644a8bfff130b

So the `ReceiveActor` is bit of a relic from 2014, long before `switch` statements supported proper pattern matching. We used the expression compiler to cache the delegates declared inside the `Receive<T>` statements and had our own construct for matching incoming messages against each of them. We haven't revisited this design at all really since 2014 and I'm also quite confident that the `ReceiveActor` doesn't play nicely with AOT. 

I noted in some of my perf work right after .NET 7 shipped that `ReceiveActor` also doesn't play nicely with the JIT's Dynamic PGO either: https://petabridge.com/blog/dotnet7-pgo-performance-improvements/

It might be worth seeing if the underlying mechanism that the `ReceiveActor` uses behind the scenes could be re-written without the expression compiler, using more modern language constructs instead. I'm not 100% sure that's doable, but it's worth a try.

**Comment by woksin** [comment]
I think that it is impossible to take the current design of the `ReceiveActor` and make it as performant as the `UntypedActor` due to how it have to store the functions that handles the messages, you cannot get past the fact that it has to rely on reflection and capturing of the context which are expensive operations. Unless you want to utilize source generators somehow basically create something that is more similar to the `UntypedActor` by analyzing the given `Receive` lambdas and "unwrap" them into a simple `OnReceive(object msg)` method with if/else and/or pattern matching on the message. But I don't know how doable that is. And this feature would only be available on net5.0+

As you say the `ReceiveActor` (and in my opinion by extension the `UntypedActor` also) seems to be relics of the past where pattern matching was not so good in C#. I would argue that the developer experience using a `ReceiveActor` vs an `
UntypedActor` is very much the same now because of the new pattern matching features of C#. I would argue that the `UntypedActor` is perhaps a bit better because you cannot shoot yourself in the foot by using `Receive`-methods outside the context of the constructor which would result in a runtime exception and that the `Become`-methods are more clear in the `UntypedActor` vs the `ReceiveActor` because of the parameter being more explicit in what it is supposed to do. 

The `MatchBuilder` system  is basically "the only" underlying mechanism behind the `ReceiveActor` that differs it from the `UntypedActor`, and that system is only used for the `ReceiveActor` and `ReceivePersistentActor` (which is pretty much a copy-pase of `ReceiveActor` but with an extra `Stack` of `MatchBuilders` to keep in memory, the `Akka.Persistence` library actor classes suffers basically the exact same problems as the non-persistent versions). I don't really have high hopes that we can improve the `MatchBuilder` system significantly enough.

I realise that I sound pessimistic here, but I at least in my projects would see no reason to even use the `ReceiveActor`, perhaps the only added value might be the `ReceiveAsync`-methods but that can probably be done in the `UntypedActor` as well?

**Comment by Aaronontheweb** [comment]
> I realise that I sound pessimistic here, but I at least in my projects would see no reason to even use the ReceiveActor, perhaps the only added value might be the ReceiveAsync-methods but that can probably be done in the UntypedActor as well?

Yes there's a method you can use inside the `UntypedActor` to execute a `Task` inside the actor's context: [`RunTask`](https://getakka.net/api/Akka.Actor.UntypedActor.html#Akka_Actor_UntypedActor_RunTask_System_Func_System_Threading_Tasks_Task__) - but it's clunky IMHO.

**Comment by woksin** [comment]
I have a feeling that the performance gains we can realistically achieve here is not worth the effort. The essential problem is that the ReceiveActor is an artifact of the past and just using the UntypedActor now gives you almost all the same benefits with an additional performance benefit.

@Aaronontheweb I'd suggest to mark this as 'wont-fix'

**Comment by Aaronontheweb** [comment]
Will do
