### ISSUE TITLE
Future proof default serailization

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#681]
We should come to consensus on how to deal with the default serailization.
There are a few quirks around this topic.

1. We currently use Json.NET, I'd like that to be at least somewhat easy to change in the future
1. It should support serializing standard POCO classes so end users does not have too much friction
1. It should support serializing our internal primitives, `ActorRef` and friends
1. We should not have to abuse the design of our internal primitives to fit the serializer
1. It should support referencing primitives from user messages

We currently map `ActorRef` and `ActorPath` to surrogate types (think DTO's for the serializer)
This allows us to leave the Akka primitives untouched by the serializer. (it does have to implement an interface to let our serializer know that it should be surrogated though)

This would mean we would have clean primitives and the surrogates can carry whatever information they need in the serialization format.
This also removes the need for hacky stuff like `[JsonIgnore]` on properties in the Akka primitives.

Is this the way we should go?
I think it is a fair approach, the drawbacks is that we get more code to maintain, when we add stuff to a primitive (which wont be that often) we have to update the surrogate too, maybe.

This also makes it somewhat easier to replace Json.NET in the future, we just need to find a serializer that supports surrogates in some way.

Discuss

**Comment by HCanber** [comment]
I'd like to add one more thing: remove dependency to Json.Net in `Akka` project. Instead add a new `Akka.Serialization` project and put shared things in there, and a new `Akka.Serialization.JsonNet` with the Json.Net stuff. `Akka` project would then not be dependent on anything (more than standard Framework assemblies) which is great for embedded stuff and single process system.

I think surrogates is one way to go, but currently I'm leaning towards the last approach in this somewhat long comment...

#### Surrogates today
For those not familiar with how we use surrogates, below is an example of a usage of surrogate in `ActorPath`.
We have a JsonConverter, `NewtonSoftJsonSerializer.SurrogateConverter` that during serialization handles types that implements `ISurrogated` (`ActorPath` in this case), and in that case calls `ToSurrogate()` which returns the surrogate, which is serialized instead of the the actual type (`ActorPath` in this case). When deserializing, the surrogate is deserialized and `FromSurrogate()` is called on the surrogate which returns the real type (`ActorPath` in this case).

``` C#
public abstract class ActorPath : IEquatable<ActorPath>, IComparable<ActorPath>, ISurrogated
{
    public class Surrogate : ISurrogate, IEquatable<Surrogate>, IEquatable<ActorPath>
    {
        public Surrogate(string path)
        {
            Path = path;
        }

        public string Path { get; private set; }

        public object FromSurrogate(ActorSystem system)
        {
            ActorPath path;
            if (TryParse(Path, out path))
            {
                return path;   // returns an ActorPath
            }

            return null;
        }

        #region Implicit conversion operators

        public static implicit operator ActorPath(Surrogate surrogate) { ... }
        public static implicit operator Surrogate(ActorPath path) { ... }

        #endregion

        #region Equality

        public bool Equals(Surrogate other) { ... }
        public bool Equals(ActorPath other) { ... }
        public override bool Equals(object obj) { ... }
        public override int GetHashCode() { ... }

        #endregion
    }
    
    public ISurrogate ToSurrogate(ActorSystem system)
    {
        return new Surrogate(ToSerializationFormat());
    }

    public string ToSerializationFormat()
    {
        return ToStringWithAddress();
    }    
    ...
}
```

#### Surrogates in the future

- Do we need the implicit operators and equality stuff? Surrogate should only be used during transport, and not be used for anything else, so wouldn't the below be enough (`ActorRef` isn't equatable). This might be a special case I don't know of, but generally it shouldn't be needed.
- `ToSurrogate()` should be implemented explicitly (to hide it from the user).
- For maximum compatibility with other serializers than Json.Net let's use public get-set-properties in the surrogate

``` C#
public abstract class ActorPath : IEquatable<ActorPath>, IComparable<ActorPath>, ISurrogated
{
    public class Surrogate : ISurrogate
    {
        public string Path { get; set; }

        public object FromSurrogate(ActorSystem system)
        {
            ActorPath path;
            if (TryParse(Path, out path))
            {
                return path;
            }

            return null;
        }

    }
    
    ISurrogate ISurrogated.ToSurrogate(ActorSystem system)
    {
        return ToSurrogated();
    }

    protected virtual ISurrogate ToSurrogated()
    {
        return new Surrogate { Path = ToSerializationFormat() };
    }
    
    public string ToSerializationFormat()
    {
        return ToStringWithAddress();
    }    
    ...
}
```

#### Separation of concerns, let the serializer deal with serialization
The other alternative is to not use surrogates at all, but let every serializer decide how to serialize these types. For Json.Net we would, in the `Akka.Serialization.JsonNet` project have a JsonConverter for every type that cannot be serialized normally. This separates the concern of serializing an `ActorRef` from the concern of being an actor reference within the system.


#### Tests needed
No matter which method we choose, I think we still need tests that proves that all primitives that need to be serialized can be serialized and deserialized.

**Comment by rogeralsing** [comment]
The current approach uses Json Converters for the surrogate stuff, so we do not rely on the Json.NET built in surrogates other than the same name.
All the operator stuff and equality compares should be possible to remove now AFAIK.

See https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Serialization/NewtonSoftJsonSerializer.cs#L121

**Comment by Aaronontheweb** [comment]
@HCanber > Akka project would then not be dependent on anything (more than standard Framework assemblies) which is great for embedded stuff and single process system.

I think this is a **great** idea.

I still think the main project needs to have some form of built-in serialization (for when serialize all messages is turned on, designed to provide maximum immutability guarantees,) but for remoting and everything else we can push those dependencies out.

**Comment by rogeralsing** [comment]
But there is no difference berween serializing for remote vs serializing for serialize-all-messages=on.
We need the same features in both cases

**Comment by HCanber** [comment]
Can be solved like this: If you need to serialize all messages then you simple need to install one of the `Akka.Serialization.XXX` packages. Without a Serialization-package installed, the system would throw an exception if Serialize All messages is turned on.

**Comment by rogeralsing** [comment]
:+1:

**Comment by Aaronontheweb** [comment]
@HCanber yeah, we can keep the Serializer registry in Akka.Core and just check if anything has been bounded to it or not.

**Comment by rogeralsing** [comment]
One more thing to discuss.

In the current design, there is a bidirectional mapping between surrogate and surrogated types.
This makes it possible for users to create their own complex types that can be surrogated out of the box.

If we extract all the serialization bits to its own lib.
There is no way to describe for the serializer what types support surrogating, we have to explicitly tell that somehow.
Lets say we hardcode the akka primitives into a json converter, thats all fine and dandy.
but what if the end user wants to add a new type, or even another akka module wants to add new surrogated types.
How should we tell the serializer there are new types that needs special handling?

Manual registration?

`Akka.Serialization.NewtonsoftJson.RegisterType<SomeType/JsonConverter>(mySystem)`

Thoughts?

**Comment by Aaronontheweb** [comment]
@rogeralsing @HCanber new fly in the ointment I discovered yesterday when I was working on bringing `ConsistentHashRouter` up to code with canonical Akka.

`ConsistentHashingRoutingLogic` takes a dependency on all of the built-in serializers as part of its routing logic. Specifically, in the event that it's presented with a hash key that isn't a byte array, primitive, or string - so something like an `ActorRef` or a user-defined type, it needs to use the `Serializer` to serialize the key into a byte array before it can properly be hashed.

So consistent hash routing will fail most of the time without having serializers available. Had no idea about that until yesterday.

**Comment by HCanber** [comment]
Maybe we should have a look at having a Bootstrapper like Nancy has. Instead of `ActorSystem`

**Comment by HCanber** [comment]
@Aaronontheweb Thanks for learning me a new idiom :)

Manual or semi-automatic registration specific to the serilaizer is the way to go, I think. Something like this?
``` C#
ActorSystem.Create(name, config, c=>
  c.UseSerializer(Akka.Serialization.NewtonsoftJson.DefaultSerializer.With( collectionOfJsonConverters ))
);
```

__Bootstrapper__
Or maybe we should lift this question to a higher level, and discuss how we want the user to customize things in general.
Instead of the `Action<ConfigurationObject>` above and instead of supplying a config object to the actor system we could introduce a `Bootstrapper`, much like Nancy has. If no Bootstrapper is supplied to the ActorSystem constructor, all user assemblies are scanned for a class implementing `Bootstrapper`. If it's found it is used; otherwise a default one is used.

The bootstrapper would contain the configuration we have today (and by default finds it from app.config or web.config) and have extension points for customizing stuff that can't be customized in configuration (could very well contain things that can be put into configuration too).

`Bootstrapper` contains a virtual `CreateSerializer()` which by default scans all assemblies for a serializer. If none is found it returns a `ThrowExceptionsWhenUsedSerializer`. 
When importing a Serialization package, like `Akka.Serialization.NewtonsoftJson` it will be automatically found by the `Bootstrapper` and used.
By default the JsonDeserializer scans all assemblies after types implementing `JsonConverter` and hooks them up automatically (I've used this variant in a couple of projects myself). If the user wants more control, they would supply their own instance of the serializer, with the converters in place, by overriding  `CreateSerializer()` on the `Bootstrapper`.

``` C#
//with no class implementing Boostrapper, the call below would use the default bootstrapper
//which gets config from app.config/web.config, and scans for a serializer and uses it if it's found
ActorSystem.Create("mySystem");
```

``` C#
public class Bootstrapper : DefaultBootstrapper
{
  public override ISerializer CreateSerializer()
  {
     return Akka.Serialization.NewtonsoftJson.DefaultSerializerWithConverters(new MyTypeJsonConverter(), new MyOtherTypeJsonConverter);
  }
}

//The bootstrapper above will be found, instantiated, and used by the call below
ActorSystem.Create("mySystem");
```

**Comment by Aaronontheweb** [comment]
@rogeralsing can this be closed?

**Comment by HCanber** [comment]
I think we can move some of the ideas into a new issue "Remove dependency to Json.net from Akka-project" or however it should be phrased, i.e. move the json-net serialization to a new `Akka.Serialization.NewtonsoftJson` project.

**Comment by rogeralsing** [comment]
Starting this thread again

We need to find a serializer that supports these features:

1. It should be an instance, so we can associate it with a specific actorsystem.. so no static api
2. It should support polymorphic serialization.. so Cat and Dog comes out as Cat and Dog and not as Animal on the other end
3. It should support surrogates, so we can surrogate ActorRefs and such objects when serializing
4. It should not require [DataContract] or any other annotations or intrusive design on the messages
5. It should be fast, it doesn't need to be the fastest one out there, but decent performance is a must have.

**Comment by Horusiath** [comment]
cc #999 @akkadotnet/developers

**Comment by rogeralsing** [comment]
I've been testing a bit using Json.NET 7 with Bson writer.
That works pretty good. 
There is a small quirk that Bson does not allow primitives as the root object. eg. if you pass a single integer.
So root primitives needs to be stored in some sort of envelope. other than that, all serialization tests pass.

if that works out, I think we should switch from json to bson, as bson is more compact

**Comment by magnodeveloper** [comment]
It's 3.5 years later and still Akka core library brings in a reference to Newtonsoft.  Is this going to be addressed?
