### ISSUE TITLE
ActorSelection fails on mono on OSX when paths start with /

### ISSUE THREAD

**Issue by bruinbrown** [akkadotnet/akka.net#687]
During ActorPath parsing, a check is made to load in the actor path as an absolute Uri. On Mono (on OSX at least), when parsing an ActorPath which starts with /, this is a valid absolute file URI. This means that any ActorSelection of this form returns the dead letters address instead. It's currently possible to temporarily fix this by adding akka://<system-name> before all absolute paths.

**Comment by rogeralsing** [comment]
oooh... thanks for finding the cause for this!

**Comment by migueldeicaza** [comment]
The issue here is that the Uri API is broken by design.

Microsoft allowed Uris to take paths without the "file://" prefix.   This means that it is valid to call Uri like this:

     new Uri ("c:/autoexec.bat")

Usually the issue comes up with code like this:

    foreach (var f in Directory.GetFiles (...)) 
        xxx (new Uri (f));

So we had to make Uri allow paths, which in Unix includes "/"

The solution is to use the full Uri constructor and full specifiers.

**Comment by Aaronontheweb** [comment]
Thanks @migueldeicaza - this is extremely helpful.

**Comment by Aaronontheweb** [comment]
#708 should fix this. Going to keep the PR open to get some confirmations from our Mono users first.
