### ISSUE TITLE
ConsumerController is Deadlocked in WaitingForConfirmation Status

### ISSUE THREAD

**Issue by briansain** [akkadotnet/akka.net#7088]
**Version Information**
Version of Akka.NET? 1.5.15
Which Akka.NET Modules? Akka.Delivery and Akka.Persistence

**Describe the bug**
If the ConsumerController tries to delivery a SequencedMessage<T> to the consumer, but the consumer is not able to be created and doesn't receive the SequencedMessage<T>, then the ConsumerController is deadlocked because it doesn't try to resend the SequencedMessage<T> again. The ProducerController sends a Retry message to the ConsumerController, but the ConsumerController ignores it.

**To Reproduce**
For our issue specifically, this occurs whenever our true "receiving" actor is created by a Manager. The Manager receives the message from the ConsumerController and will forward said message to a child, who is the true consumer. The child is not able to be created/hydrated due to some SQL Timeout or transient error at the time. The ConsumerController was able to "Tell" the Sequenced message but our manager was not able to forward it on. The ConsumerController is now stuck because it doesn't retry to send this message. 

I can create a small POC in Github if needed.

**Expected behavior**
I expect our consumer receive multiple instances of the message, so that the consumer actor has multiple attempts to be created. 

**Actual behavior**
The ConsumerController is stuck in a WaitingForConfirmation status without a way to get out of that status.

**Screenshots**

**Environment**
Azure Kubernetes

**Additional context**

**Comment by Aaronontheweb** [comment]
The `ConsumerController` needs to be configured to accept an optional "idle timeout" of some kind, in scenarios where the `Consumer` couldn't finish the job for some reason (i.e. the consumer forwards that message to another actor who does the work and replies back, but that other actor was shut down before it could process the message.)

Having some idle timeout + retry functionality in here would allow the `ConsumerController` to take the reins here and prevent the end-user from having to author some of their own downstream functionality for handling retries et al. Changing the defaults to use this timeout automatically might be a bit of a breaking behavior change for some users, but I don't know how widely used Akka.Delivery is exactly (so that issue might be purely theoretical.)

The current HOCON:

```hocon
akka.delivery{
consumer-controller {
      # Number of messages in flight between ProducerController and
      # ConsumerController. The ConsumerController requests for more messages
      # when half of the window has been used.
      flow-control-window = 50

      # The ConsumerController resends flow control messages to the
      # ProducerController with the resend-interval-min, and increasing
      # it gradually to resend-interval-max when idle.
      resend-interval-min = 2s
      resend-interval-max = 30s

      # If this is enabled lost messages will not be resent, but flow control is used.
      # This can be more efficient since messages don't have to be
      # kept in memory in the `ProducerController` until they have been
      # confirmed, but the drawback is that lost messages will not be delivered.
      only-flow-control = false
    }
}
```

If we added another setting:

```hocon
akka.delivery.consumer-controller.retry-confirmation = false
```

And have it default to `off`, but when it's enabled we could allow the `ConsumerController<T>` to process `Retry` requests and redeliver the current message to the `Consumer`. I'd need to check to see if we still _have track_ of the current message in the `WaitingForConfirmationState` because that's another issue possibly, but this is the basic opt-in design we could support to fix the problem from an end-user standpoint.

**Comment by Arkatufus** [comment]
This is by design, you will need to redesign your code so that there is a guarantee that the `Manager` actor **will** acknowledge that the message has been received in the future.
