### ISSUE TITLE
Add Mono framework target for Akka.Cluster nuget package

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#812]
Unfortunately some of the code built into Akka.Cluster is very platform specific - namely the `MetricsCollector` responsible for reporting on CPU / Memory utilization for each individual node in the cluster.

There's a specific performance counter we have to read to get total available memory for Mono, and a totally different method for Windows. Neither is x-plat compatible with the other (AFAIK.)

So the solution is to use pre-compilation directives and build platform-specific distributions of Mono for modules like Akka.Cluster that have this problem.

One of the things we'll need to do is add a Mono framework target to the NuGet package for these distributions - kind of like we'd do if we wanted to distribute a .NET 4.0 version of Akka.NET.

Does anyone have any idea how to do this *for Mono specifically*? I couldn't find what I was looking for inside the nuget.org docs.

**Comment by kekekeks** [comment]
A lot of people who use Mono are deploying binaries built with Visual Studio (since Mono C# compiler and xbuild aren't that great). So it's not a good idea to ship a separate binary for Mono, it's better to select the implementation at run-time based on `Type.GetType("Mono.Runtime") != null`

**Comment by Aaronontheweb** [comment]
@kekekeks in this case the issue is that on Windows we depend on a specific library that isn't available in Mono (don't laugh, but it's the VB.NET runtime - [here's why we use it](http://stackoverflow.com/questions/105031/how-do-you-get-total-amount-of-ram-the-computer-has).)

If we can come up with a platform-independent way of getting this data (it might be as simple as using a performance counter supported on both platforms) then that will eliminate this as a requirement.

**Comment by Aaronontheweb** [comment]
> it might be as simple as using a performance counter supported on both platforms

(I have looked into this, but haven't settled on anything conclusive yet.)

**Comment by Aaronontheweb** [comment]
(I might also be missing something really obvious, which happens more often than I'd like to admit ;) )

**Comment by kekekeks** [comment]
@Aaronontheweb
>in this case the issue is that on Windows we depend on a specific library that isn't available in Mono

It's actually not an issue. If class isn't used, CLR/Mono won't try to load libraries it depends on. So on Mono we can safely use binaries compiled for .NET.

If one wants to use MonoDevelop for development (very strange idea from my point of view, because you can't use ReSharper) or as debugger (way more useful for this purpose), just wrap code that uses VB.NET library in
```csharp
#if __MonoCS__ 
#else
//Your code
#endif
```
So it will compile with Mono. 


BTW, VB runtime *is* [available in Mono](https://github.com/mono/mono-basic/blob/master/vbruntime/Microsoft.VisualBasic/Microsoft.VisualBasic.Devices/ComputerInfo.vb) (`TotalPhysicalMemory` is a stub through). It's also [packaged for Ubuntu](http://packages.ubuntu.com/trusty/libmono-microsoft-visualbasic11.0-cil).

**Comment by kekekeks** [comment]
This should be sufficient (`GetVbTotalPhysicalMemory` is introduced because referenced assembly is loaded [when referencing method is entered for the first time](http://stackoverflow.com/questions/2785520/when-are-referenced-assemblies-loaded))

**Comment by kekekeks** [comment]
I'm also concerned about [UnboundedMailboxQueue.cs](https://github.com/akkadotnet/akka.net/blob/ce561dd51755e0b46f429d092691e494232fb811/src/core/Akka/Dispatch/MessageQueues/UnboundedMailboxQueue.cs) and [ConcurrentQueueMailbox.cs](https://github.com/akkadotnet/akka.net/blob/f186681b25f00970dc51f5db082aeda2c13c90d0/src/core/Akka/Dispatch/ConcurrentQueueMailbox.cs). Why [MonoConcurrentQueue.cs](https://github.com/akkadotnet/akka.net/blob/ce561dd51755e0b46f429d092691e494232fb811/src/core/Akka/Util/MonoConcurrentQueue.cs) is used here instead of system one?

**Comment by rogeralsing** [comment]
@kekekeks the MonoConcurrent should be removed, we used ths earlier as the system one was broken and subject of all sorts of RC's. thus preventing Akka.NET from running at all on earlier versions of mono.

This is no longer the case, so we can safely remove it.

**Comment by Aaronontheweb** [comment]
@kekekeks 

> It's actually not an issue. If class isn't used, CLR/Mono won't try to load libraries it depends on. So on Mono we can safely use binaries compiled for .NET.

That's good to know!

> If one wants to use MonoDevelop for development (very strange idea from my point of view, because you can't use ReSharper) or as debugger (way more useful for this purpose), just wrap code that uses VB.NET library in

That's where this came up - had to spend some time working exclusively on Ubuntu 14.04 right before the V1 release to ensure that the Mono fixes for our transport layer worked as expected. Ended up wrapping the code inside a pre-processor directive like you showed.

**Comment by Aaronontheweb** [comment]
@kekekeks sold me - better to just guarantee runtime compatibility in the binaries.
