### ISSUE TITLE
IStash shouldn't expose "Prepend(IEnumerable<Envelope>)"

### ISSUE THREAD

**Issue by nvivo** [akkadotnet/akka.net#875]
Currently, IStash [exposes](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Actor/Stash/IStash.cs#L47) `Prepend(IEnumerable<Envelope>)`, and this is only used in the [Eventsourced implementation](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Persistence/Eventsourced.cs#L296). This method is internal to akka in the [scala implementation](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/Stash.scala#L172), but interfaces can't apply this kind of constraint in C#.

I propose removing this method from the `IStash` interface to prevent users from calling it during normal application development.

This can be exposed by using a new advanced/internal interface that all stashes implement and make Eventsourced use this interface instead:

```cs
interface IInternalStash : IStash
{
    void Prepend(IEnumerable<Envelope> envelopes);
}
```

**Comment by nvivo** [comment]
**Additional info:**

I'm raising these question as I'm updating the docs for Stashing, so I'm interested to know if these features are really public api and should be documented and have examples.

I'd raise the same question about some other members on IStash that expose the `Envelope` class to the user. Do users need to access these members as well? 

```cs
void UnstashAll(Func<Envelope, bool> predicate);
IEnumerable<Envelope> ClearStash();
```

It seems the JVM implementation is quite different in this area. Should IStash expose only the basic "Stash, Unstash and UnstashAll" that are previously documented and move everything else to an `IInternalStash`? And if ClearStash is a valid option, shouldn't it be exposed as "void" to the user?

**Comment by rogeralsing** [comment]
cc @HCanber @Aaronontheweb

**Comment by Aaronontheweb** [comment]
@nvivo 

I'll address this backwards:

```cs
void UnstashAll(Func<Envelope, bool> predicate);
IEnumerable<Envelope> ClearStash();
```

These are both meant to be exposed to end-users - the purpose of the first method is to give the user an option to unstash messages based on its contents (which includes the Sender, hence why `Envelope` is exposed.)

The purpose of the second method is to just dump the contents of the stash - perfectly valid choice in a lot of cases (imagine a restart where you want to send those messages to someone else.) Better off returning the content than permanently deleting it, so that way the end-user can decide what happens next.

So those two methods are fine as-is.

> I propose removing this method from the `IStash` interface to prevent users from calling it during normal application development.

Technically - you're right. The `Prepend` method should not be exposed to end-users.

If ever in the future you find yourself in an argument discussing the merits of returning abstract base classes versus interfaces from an API, please refer to this exact problem :p 

ABCs are more naturally suited to this type of API extensibility (different levels of visibility) than interface-driven ones are.

That being said though, removing a method from a public interface is a big deal - means that there's no backwards compatibility in any DLLs that depended on a previous version of that interface. So I'm going to recommend just leaving that method there for now. 

Who knows? Maybe users will come  up with an interesting way of using it other than what we intended. But for now maybe it's best to just document that method with an comment along the lines of INTERNAL API.

**Comment by nvivo** [comment]
Thansk for the detailed explanation @Aaronontheweb.

I'll add a note to the docummentation according to your suggestion.

**Comment by jpierson** [comment]
BTW, I just came across this post in hopes of clarifying whether Prepend can be used as a reasonable solution for reversing the order of stashed messages before they are processed. Perhaps there is a better way of achieving this but so far this is the only solution that really sticks out at me.
