### ISSUE TITLE
FAKE: eliminate duplicate test runs

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#893]
We should try to cut our build times down, and the best way to do that is to modify our FAKE F# script to eliminate duplicate test runs.

The Akka.Cluster specs get run 3 separate times, for instance.

If we add the MultiNodeTests to our suite and those get run more than once it can add 10-15 minutes per run.

**Comment by annymsMthd** [comment]
I have a fix for that. The reason Akka.Cluster was ran 3 times was because it was referenced in two projects. Fake was finding all three dlls. Test suites should really be leaf nodes and we can move any shared code into the shared libraries, like we have already. The extra references have been removed in #888

**Comment by Aaronontheweb** [comment]
Awesome! Thanks @annymsMthd

**Comment by annymsMthd** [comment]
This is fixed.
