### ISSUE TITLE
Making DI more accessible

### ISSUE THREAD

**Issue by thomaslazar** [akkadotnet/akka.net#965]
It's currently kinda "hard" to use DI with Akka.net.

You need need to either drag around an IDependencyResolver (as shown in the documentation) to create the Props for Actors or use actorSystem.GetExtension<DIExt>() (not documented) to get access to a Props Props(Type actorType) method that lets you create Props through the DI container.

There is an extension DI() for IActorContext shown in the documentation that gives you access to a ActorOf<TActor>(string name) method that lets you create Child Actors. But that method doesn't let you configure the created actor in code because it returns an IActorRef.

My suggestion would be to add an extension DI(this ActorSystem system) to the ActorSystem to make it similar to that of the IActorContext class.

In addition to that a way should be added to just have the Props be created through the DI container so that one can configure an Actor in code as well. I would suggest adding Props<TActor>() methods in each Adapter class.

**Comment by jcwrequests** [comment]
@thomaslazar Would you mind putting together an example on how your changes make it easier? Maybe take one of the examples from the DI contrib a rewrite it with your code extension. That way it makes comparing the two version much easier. Anything that can be done to make it easier is always welcome. 

Thanks so much for taking the time and putting in the issue.

 I look forward to see your examples.

**Comment by jcwrequests** [comment]
@thomaslazar Sorry I did not see your PR. Would you mine still putting together an example? Thanks.

**Comment by thomaslazar** [comment]
@jcwrequests I changed the castle windsor example to use the new extension. but the examples currently in the repository don't really show the problem that my changes try to solve. For that to be more apparent I'd have to whip up a ASP.NET example using DI and Akka.net. I will try to see if i can get something up on Thursday.

**Comment by nvivo** [comment]
Should have seen this discussion before. Ended up with a long post on [#966](https://github.com/akkadotnet/akka.net/pull/966#issuecomment-101236649), sorry for that. Anyway, take a look there and let's see if we can come up with something better.

**Comment by Danthar** [comment]
@nvivo  I agree with your response on #966 . The DI api as it is now does feel 'awkward'. This is a direct result of using the existing plugin architecture of Akka to provide DI support.

> Even being a port, we should be allowed to improve things every now and then.

Obviously therein lies the danger that the more you 'improve' (thus deviate) from the original project. You could reach a point where you can no longer call it a port of Akka.

I don't know how the @akkadotnet/owners feel about this. But I don't think that providing a better DI support story for akkadotnet automatically means diverging from the original Akka project. 
Since Akka has the exact same API for DI as Akkadotnet has now. I assume they have largely the same issues as the ones we have identified here. 

If the @akkadotnet/owners agree that the DI support could use some work, it might be a good idea to contact the TypeSafe guys and ask their opinion on this. 
Maybe they feel the DI support could use an overhaul as well. Which would be great, because it means akkadotnet and akka can work together to create a better DI support story that will be supported by both versions of the framework. 
My 2 cents

**Comment by rogeralsing** [comment]
@Aaronontheweb had a meeting with Roland from Typesafe yesterday regarding DI. I dont know the outcome of that conversation yet

**Comment by Danthar** [comment]
For the people wondering what the status of this issue is: The discussion continued in #966

**Comment by rogeralsing** [comment]
Im closing this as #966 have been merged
